---
title: 作用群的选择
subtitle: 幂零锥和其上的几何：以 $\mathfrak{gl}_n$ 为例
author: sun123zxy
date: 2026-03-30
lang: zh
bibliography: index.bib

draft: true

categories:
  - math
  - algebra

collections:
  - nilpcone

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\gl}{\mathfrak{gl}}
\newcommand{\SL}{\mathrm{SL}}
\newcommand{\PSL}{\mathrm{PSL}}
\renewcommand{\sl}{\mathfrak{sl}}
\newcommand{\ad}{\operatorname{ad}}
\newcommand{\End}{\operatorname{End}}
\newcommand{\Ad}{\operatorname{Ad}}
\newcommand{\Aut}{\operatorname{Aut}}

[上篇](/posts/20260321-geo-nilp-gln/) 中简单介绍了复数域上 $\gl_n$ 或 $\sl_n$ 的共轭 / 幂零轨道的定义．这是 ad hoc 的．一般来说，不同的群作用在李代数 $\mathfrak{g}$ 上可能导致不同的轨道．本篇介绍我们选择作用群的标准，主要参考 [@mcgovern_nilpotent_1993, {section 1.2}]．

仍然以 $\gl_n$ 为例．一般来说，我们可以考虑全体 $\gl_n$ 的李代数同构 $\Aut_{\gl_n}(\gl_n)$ 在 $\gl_n$ 上的作用．这是个代数群，其上的几何结构由如下一般的步骤得到：

- 设 $\mathfrak g$ 是一个 $n$ 维李代数，则选取一组基底 $(e_i)_{i=1}^n$ 可获得 $n$ 维仿射空间结构

- 全体其上的线性变换 $\End_{\mathbb C}(\mathfrak g)$ 是 $n^2$ 维的仿射空间，基底 $(E_{i,j})_{i=1,j=1}^{n,n}$ 由 $\mathfrak g$ 的基底诱导得到

- 在 $\End_{\mathbb C}(\mathfrak g)$ 上做线性同构限制，即要求行列式非零，得到开子簇 $\Aut_{\mathbb C}(\mathfrak g)$．注意这个动作也可以实现为仿射簇．

- 在 $\End_{\mathbb C}(\mathfrak g)$ 上做李代数同态限制得到 $\End_{\mathfrak g}(\mathfrak g)$，即要求
  $$
  \varphi ([x, y]) = [\varphi(x), \varphi(y)], \quad \forall x, y \in \mathfrak g
  $$
  此式关于 $\mathfrak g$ 和 $\End_{\mathbb C}(\mathfrak g)$ 的基底线性展开后是若干关于 $\varphi$ 在基底 $(E_{i,j})$ 下线性组合系数的多项式方程．因此 $\End_{\mathfrak g}(\mathfrak g)$ 是 $\End_{\mathbb C}(\mathfrak g)$ 的闭子集．【TODO：簇？】

- 取 $\Aut_{\mathfrak g}(\mathfrak g) := \End_{\mathfrak g}(\mathfrak g) \cap \Aut_{\mathbb C}(\mathfrak g)$，这是 $\End_{\mathbb C}(\mathfrak g)$ 的拟仿射子【TODO】

:::{.remark}

TODO：看上去这个过程对一般的 $\mathfrak g$-模也可以做．特别地，上面相当于是在对伴随表示 $\ad_{\mathfrak g}$ 做．
:::

——这是一个相当大的群，共轭作用
$$
\Ad(\GL_n) := \{X \mapsto A X A^{-1} : A \in \GL_n\} \subseteq \Aut(\gl_n)
$$
只是其中的一小部分．

:::{#prp-gln-diff-ad}

$\GL_n$, $\SL_n$, $\PSL_n$ 在 $\gl_n$ 上的共轭作用导致相同的轨道．

这里 $\SL_n := \{g \in \GL_n : \det g = 1\}$ 是 $\GL_n$ 的子群，$\PSL_n := \SL_n / Z(\SL_n)$ 是 $\SL_n$ 的商群，$Z(\SL_n)$ 是 $\SL_n$ 的中心．
:::

这是因为任意 $A \in \GL_n$ 的共轭作用 $X \mapsto A X A^{-1}$ 都等价于 $(\det A)^{1/n} \in \SL_n$ 的共轭作用，而中心在共轭作用下不起作用．

:::{.remark}

可以看到这开始和基域的选择有关．考虑群正合列：
$$
1 \longrightarrow \SL_n \longrightarrow \GL_n \xrightarrow{\det} \mathbb C^\times \longrightarrow 1
$$
右分裂同态 $c \mapsto (\det c)^{1/n}$ 使得其右侧分裂，从而 $\GL_n = \SL_n \rtimes Z(\GL_n) \cong \SL_n \rtimes \mathbb C^\times$．但这是复数域能够开根的结果．

TODO: 这也许和所谓的 split reductive group 有关．
:::

因此在 $\gl_n$ 上，$\GL_n$, $\SL_n$, $\PSL_n$ 的选择是等价的．这三个群作用都是直接由共轭作用诱导的．可以认为 $\PSL_n \subseteq \Aut(\gl_n)$．