---
title: Artin--Noether 乱炖
subtitle: On the Equivalence of Artinian and Zero-Dimensional Noetherian Rings
author: sun123zxy
date: 2025/08/01
date-modified: 2025/12/07
lang: zh
bibliography: index.bib

categories:
  - math 
  - algebra
collection:
  - short

format:
  html: default
---

本文所指环均为交换幺环．我们重新编排一下 [@m_f_atiyah_introduction_1969, {chapter 8}] 的顺序，开发以下著名的 Artin 环等价刻画的证明：

:::{#thm-artin-noether}

## Akizuki--Hopkins--Levitzki

环 $A$ 是 Artin 环当且仅当它是（Krull 维度）零维的 Noether 环．
:::

回忆如果环 $A$ 作为 $A$-模具有有限长度的合成列，那么它既是 Artin 环，也是 Noether 环^[这甚至是充要条件，详见 [@altman_term_2013, {corollary 19.5}]]．故只需分析环拥有有限长度合成列的条件．

## 局部

让我们先解决局部的情况．设 $A$ 是具有唯一极大理想 $\mathfrak m$ 的局部环．我们有一条天然的理想降链
$$
A \supseteq \mathfrak m \supseteq \mathfrak m^2 \supseteq \dots
$$
这条降链可能出现以下三种情况：

- 降链不稳定，即 $m^i \supsetneq m^{i+1}$．

  如形式幂级数环 $K[[x]]$．它是 Noether 环，不是 Artin 环，降链为：
  $$
  K[[x]] \supsetneq (x) \supsetneq (x^2) \supsetneq \dots 
  $$ 

  如多项式环 $K[x]$ 在素理想 $(x)$ 处的局部化 $K[x]_{(x)}$．它是 Noether 环，不是 Artin 环．

  $$
    K[x]_{(x)} \supsetneq (x) \supsetneq (x^2) \supsetneq \dots
  $$

- 降链稳定，即存在 $k$ 使得 $\mathfrak m^k = \mathfrak m^{k+1} = \cdots$，但稳定的 $\mathfrak m^k$ 不是零理想．

  例子有点难找，我们暂且不表．

- 降链稳定且 $\mathfrak m^k = (0)$，即 $\mathfrak m$ 是幂零理想．

  如 $K[x] / (x^3)$．它是 Noether 环，也是 Artin 环．

:::{.remark}

事实上，如果环是 Noetherian 的，第二种情况不可能出现——这用 Nakayama 引理分析降链尾部稳定部分立得；而第一种情况的降链也必然趋于零理想——这是局部环上的 Krull 交定理保证的．
:::

根据这些例子，看起来我们有必要**加入 $\mathfrak m$ 是幂零理想的条件**．设其幂零指数为 $k$．此时有理想降链
$$
A \supseteq \mathfrak m \supseteq \mathfrak m^2 \supseteq \dots \supseteq \mathfrak m^k = (0)
$$
让我们试着把它补全成一个合成列．$A / \mathfrak m$ 是域；$\mathfrak m^i / \mathfrak m^{i+1}$ 是 $A / \mathfrak m$-模，也就是线性空间．嗯，于是想让它长度有限，只需要求每个 $\mathfrak m^i / \mathfrak m^{i+1}$ 的维数有限即可．而在线性空间里，Artinian 和 Noetherian 是等价的，而这两个性质都是子模、商模遗传的——故 **$\mathfrak m$ 幂零时，局部环 $A$ 的 Artinian 性质和 Noetherian 性质等价**．

:::{.remark}

这个思路其实是 [@m_f_atiyah_introduction_1969, {corollary 6.11}] 的特例．
:::

那什么时候 $\mathfrak m$ 幂零呢？

- $\mathfrak m$ 幂零蕴含着 Krull 维度为零．设 $\mathfrak m^k = (0)$，两端同时取 radical 就有 $\mathfrak m = \sqrt{(0)}$，后者是 nilradical，是全体素理想的交．那随便取一素理想 $\mathfrak p$ 就有 $\mathfrak m = \sqrt{(0)} \subseteq \mathfrak p$，再用 $\mathfrak m$ 的极大性就有 $\mathfrak m = \mathfrak p$，也就是说 $\mathfrak m$ 也是局部环 $A$ 唯一的素理想．因此 $A$ 的 Krull 维度为零．

- 当 $A$ 是 Noether 环时，Krull 维度为零可以推出 $\mathfrak m$ 幂零．Krull 维数为零意味着 $\mathfrak m$ 就是 nilradical，后者在 Noether 环中是幂零理想：

  :::{#prp-noether-nilradical-nilpotent}

  Noether 环中 nilradical 是幂零理想．
  :::

  :::{.proof}
  
  容易利用生成元有限和鸽巢原理得证．
  :::

  :::{.remark}

  一个常见变体是，Noether 环中任意理想的 radical 的自乘若干次幂一定落入该理想中．
  :::

- $A$ 是 Artin 环蕴含了 $A$ 是零维的——我们直接给出一般情况的证明：

  :::{#prp-artin-zero-dim}

  ## [@m_f_atiyah_introduction_1969, {proposition 8.1}]

  Artin 环中的素理想都是极大理想．
  :::

  :::{.proof}

  设 $A$ 是 Artin 环，$\mathfrak p$ 是 $A$ 的素理想．注意 Artinian 性质在商模上保持，我们证明 Artin 整环 $A / \mathfrak p$ 是域．任取非零元 $x \in A / \mathfrak p$，考察理想降链
  $$
  (x) \supseteq (x^2) \supseteq (x^3) \supseteq \dots
  $$
  由于 $A / \mathfrak p$ 是 Artin 环，降链稳定，则存在 $k$ 使得 $(x^k) = (x^{k+1})$，于是存在可逆元 $c \in A / \mathfrak p$ 使得 $x^{k+1} = c x^k$．用整环消去律立得 $x = c$，即 $x$ 可逆．因此 $A / \mathfrak p$ 是域，$\mathfrak p$ 是极大理想．
  :::

- $A$ 是 Artin 环蕴含了 $\mathfrak m$ 幂零．根据上一条结果，$\mathfrak m$ 在 Artin 环中其实就是 nilradical，我们可以使用如下不太平凡的结果：

  :::{#prp-artin-nilradical-nilpotent}

  ## [@m_f_atiyah_introduction_1969, {proposition 8.4}]

  Artin 环的 nilradical（或 Jacobson radical）$\mathfrak N$ 是幂零理想．
  :::

  :::{.proof}
  
  Artinian 性质使得 $\mathfrak N$ 幂次组成的降链稳定，不妨设最后稳定在 $\mathfrak L$，于是 $\mathfrak N \mathfrak L = \mathfrak L$．假如 $\mathfrak L$ 非零，取一极小（Artin 降链条件保证能取到）非零子理想 $\mathfrak a \subset \mathfrak L$ 满足 $\mathfrak a \mathfrak L \neq (0)$，则 $\mathfrak a$ 必为一主理想 $(a)$．但理想 $a \mathfrak L$ 也满足 $(a \mathfrak L) \mathfrak L = a(\mathfrak L \mathfrak L) = a \mathfrak L \neq (0)$，故由极小性，$(a) = a \mathfrak L$．于是存在 $l \in \mathfrak L \subset \mathfrak N$ 使得 $a = al$．但 $l$ 是幂零元，故 $a = al = al^2 = \dots = 0$，矛盾．
  :::

  :::{.remark}

  这个证明比较难想，主要是利用了 $\mathfrak L$ 是幂等理想的性质．事实上可以使用 Nakayama 引理证明：任何有限生成的幂等理想都是某一幂等元素生成的主理想．这个幂等元素就类似于上述证明中我们费力构造出的 $a$．
  :::

综上，我们获得了局部环内 Artin 环等价于零维 Noether 环的证明，或者说：

:::{#thm-artin-noether-local-ex}

以下条件对 Noether 局部环 $(A, \mathfrak m)$ 等价：

- $A$ 作为 $A$-模具有有限合成列；
- $A$ 是 Artin 环；
- $A$ 的极大理想 $\mathfrak m$ 幂零；
- $A$ 的 Krull 维度为零．
:::

## 全局

现在我们不再假设 $A$ 是局部环．发挥类似 $\mathfrak m$ 效果的理想变成了 Jacobson radical $\mathfrak J := \bigcap_i \mathfrak m_i$．我们仍然可以考虑 $\mathfrak J$ 的各幂次形成的降链
$$
A \supseteq \mathfrak J \supseteq \mathfrak J^2 \supseteq \dots
$$
并讨论它的稳定性——类似的，我们**要求 $\mathfrak J$ 是幂零理想**．刚刚已经做过局部环的情况，要是全局的情况也能约化到局部就好了．Jacobson radical 作为极大理想的交很自然的让我们想到中国剩余定理，于是我们再**加入一个条件：$A$ 的极大理想数量有限**，此时
$$
\begin{aligned}
A
&\cong A / \mathfrak J^k & \text{by nilpotency of } \mathfrak J \\
&\cong A / \left(\bigcap_i \mathfrak m_i \right)^k \\
&\cong A / \left(\prod_i \mathfrak m_i \right)^k & \text{by finite maximal ideals}\\
&\cong A / \prod_i \mathfrak m_i^k \\
&\cong \prod_i A / \mathfrak m_i^k & \text{by Chinese Remainder Theorem}
\end{aligned}
$$

:::{.remark}

最后一步需要用到 $\mathfrak m_i^k$ 两两 comaximal 的性质．事实上，comaximal 的性质关于取 radical 保持：理想 $\mathfrak a, \mathfrak b$ 满足 $\mathfrak a + \mathfrak b = A$ 当且仅当 $\sqrt{\mathfrak a} + \sqrt{\mathfrak b} = A$：

$$
\begin{aligned}
\mathfrak a + \mathfrak b = A
&\iff \sqrt{\mathfrak a + \mathfrak b} = A \\
&\iff \sqrt{\sqrt{\mathfrak a} + \sqrt{\mathfrak b}} = A \\
&\iff \sqrt{\mathfrak a} + \sqrt{\mathfrak b} = A
\end{aligned}
$$

此外，可见对非局部环的情况，任何极大理想 $\mathfrak m$ 都不可能幂零：否则 $\mathfrak m \subseteq \mathfrak R \subset \mathfrak J \subseteq \mathfrak m$，局部环．
:::

注意 $A / \mathfrak m_i^k \cong A_{\mathfrak m_i} / \mathfrak m_i^k A_{\mathfrak m_i}$ 都是极大理想为 $\mathfrak m_i$ 的局部环．于是 $A$ 被拆分为有限个局部环的直积．Artinian、Noetherian、零维的性质因此在 $A$ 及其局部环间双向传播．这样
$$
\begin{aligned}
A \text{ is Artinian}
&\iff A / \mathfrak m_i^k \text{ is Artinian for each } i \\
&\iff A / \mathfrak m_i^k \text{ is Noetherian and of Krull dimension $0$ for each } i \\
&\iff A \text{ is Noetherian and of Krull dimension $0$}
\end{aligned}
$$

总结一下，**在 Jacobson radical $\mathfrak J$ 幂零且极大理想数量有限的环中，Artinian 等价于零维 Noetherian**．

:::{.remark}

上述将 Artin 环分解为若干 Artin 局部环的分解被称为 Artin 环的结构定理．该分解事实上还具有唯一性，请参考 [@m_f_atiyah_introduction_1969, {theorem 8.7}]．
:::

现在只需研究这额外增加的两个条件的性质．和我们在局部环中的讨论一致，Jacobson radical $\mathfrak J$ 的幂零性可由：

- Artin 环：[@prp-artin-nilradical-nilpotent]

- 零维 Noether 环：$\mathfrak J = \mathfrak N$ 及 [@prp-noether-nilradical-nilpotent]

获得．而关于极大理想数量有限，首先我们指出这条件的必要性——考虑多项式环 $K[x]$，它是 Jacobson 根为零理想的 Noetherian 环，但不是 Artin 环．其次，它可以由以下两种情况获得：

- Artin 环：

  :::{#prp-artin-finite-specmax}

  ## [@m_f_atiyah_introduction_1969, {proposition 8.3}]

  Artin 环的极大理想数量有限．
  :::

  :::{.proof}
  
  考虑所有极大理想的有限交组成的理想族，通过 Artin 环的降链稳定性取出其中的一个极小理想，设它是 $\mathfrak a := \mathfrak m_1 \cap \dots \cap \mathfrak m_k$．假若极大理想无限，则取一不同于 $\mathfrak m_1, \dots, \mathfrak m_k$ 的极大理想 $\mathfrak m_{k+1}$，就有 $a \cap m_{k+1} \subsetneq a$，与 $\mathfrak a$ 的极小性矛盾．
  :::

- 零维 Noether 环：

  Noether 环的任意理想都有准素分解 [@m_f_atiyah_introduction_1969, {theorem 7.13}]，特别地，考虑零理想的准素分解，取 radical 得到 nilradical $\mathfrak R$ 的素理想分解 $\mathfrak R = \bigcap_i \mathfrak p_i$．
  
  我们指出，其它 $A$ 的素理想都至少包含某个 $\mathfrak p_i$：对任意素理想 $\mathfrak p$，$\prod_i \mathfrak p_i \subseteq \bigcap_i \mathfrak p_i = \mathfrak R \subseteq \mathfrak p$，再用素理想等价刻画 [@m_f_atiyah_introduction_1969, {theorem 1.11 (ii)}] 就存在特定 $i$ 使得 $\mathfrak p_i \subseteq \mathfrak p$．

  现在使用 $A$ 的零维性，立得 $\mathfrak p_i$ 组成 $A$ 的所有极大理想，故 $A$ 的极大理想数量有限．

至此我们完成了 Artin 环等价于零维 Noether 环的证明．既然已经知道 Artinian 强于 Noetherian，让我们把定理改写成更加令人印象深刻的形式：

:::{#thm-artin-noether-ex}

以下条件对 Noether 环 $A$ 等价：

- $A$ 作为 $A$-模具有有限合成列；
- $A$ 是 Artin 环；
- $A$ 的 Jacobson radical $\mathfrak J$ 是幂零理想，且 $A$ 的极大理想数量有限；
- $A$ 的 Krull 维度为零．
:::

TODO：[@altman_term_2013] 提供了证明的另一条路径．

## 后记

除环的 Krull 维数外，刻画局部 Noether 环的另一重要参数是 $\dim_k (\mathfrak m / \mathfrak m^2)$：$\mathfrak m / \mathfrak m^2$ 作为 $k := A / \mathfrak m$-线性空间的维数．由 Nakayama 引理 [@m_f_atiyah_introduction_1969, {proposition 2.8}]，$\dim_k (\mathfrak m / \mathfrak m^2)$ 恰为 $\mathfrak m$ 的最小生成元个数．

$\dim_k \mathfrak m / \mathfrak m^2 = 0$ 时，$\mathfrak m = 0$，故 $A$ 是域．现在来看第二简单的情况：$\dim_k \mathfrak m / \mathfrak m^2 = 1$．使用 Krull 交定理可以证明，如下条件对局部 Noether 环 $A$ 等价：

- $A$ 是 PIR，即所有理想都是主理想．

- $A$ 的极大理想 $\mathfrak m$ 是主理想．

- $\dim_{k} \mathfrak m / \mathfrak m^2 = 1$．

- 每个非零理想都是 $\mathfrak m$ 的某个幂次．

考虑到 [@thm-artin-noether-local-ex]，当 $\mathfrak m$ 不稳定时，任意非零理想都是 $\mathfrak m$ 的某个幂次，故任意非零素理想都是 $\mathfrak m$，即 $A$ 至多一维．当 $\mathfrak m$ 稳定（即幂零），我们得到 Artin 的零维局部 PIR．否则 $A$ 是维度为 $1$ 的整环，此时这种环被称为离散赋值环（Discrete Valuation Ring, DVR），典型的例子有

- $k[x]_{(x)}$：一元多项式环在素理想 $(x)$ 处的局部化是 DVR．
- $k[[x]]$：一元多项式环在 $(x)$ 处的完备化是 DVR．
- $k[x,y]_{(x)}$：整闭的 Noether 整环在高度为 $1$ 的素理想处的局部化是 DVR．人话：不可约代数超曲面（余维为 $1$）附近的函数芽是 DVR．

一般地，满足 Krull 维数等于 $\dim_k (\mathfrak m / \mathfrak m^2)$ 的局部 Noether 环被称为是正则的（[@m_f_atiyah_introduction_1969, {theorem 11.22}]；前者在一般情况下小于等于后者）．DVR 恰是一维正则局部环．

来看整体．之前看到，零维 Noether 环是若干局部 Artin 环的直积，故零维 Noether 环是 PIR 当且仅当每个局部环都是 PIR．现在来看一维 Noether 环，我们希望将局部正则性翻译到整体上．事实是：

- 对一维局部诺特环，DVR 等价于整闭性．[@m_f_atiyah_introduction_1969, {proposition 9.2}]
- 整闭是局部性质．[@m_f_atiyah_introduction_1969, {proposition 5.13}]

故一维 Noether 环整闭当且仅当它的每个局部化是 DVR．这种环被称为 Dedekind 整环．典型的例子有:

- 代数数域的整数环，即 $\mathbb Z$ 在 $\mathbb Q$ 的某一有限域扩张中的整闭包．[@m_f_atiyah_introduction_1969, {theorem 9.5}]
- non-singular 的不可约代数曲线（一维代数簇）的函数环．注意曲线的 non-singularity 恰为每点局部化的正则性要求．

Dedekind 整环有很多数论上的好性质，例如

- 所有准素理想都是某个素理想的幂次 [@m_f_atiyah_introduction_1969, {theorem 9.3}]
- 所有理想都有唯一素理想乘积分解 [@m_f_atiyah_introduction_1969, {theorem 9.4}]

等．这里就不展开了．

## Acknowledgement {.appendix}

感谢 Luna 在本文写作过程中提供的帮助和建议．