---
title: 有限群表示论：Peter--Weyl 定理
author: sun123zxy
date: 2026-03-14
last-modified: 2026-04-20
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
collections:
  - group-rep-tour

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\GL}{\operatorname{GL}}
\newcommand{\im}{\operatorname{im}}
\newcommand{\id}{\operatorname{id}}
\newcommand{\Tr}{\operatorname{Tr}}
\newcommand{\End}{\operatorname{End}}

## 从左模到双模

有限群表示论的一个经典结果是正则表示的分解：
$$
\mathbb C[G] \cong \bigoplus_i V_i^{\oplus \dim V_i}
$$
这里 $\mathbb C[G]$ 是群 $G$ 的群代数，$V_i$ 是 $G$ 的全体不可约表示．这只是个左 $\mathbb C[G]$-模的分解：$\mathbb C[G]$ 被分解成了其单左理想的直和．但是 $\mathbb C[G]$ 是个环，完整来说我们应该研究其作为 $\mathbb C$-代数的分解．Peter--Weyl / Wedderburn--Artin 定理给出了它的分解：
$$
\mathbb C[G] \cong \bigoplus_i \End_{\mathbb C}(V_i) \cong \bigoplus_i V_i \otimes_{\mathbb C} V_i^*
$$
可见其结构确实变得更加丰富．稍做辨析：

### 双模观点

- 这里每份投影 $\pi_i: \mathbb C[G] \to \End_{\mathbb C}(V_i)$ 都是表示 $\rho_{V_i} : G \to \GL(V_i)$ 直接线性扩张得到——因此 Peter--Weyl 定理实质上是在说，$\mathbb C[G]$ 在其每个不可约表示上的作用完全决定了 $\mathbb C[G]$ 的代数结构．

- 容易验证每个 $\pi_i$ 都是 $(\mathbb C[G], \mathbb C[G])$-代数同态——保加法，保乘法，保数乘，保左、右 $G$-作用．这里的分解是在此意义下的同构．

- $V_i$ 是 $G$ 的不可约表示，配备左 $\mathbb C[G]$-模结构．

- $V_i^*$ 是 $V_i$ 的对偶空间，配备右 $\mathbb C[G]$-模结构 $(f \cdot g)(v) := f(g \cdot v)$．

:::{.remark}

在经典的有限群表示论中，那时我们希望 $V_i^*$ 是左 $\mathbb C[G]$-模，所以当时配备的是 $(f \cdot g)(v) := f(g^{-1} \cdot v)$．这里就是想要右模结构，所以不用取逆生造了．
:::

- $V_i \otimes_{\mathbb C} V_i^*$ 通过 $(\mathbb C[G], \mathbb C)$-双模和 $(\mathbb C, \mathbb C[G])$-双模的张量积获得一个 $(\mathbb C[G],\mathbb C[G])$-双模结构：
  $$
  g \cdot (v \otimes f) \cdot h := (g \cdot v) \otimes (f \cdot h)
  $$
  其内部乘法是缩并运算．这使得其成为一个 $(\mathbb C[G], \mathbb C[G])$-代数．

- 对左 $\mathbb C[G]$-模 $U$, $W$，为了使自然同构 $W \otimes_{\mathbb C} U^* \cong \Hom_{\mathbb C}(U,W)$ 成立，为 $\Hom_{\mathbb C}(U,W)$ 配备 $(\mathbb C[G],\mathbb C[G])$-双模结构
  $$
  (g \cdot \varphi \cdot h)(u) := g \cdot \varphi(h \cdot u)
  $$
  特别地，在 $\End_{\mathbb C}(V_i) = \Hom_{\mathbb C}(V_i, V_i)$ 定义内部乘法是函数复合，则 $\End_{\mathbb C}(V_i)$ 也获得 $(\mathbb C[G], \mathbb C[G])$-代数结构．

:::{.remark}

平时仅考虑左模结构时，为使记号对齐，通常喜欢写 $\Hom_{\mathbb C}(V,W) \cong V^* \otimes_{\mathbb C} W$——这无伤大雅，反正 $V^*$ 强行通过 $g^{-1}$ 获得了左 $\mathbb C[G]$-模结构．但对双模的情况，左 $\mathbb C[G]$-作用是由 $W$ 负责，右 $\mathbb C[G]$-作用是由 $V^*$ 负责，我们就最好不要交换它们了．
:::

- 不会因为仅将此分解视为环的分解受到任何处分——通过表示诱导的映射 $\pi_i : \mathbb C[G] \to \End_{\mathbb C}(V_i)$ 足以将 $\End_{\mathbb C}(V_i)$ 上的乘法结构拉回得到其 $(\mathbb C[G], \mathbb C[G])$-双模结构．

- 反过来，仅考虑 $(\mathbb C[G], \mathbb C[G])$-双模结构也没有问题：将会证明 $\pi_i$ 是满射，即每个 $\End_{\mathbb C}(V_i)$ 都是可以写作某一 $\mathbb C[G]$-左作用．

### 左模观点

考虑到群代数有对极映射 $g \mapsto g^{-1}$，这使得可以将任何 $V$ 上的 $(G,H)$-双边表示结构强行翻成 $G \times H$-群表示结构研究：
$$
(g,h) \cdot v := g \cdot v \cdot h^{-1}
$$
或在模的语言下：任何 $(\mathbb C[G], \mathbb C[H])$ 双模结构可被强行翻成 $(\mathbb C[G] \otimes_{\mathbb C} \mathbb C[H])$ 结构．这样的好处是可以直接套用之前对群表示的语言来表达双模．例如，在此风格表述下的 Peter--Weyl 定理
$$
\mathbb C[G] \cong \End_{\mathbb C}(V_i) \cong \bigoplus_i V_i \otimes_{\mathbb C} V_i^*
$$
应当理解为 $\mathbb C[G]$ 作为 $G \times G$-群表示的分解，其中

- $\otimes_{\mathbb C}$ 是 $G \times G$-群表示的张量积
- $\End_{\mathbb C}(V_i)$ 是 $G \times G$-表示，其上第一个 $G$-自然作用在值域 $V_i$，第二个 $G$-作用取逆作用在定义域 $V_i$
- $V_i$ 是 $G \times G$-表示，其上第一个 $G$-作用自然，第二个 $G$-作用平凡
- $V_i^*$ 是 $G \times G$-表示，其上第一个 $G$-作用平凡，第二个 $G$-作用取逆作用在定义域 $V_i$

:::{.remark}

这似乎只是把双边代数表示翻译到 Hopf 代数表示的抽象废话，但在如 Schur--Weyl 对偶中，会看到这种翻译能有效简化表述．
:::

## 证明

我们提供几条依赖不同工具的证明路线，读者可按前置情况任选．

- 有关有限群表示论的基础内容可参见[有限群表示论速通](/posts/20260312-group-rep-speedrun/)．

先证 $\pi$ 是单射：

- 这里的证明依赖有限群表示论的 Maschke 定理（半单性）．

  若一 $\mathbb C[G]$ 元素在每个不可约表示上作用均为 $0$，由半单性，$\mathbb C[G]$ 自己分解成若干不可约表示的直和，所以该元素在 $\mathbb C[G]$ 上作用也为 $0$．$\mathbb C[G]$ 在自己上作用当然是忠实的，所以该元素只能是 $0$．

则只需证 $\pi$ 是满射．这里有多种可供选择的路线：

- 依赖有限群表示论的维数平方和公式 $\sum_i (\dim V_i)^2 = |G|$：[@fulton_representation_2004, {Proposition 3.29}]
  
  $\dim \End_{\mathbb C}(V_i) = (\dim V_i)^2$，$\dim \mathbb C[G] = |G|$ 维数逼迫单射 $\pi$ 也是满射．

- 依赖 [矩阵代数的 Burnside 定理](/posts/20240121-burnside/)，该定理的证明可以仅依赖初等线性代数：

  - 复数域上矩阵代数的含幺子结合代数如果不可约，则一定是整个．

  则考察含幺结合代数 $\mathbb C[G]$ 在 $\End_{\mathbb C}(V_i)$ 上的像，确为 $\End_{\mathbb C}(V_i)$ 的不可约含幺子结合代数．故根据 Burnside 定理，$\mathbb C[G]$ 在每个 $\End_{\mathbb C}(V_i)$ 上的像都必须是全体．

:::{.remark}

依赖 Burnside 定理的满射性证明甚至不需要 $G$ 是有限群，
:::

我们还可以显式构造 $\pi$ 的逆 $\iota$ 来获得一个构造性的证明：

- 先来构造 $(\mathbb C[G], \mathbb C[G])$ 双模同态 $\iota_i: \End_{\mathbb C}(V_i) \to \mathbb C[G]$：
  $$
  \varphi \mapsto \frac{\dim V_i}{|G|} \sum_{g \in G} \Tr(\varphi \circ \rho_{V_i}(g^{-1})) g
  $$
  等价地，$V_i \otimes_{\mathbb C} V_i^* \to \mathbb C[G]$ 的版本是
  $$
  v \otimes f \mapsto \frac{\dim V_i}{|G|} \sum_{g \in G} f(g^{-1} \cdot v) g
  $$
  固定 $V_i$ 一组基 $(e_i^k)$ 并生成 $V_i^*$ 上的对偶基 $(f_i^j)$，则此映射有矩阵风格的解读：将 $g \in G$ 映射到 $\rho_{V_i}(g^{-1})$ 的第 $j$ 行第 $k$ 列元素取出得到一 $L^2(G)$ 内函数
  $$
  \rho_{V_i}^{j, k}(g) := f_i^j(\rho_{V_i}(g^{-1}) \cdot e_i^k)
  $$
  再等价地看作 $\mathbb C[G]$ 的元素，最后适当归一化．

- 我们可以证明 $\iota_i$ 是单射，且每个 $\iota_i$ 的像之间两两正交．

  $L^2(G)$ 上有函数空间的标准内积．考虑 $e_{i_2}^{k_2} \otimes f_{i_1}^{j_1} \in V_{i_2} \otimes_{\mathbb C} V_{i_1}^* \cong \Hom_{\mathbb C}(V_{i_1}, V_{i_2})$，对其平均化得
  $$
  \frac 1 {|G|} \sum_{g \in G} \rho_{V_{i_2}}(g) \circ \left( e_{i_2}^{k_2} \otimes f_{i_1}^{j_1} \right) \circ \rho_{V_{i_1}}(g^{-1}) \in \Hom_G(V_{i_1}, V_{i_2})
  $$
  再对此 $\Hom_G(V_{i_1}, V_{i_2})$ 中映射取第 $j_2$ 行第 $k_1$ 列元素得
  $$
  \begin{aligned}
  &\phantom{=} \frac 1 {|G|} \sum_{g \in G} f_{i_2}^{j_2} \left( \rho_{V_{i_2}}(g) \circ \left( e_{i_2}^{k_2} \otimes f_{i_1}^{j_1} \right) \circ \rho_{V_{i_1}}(g^{-1}) \cdot e_{i_1}^{k_1} \right) \\
  &= \frac 1 {|G|} \sum_{g \in G} \rho_{V_{i_2}}^{j_2, k_2}(g) \cdot \rho_{V_{i_1}}^{j_1, k_1}(g^{-1}) \\
  &= \langle \rho_{V_{i_2}}^{j_2, k_2}, \rho_{V_{i_1}}^{j_1, k_1} \rangle
  \end{aligned}
  $$
  回忆 Schur 引理对 $\Hom_G (V_{i_1}, V_{i_2})$ 的刻画，这恰是在说此内积非零当且仅当 $i_1 = i_2$ 且 $j_1 = j_2$ 且 $k_1 = k_2$．因此 $\rho_{V_{i}}^{j, k}$ 两两正交．当 $i=i_1=i_2$, $j=j_1=j_2=k=k_1=k_2$ 时，$e_i^j \otimes f_i^j \in \End_{\mathbb C}(V_i)$ 的迹为 $1$，而平均化不改变迹并将其变为 $V_i$ 上的数乘，因此 $\langle \rho_{V_i}^{j, k}, \rho_{V_i}^{j, k} \rangle = 1 / \dim V_i$．因此 $\iota_i$ 是单射，且每个 $\iota_i$ 的像之间两两正交．

- 最后验证 $\iota_i \circ \pi_i = \id_{\End_{\mathbb C}(V_i)}$ 结束讨论．【TODO】

## 推论

来看上述分解导致的事实．

### 维数平方和

首先，如果你选择的证明路线没有循环论证之嫌，可以通过维数再次看出维数平方和公式
$$
|G| = \sum_i (\dim V_i)^2
$$

### 共轭类计数

其次，对这分解取中心：
$$
Z(\mathbb C[G]) \cong \bigoplus_i Z(\End_{\mathbb C}(V_i))
$$

- $Z(\End_{\mathbb C}(V_i))$ 是 $\End_{\mathbb C}(V_i)$ 的中心，而（根据满射性）所有 $\End_{\mathbb C}(V_i)$ 都可实现为 $V_i$ 上的 $G$-左作用，因此这中心恰为 $\End_{\mathbb C[G]}(V_i)$．回忆 Schur 引理，$V_i$ 是不可约表示，所以 $Z(\End_{\mathbb C}(V_i)) = \End_{\mathbb C[G]}(V_i) = \mathbb C \id_{V_i}$，维数为 $1$．

- $Z(\mathbb C[G])$ 是什么？

  设 $\sum_{h \in G} \chi(h) h \in Z(\mathbb C[G])$，这即是要求对任意 $g \in G$，有
  $$
  \sum_{h \in G} \chi(h) h = g \left( \sum_{h \in G} \chi(h) h \right) g^{-1} = \sum_{h \in G} \chi(h) g h g^{-1} = \sum_{h \in G} \chi(g^{-1} h g) h
  $$
  即 $\chi(g^{-1} h g) = \chi(h)$——在共轭类上取常值——$Z(\mathbb C[G])$ 就是类函数全体！其维数等于 $G$ 的共轭类的数量．

两条连起来看：$G$ 的共轭类的数量等于 $G$ 的不可约表示的数量．

:::{.remark}

## 左模观点

回忆 $\mathbb C[G]$ 也作为 $G \times G$-群表示分解．让我们使用对角映射 $g \mapsto (g,g)$ 将 Peter--Weyl 分解
$$
\mathbb C[G] \cong \bigoplus_i \End_{\mathbb C}(V_i)
$$
看成 $G$-表示的分解，于是 $\mathbb C[G]$ 上的 $G$-作用是共轭 $g \cdot x := g x g^{-1}$，$\End_{\mathbb C}(V_i)$ 上的 $G$-作用也是共轭 $(g \cdot \varphi) (v) := g \cdot \varphi (g^{-1} \cdot v)$．两边同时取 $G$-不变子空间，得到
$$
\left(\mathbb C[G] \right)^G \cong \bigoplus_i \End_{G}(V_i)
$$
左边作为线性空间同构于 $G$ 的类函数空间，右边又使用 Schur 引理，我们再次得到共轭类计数的结论．
:::

### 交换群、循环群、DFT

如果 $G$ 是交换群，则每个不可约表示 $V_i$ 都是 $1$ 维．因此在 $\mathbb C$-代数同构意义下有
$$
\mathbb C[G] \cong \bigoplus_i \End_{\mathbb C}(V_i) \cong \mathbb C^{\oplus |G|} \cong L^2(G)
$$
来考察这个同构具体是什么．每个 $\pi_i : \mathbb C[G] \to \End_{\mathbb C}(V_i) \cong \mathbb C$ 即为 $V_i$ 对应的特征标 $\chi_i : G \to \mathbb C$ 线性张成的结果．

考虑到有限交换群基本定理，不妨来考虑最简单的循环群 $G = \mathbb Z / n \mathbb Z$．其第 $k$ 个不可约表示，或特征标由 $1 \mapsto \zeta_n^k$ 给出，这里 $\zeta_n = e^{2\pi i / n}$ 是 $n$-次单位根．则上述同构是在说 DFT 矩阵 $(\zeta_n^{jk})_{0 \leq j,k < n}$ 可逆——当然可逆，而且是正交的．这是所谓的离散 Fourier 变换． 

### 直和分解的典范投影

对任意 $G$-表示 $V$，大力自然同构
$$
\begin{aligned}
V &\cong \mathbb C[G] \otimes_{\mathbb C[G]} V \\
&\cong \bigoplus_i \End(V_i) \otimes_{\mathbb C[G]} V \\
&\cong \bigoplus_i V_i \otimes_{\mathbb C} V_i^* \otimes_{\mathbb C[G]} V \\
&\cong \bigoplus_i V_i \otimes_{\mathbb C} \Hom_G(V_i, V)
\end{aligned}
$$
注意 $\dim \Hom_G(V_i, V)$ 就是 $V_i$ 在 $V$ 中的重数，因此 $V_i \otimes_{\mathbb C} \Hom_G(V_i, V)$ 就是 $V$ 的各不可约成分，上述同构给出了 $V$ 的不可约成分的自然拆解——不同于证明半单性时对补空间的依赖，由于之前在 Peter--Weyl 的证明中给出了完全构造性的同构，这里的拆解也是完全构造性的，可以直接写出典范嵌入
$$
\begin{aligned}
\iota_i: V_i \otimes_{\mathbb C} \Hom_G(V_i, V) &\to V \\
v \otimes \varphi &\mapsto \varphi(v)
\end{aligned}
$$
和典范投影
$$
\begin{aligned}
\pi_i : V \to \bigoplus_i V_i \otimes_{\mathbb C} \Hom_G(V_i, V) \\
\iota_i \circ \pi_i = \frac{\dim V_i}{|G|} \sum_{g \in G} \overline{\chi_{V_i}(g)} \rho_V(g)
\end{aligned}
$$
