---
title: 幂零轨道的维数
subtitle: 幂零锥和其上的几何：以 $\mathfrak{gl}_n$ 为例
author: sun123zxy
date: 2026-04-03
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra

collections:
  - nilpcone

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\gl}{\mathfrak{gl}}
\newcommand{\SL}{\mathrm{SL}}
\newcommand{\PSL}{\mathrm{PSL}}
\renewcommand{\sl}{\mathfrak{sl}}
\newcommand{\ad}{\operatorname{ad}}
\newcommand{\Ad}{\operatorname{Ad}}
\newcommand{\Aut}{\operatorname{Aut}}
\newcommand{\Lie}{\operatorname{Lie}}
\newcommand{\diag}{\operatorname{diag}}

[上篇](/posts/20260321-geo-nilp-gln/)介绍了幂零锥和幂零轨道的基本概念．本篇我们关心 $\mathfrak{gl}_n$ 幂零锥和幂零轨道的维数情况．

## 定义维数

需要先澄清维数的定义．仿射空间的维数自然不必说，但定义仿射簇的维数则是另一个很长的故事．

- 最方便的定义是其 Zariski 拓扑不可约闭集升链的最大长度，这等价于其函数环素理想升链的最大长度，即 Krull 维数．如果考虑拓扑空间内某一点上不可约闭集的升链最大长度，或等价地考虑函数环在这点对应极大理想处局部化的 Krull 维数，则得到局部维数．易见全局维数是局部维数取上界得到．

- 当仿射簇不可约时，对应函数环是整环，于是有分式域，可以讨论其超越维数（transcendence degree）．Noether 正则化引理和关于整扩张下素理想升降链的 going-up / down 性质保证了超越维数和和上面定义的 Krull 维数相等．从局部化视角观察上述讨论，可知不可约代数簇的全局维数和局部维数相等．

:::{.remark}

可约仿射簇完全可以有不同维数的不可约分量，因此全局维数和局部维数不相等．
:::

- 维数还有 Hilbert–Poincaré 多项式、准素理想的最小生成元个数等定义，这里用不到，喜欢的同学可左转 [@AM1969]．

## 态射下的维数

维数有如下好性质 [@geck_introduction_2013, {Corollary 2.2.9}]：

:::{#prp-dim-fiber}

设 $\varphi : X \to Y$ 是仿射簇之间的态射，$\varphi(X)$ 在 $Y$ 中稠密．则存在 $Y$ 的非空开集 $U$ 使得 $U \subseteq \varphi(X)$，且对于任意 $y \in U$，$\dim \varphi^{-1}(y) = \dim X - \dim Y$．
:::

作为特例，考虑代数群 $G$ 作用在仿射簇 $X$ 上．固定元素 $x$，考虑态射 $G \to G \cdot x$，$g \mapsto g \cdot x$，此映射的所有纤维都是 $x^G$ 的陪集，故根据上述命题，
$$
\dim G = \dim x^G + \dim G \cdot x
$$
这里稳定核 $x^G := \{g \in G : g \cdot x = x \}$，$G \cdot x$ 是 $x$ 的轨道．这为我们提供了轨道维数的计算手段．

## 幂零轨道的维数

现在来数 $\mathfrak{gl}_n$ 幂零轨道的维数．考察 Jordan 型为 $\lambda \vdash n$ 的 Jordan 标准型 $J_\lambda$ 及其轨道 $\mathcal O_\lambda$，根据上述技巧
$$
\dim \GL_n = \dim Z_{\GL_n}(J_\lambda) + \dim \mathcal O_\lambda
$$
这里共轭作用的稳定核是与 $J_\lambda$ 交换的全体可逆矩阵 $Z_{\GL_n}(J_\lambda)$．注意共轭群 $\GL_n$ 是仿射空间 $\gl_n$ 的开子簇，因此共享维数 $n^2$，计算 $\dim \mathcal O_\lambda$ 规约为计算稳定核的维数．注意
$$
Z_{\GL_n}(J_\lambda) = Z_{\gl_n}(J_\lambda) \cap \GL_n
$$
这里 $Z_{\gl_n(J_\lambda)}$ 是 $J_\lambda$ 在 $\gl_n$ 里的中心化子，它不仅是闭子簇同时还是线性空间，即仿射空间，于是 $Z_{\GL_n}(J_\lambda)$ 作为仿射空间 $Z_{\gl_n(J_\lambda)}$ 的开集共享空间维数．

:::{.remark}

事实上 $Z_{\gl_n}(J_\lambda)$ 是 $Z_{\GL_n}(J_\lambda)$ 的李代数．
:::

问题规约为计算 $Z_{\gl_n}(J_\lambda)$ 的维数．设分拆 $\lambda$ 长度为 $l$，分块矩阵 $X = (X_{i,j})_{1 \leq i,j \leq l}$ 想要和分块对角矩阵 $J_\lambda := \diag(N_1, \dots, N_l)$ 交换，需要 $X_{i,j} N_{j} = N_{i} X_{i,j}$ 对任意 $1 \leq i, j \leq l$ 成立．注意这相当于是说 $X_{i,j}$ 上移一格和右移一格（溢出不管、缺失补零）没区别——这种好事什么时候发生？

这意味着左边界和下边界除左上和右下角块全零，并且左上至右下的各条对角线上元素相同．于是只有右上侧的 $\min(\lambda_i, \lambda_j)$ 条对角线具有自由选择元素的权利，因此整个 $X$ 的自由度，即
$$
\dim Z_{\gl_n}(J_\lambda) = \sum_{1 \leq i,j \leq l} \min(\lambda_i, \lambda_j)
$$
这个数不好看，大力组合重构：
$$
\begin{aligned}
\dim Z_{\gl_n}(J_\lambda) &= \sum_{1 \leq i,j \leq l} \min(\lambda_i, \lambda_j) \\
&= \sum_{i=1}^l \sum_{j=1}^l \sum_{k=1}^l \delta(k \leq \lambda_i) \delta(k \leq \lambda_j) \\ 
&= \sum_{k=1}^l \sum_{i=1}^l \delta(k \leq \lambda_i) \sum_{j=1}^l \delta(k \leq \lambda_j) \\
&= \sum_{k=1}^l (\lambda^T)_k^2
\end{aligned}
$$
这里 Kronecker $\delta$ 函数来表达 0/1 条件，$\lambda^T$ 是分拆 $\lambda$ 的转置，$(\lambda^T)_k = \sum_{i=1}^l \delta(k \leq \lambda_i)$．它真好看！因此
$$
\dim \mathcal O_\lambda = n^2 - \sum_{k=1}^l (\lambda^T)_k^2
$$
特别地：

- $\mathcal O_{(n)}$ 的维数是 $n^2 - n$，这也是整个幂零锥 $\mathcal N$ 的维数；
- $\mathcal O_{(1,1,\dots,1)}$ 的维数是 $0$．
