project:
  type: website
resources:
  - "assets/images/*"

metadata-files: 
  - _format.yml
  - _article.yml
  - _website.yml

filters:
  - at: pre-ast
    path: "_assets/callthm.lua"
  - "_assets/tikz.lua"