project:
  type: website
resources:
  - "assets/images/*"
website:
  site-url: "https://blog.sun123zxy.top"
  title: "sun123zxy's blog"
  favicon: "/assets/images/avatar.png"
  navbar:
    right:
      - text: About
        href: "/posts/about"
      - icon: rss
        href: "/index.xml"
  page-navigation: true
  page-footer: "sun123zxy's blog | Powered by Quarto"

# --- SunQuarTeX related metadata ---

metadata-files: 
  - _sunquartex.yml

# --- metadata specific to the blog ---

format:
  html:
    theme:
      dark: [darkly, "./_assets/listing-custom.scss", "./_assets/custom.scss", "./_assets/darkly-custom.scss"]
      light: [flatly, "./_assets/listing-custom.scss", "./_assets/custom.scss"] # see issue #3705
    
    toc: true
    toc-depth: 100
    number-depth: 3

    link-external-icon: true
    link-external-newwindow: true

    highlight-style:
      light: arrow
      dark: "./_assets/youmu-dark.theme"