project:
  type: website
resources:
  - "assets/images/*"
website:
  site-url: "https://blog.sun123zxy.top"
  title: "sun123zxy's blog"
  favicon: "/assets/images/avatar.png"
  navbar:
    right:
      - text: About
        href: "/posts/about"
      - icon: rss
        href: "/index.xml"
  page-navigation: true
  page-footer: "sun123zxy's blog | Powered by Quarto"

metadata-files: 
  - "./_format.yml"
  - "./_article.yml"