project:
  type: website
resources:
  - "assets/images/*"
website:
  site-url: "https://blog.sun123zxy.top"
  title: "sun123zxy's blog"
  favicon: "/assets/images/avatar.png"
  navbar:
    right:
      - text: About
        href: "/posts/about"
      - icon: github
        href: "https://github.com/sun123zxy/blog-quarto-code/"
      - icon: rss
        href: "/index.xml"
  page-navigation: true
  page-footer:
    left: "proudly powered by [Quarto](https://quarto.org/)"
    center: "sun123zxy's blog"
    right: "background modified from [Pixiv 50046630](https://www.pixiv.net/artworks/50046630)"

metadata-files: 
  - "./_format.yml"
  - "./_article.yml"

filters:
  - at: pre-ast
    path: "./_assets/callthm.lua"
  - "./_assets/tikz.lua"