---
title: 经典李代数中的幂零轨道：支配序
subtitle: 幂零锥和其上的几何：以 $\mathfrak{gl}_n$ 为例
author: sun123zxy
date: 2026-05-11
lang: zh
bibliography: index.bib
draft: true

categories:
  - math
  - algebra
  - lie

collections:
  - nilpcone

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\gl}{\mathfrak{gl}}
\newcommand{\SL}{\mathrm{SL}}
\renewcommand{\sl}{\mathfrak{sl}}
\newcommand{\ad}{\operatorname{ad}}
\newcommand{\Ad}{\operatorname{Ad}}
\newcommand{\rk}{\operatorname{rk}}
\newcommand{\SO}{\operatorname{SO}}
\newcommand{\so}{\mathfrak{so}}
\newcommand{\Sp}{\operatorname{Sp}}
\renewcommand{\sp}{\mathfrak{sp}}
\newcommand{\diag}{\operatorname{diag}}

本章讨论经典李代数中幂零轨道的支配序，证明幂零轨道的闭包关系和分拆上的支配序等价．

关于幂零轨道支配序的研究历史，[@jantzen_nilpotent_2004, {section 13.16}] 和 [@mcgovern_nilpotent_1993, {theorem 6.2.5}] 给出了一些评注．[@gerstenhaber_dominance_1961] 最早建立了经典李代数上幂零轨道闭包关系与分拆支配序的联系，[@hesselink_singularities_1976] 修补了 Gerstenhaber 证明中的部分漏洞．

我们选取的路线如下．对 A 型李代数，基于盖住关系间连续路径的构造和秩函数的下半连续性，给出支配序和分拆上的支配序的等价性证明；对于 B、C、D 型李代数，我们选取特定方便处理的非退化双线性型，从而仔细为其上的每一类盖住关系显式构建落在斜自伴李代数中的连续路径．我们发现可以通过一类组合图示为这些路径构造给出统一紧凑地描述．

本章默认在 $\mathbb C$ 上工作．经典李代数均认为是具体的 $\mathbb C^n$ 上的矩阵代数．A 型李代数 $\sl_n$ 的作用群默认为 $\SL_n$，B、C、D 型李代数的作用群默认为定义它们的非退化双线性型给出的正交群．考虑到已经完成了[经典李代数中幂零轨道的分类](/posts/20260426-classic-nilp-orbit/)，可以用分拆唯一标识幂零轨道．以后用 $\mathcal O_\lambda^{\sl}$ 的记号表示 Jordan 型为 $\lambda$ 的 $\sl$ 中元素在 $\SL$ 下的共轭轨道．考虑到正交群作用下的 B、C、D 型李代数 $\mathfrak g$ 的幂零轨道由 $\GL$ 作用下的轨道给出，我们用 $\mathcal O_\lambda^\mathfrak g = \mathcal O_\lambda^\sl \cap \mathfrak{g}$ 来标识 B、C、D 型在正交群作用下的幂零轨道．在上下文明确所在李代数的情况下，$O_\lambda$ 的上标可能会作省略．

## 支配序

设 $\mathfrak g$ 为一经典李代数，$\mathcal O_1$ 和 $\mathcal O_2$ 为其上的两个幂零轨道．在幂零轨道上定义偏序：如果 $\mathcal O_1 \subseteq \overline{\mathcal O_2}$，就定义 $\mathcal O_1 \trianglelefteq \mathcal O_2$，称为幂零轨道上的支配序关系（dominance order．亦作闭包序，closure order）．这里取闭包使用的拓扑是 $\mathfrak g$ 作为仿射空间的 Zariski 拓扑．

:::{.remark}

## Specialization Order

一般来讲，任何拓扑空间都可以通过取闭包包含的关系定义出一个预序（不保证反对称性的偏序关系），名曰 [specialization preorder](https://en.wikipedia.org/wiki/Specialization_preorder)．
:::

下面的结果将为我们证明轨道间的支配关系提供便利：只要 $\mathcal O_1$ 的任一元素落在 $\mathcal O_2$ 的闭包里，就有 $\mathcal O_1 \subseteq \overline{\mathcal O_2}$．

:::{#prp-orbit-force-dominance}

设 $\mathfrak g$ 是经典李代数，$G$ 是其轨道作用群，$\mathcal O_1$, $\mathcal O_2$ 为经典李代数 $\mathfrak g$ 上的共轭轨道．若 $\mathcal O_1 \cap \overline{\mathcal O_2} \neq \varnothing$，则 $\mathcal O_1 \subseteq \overline{\mathcal O_2}$．
:::

:::{.proof}

任取 $x \in \mathcal O_1 \cap \overline{\mathcal O_2}$．对任意 $y \in \mathcal O_1$，由轨道定义，存在 $g \in G$ 使得 $y = \Ad(g) x$．注意共轭作用 $\Ad(g)$ 是 $\mathfrak g$ 上的自同胚（Zariski 拓扑意义下），故与取闭包运算交换，故
$$
y = \Ad(g) x \in \Ad(g)(\overline{\mathcal O_2}) = \overline{\Ad(g)(\mathcal O_2)} = \overline{\mathcal O_2}
$$
因此 $\mathcal O_1 \subseteq \overline{\mathcal O_2}$．
:::

:::{.remark}

关于共轭作用是同胚的事实涉及到轨道作用群作为代数群的性质．不熟悉代数群的读者可以暂时先承认这一命题．
:::

## A 型李代数

来看 A 型李代数 $\sl_n$ 中幂零轨道的支配序．为此在分拆上定义同名的偏序关系：如果分拆 $\lambda$ 的每个部分和（前缀和）都大于等于 $\mu$ 的对应部分和，则定义 $\lambda \trianglerighteq \mu$．支配序对应的盖住关系（covering relation）可以用 Young 图刻画：考虑 $\lambda$ 对应 Young 图中那些比下一行至少多两个方块的行，让这一行最右侧方块“掉落”到下一行．例如，$(4,2)$ 盖住 $(3,3)$ 的图示如下：
$$
\begin{array}{cccc}
\bullet & \bullet & \bullet & \boxed\bullet \\
\bullet & \bullet
\end{array}
\quad\trianglerighteq\quad
\begin{array}{ccc}
\bullet & \bullet & \bullet \\
\bullet & \bullet & \boxed\bullet
\end{array}
$$

下面的命题说明两种序其实没有区别 [@mcgovern_nilpotent_1993, {theorem 6.2.5}]：

:::{#thm-sl-closure-dominance}

对 A 型李代数 $\sl_n$ 及其上的两个幂零轨道 $\mathcal O_\lambda$, $\mathcal O_\mu$，$\lambda \trianglerighteq \mu$ 当且仅当 $\mathcal O_\lambda \trianglerighteq \mathcal O_\mu$．
:::

:::{.proof}

## $\implies$ 侧思路概览

这里提供一种基于“连续路径”的证明．考虑 running example $\lambda = (4,2)$, $\mu = (3,3)$，$\lambda \trianglerighteq \mu$．如何连续地把幂零 Jordan 标准型矩阵 $J_{(4,2)}$ 变成 $J_{(3,3)}$ 呢？这样做：
$$
\begin{pmatrix}
0 & 1 &   &   &   &  \\
  & 0 & 1 &   &   &  \\
  &   & 0 &1-t&   &  \\
  &   &   & 0 &   &  \\
  &   &   &   & 0 & 1 \\
  &   &   & t & 0 & 0
\end{pmatrix}
$$
这里列出标准基底 $e_4$ 在上述矩阵多次作用下的变化情况：
$$
e_4 \longrightarrow +\left\{\begin{matrix}
t e_6 &\longrightarrow& t e_5 &\longrightarrow& 0& \\
(1-t) e_3 &\longrightarrow& (1-t) e_2 &\longrightarrow& (1-t) e_1 &\longrightarrow& 0
\end{matrix}\right.
$$
可以看到：

- 当 $t=0$ 时，就是 $J_{(4,2)}$；
- 当 $t \neq 1$ 时，Jordan 型为 $(4,2)$；
- 当 $t=1$ 时，Jordan 型突变为 $(3,3)$．

这是一条从 $\mathcal O_{(4,2)}$ 内部移动到 $\mathcal O_{(3,3)}$ 边缘的一条“连续路径”．抛开例子，上述论证对任意盖住关系都适用——只需关注 Young 图相邻两行之间的掉落，即可将这一保序映射扩展到任意 $\lambda \trianglerighteq \mu$．
:::

:::{.proof}

## $\implies$ 侧的证明

只需证明 $\lambda$ 盖住 $\mu$ 的情形，即 $\lambda$ 的 Young 图通过掉落一个方块变成 $\mu$ 的 Young 图．设是从 $\lambda$ 的第 $i$ 行掉到第 $i+1$ 行，记 $p = \lambda_i$, $q = \lambda_{i+1}$（从而 $p \geq q+2$）．其余各行均不受扰动，故问题约化为构造从 $\mathcal O_{(p,q)}$ 到 $\mathcal O_{(p-1,q+1)}$ 的路径．记 $J_p$, $J_q$ 分别为 $p$ 阶和 $q$ 阶幂零 Jordan 块，$E_{i,j}$ 是基本矩阵，定义矩阵系列 $\Gamma := \{\Gamma(t) : t \in \mathbb{C}\}$：
$$
\Gamma(t) := (J_p \oplus J_q) - t E_{p-1,\,p} + t E_{p+q,\,p}\qquad t \in \mathbb{C}
$$
它是幂零锥内满足多项式方程 $x_{p-1,p} + x_{p+q,p} = 1$、其它位置固定的闭子集．考察标准基 $(e_1, e_2, \dots, e_{p+q})$ 在 $\Gamma(t)$ 的作用下的变化情况：
$$
\begin{aligned}
\Gamma(t) e_1 &= 0 \\
\Gamma(t) e_{p+1} &= 0 \\
\Gamma(t) e_p &= (1-t) e_{p-1} + t e_{p+q} \\
\Gamma(t) e_{k} &= e_{k-1} \quad \text{other unspecified entry } k
\end{aligned}
$$
只有 $e_p$ 的变化情况依赖于 $t$．

- 当 $t \neq 1$，注意 $p \geq q+2$，故 $e_p$ 恰需 $p$ 次 $\Gamma(t)$ 作用变为 $0$．取 $e_p$ 和 $e_{p+q}$ 生成的循环基底
  $$
  \{\Gamma(t)^k e_p \}_{0 \leq k < p} \sqcup \{ e_k \}_{p < k \leq p+q}
  $$
  这组基在 $(e_k)_{k=1}^n$ 下可以排成对角线非零的三角矩阵，故确实线性无关．使用该循环基底可知 $\Gamma(t) \in \mathcal O_{(p,q)}$．

- 当 $t=1$ 时，$e_p$ 恰需 $q+1$ 次 $\Gamma(t)$ 作用变为 $0$，取 $e_{p-1}$ 和 $e_p$ 生成的循环基底
  $$
  \{ e_k \}_{1 \leq k < p} \sqcup \{\Gamma(1)^k e_p \}_{0 \leq k \leq q}
  $$
  这组基无非是 $(e_k)_{k=1}^n$ 的一个置换，故确实线性无关．使用该循环基底可知 $\Gamma(1) \in \mathcal O_{(p-1,q+1)}$．

于是 $\Gamma$ 只有一点不在 $\mathcal O_{(p,q)}$ 中，$\Gamma \cap \overline{\mathcal O_{(p,q)}} \supseteq \overline{\Gamma \cap \mathcal O_{(p,q)}} = \Gamma$，即 $\Gamma \subseteq \overline{\mathcal O_{(p,q)}}$．故 $\Gamma(1) \in \overline{\mathcal O_{(p,q)}}$，结合 [@prp-orbit-force-dominance] 即得 $\mathcal O_{(p-1,q+1)} \subseteq \overline{\mathcal O_{(p,q)}}$．
:::

:::{.proof}

## $\impliedby$ 侧的证明

注意如下若干事实：

- $\lambda \trianglerighteq \mu$ 当且仅当 $\lambda^T \trianglelefteq \mu^T$ [@mcgovern_nilpotent_1993, {lemma 6.3.1}]：可以通过 Young 图的掉落操作直观感受和证明这一点．

- 秩函数具有下半连续性（lower semicontinuity）：秩不大于某数 $k$ 的矩阵是闭集．秩的子式定义可以为此提供一个一句话证明：对这些矩阵的要求等价于大于 $k$ 阶的子式全为零．更一般地，对任意 $i \in \mathbb N$，由于 $A \mapsto A^i$ 连续，故复合函数 $A \mapsto \rk(A^i)$ 也下半连续．此性质使得当我们对幂零轨道取闭包时，元素及其幂次的秩都不会增加．

- 基于秩的 Jordan 型计算：Jordan 型为 $\lambda$ 的幂零矩阵 $X$ 满足其 $i$ 次幂的秩就是 Young 图 $\lambda$ 去掉前 $i$ 列剩下的方块数：
  $$
  \rk X^i = n - \sum_{k=1}^i (\lambda^T)_k, \quad i = 0, 1, \dots
  $$
  这里 $\lambda^T$ 是分拆 $\lambda$ 的转置，即 Young 图沿主对角线的翻转．反过来这为我们提供了计算 Jordan 型的秩方法：
  $$
  (\lambda^T)_k = \rk X^{k-1} - \rk X^k, \quad k = 1, 2, \dots
  $$
  此外，$X^i$ 的 Jordan 型的转置为 $(n - \rk X^i, \rk X^i - \rk X^{i-1}, \rk X^{i+1} - \rk X^i, \dots)$．

现在设 $\overline{\mathcal O_\lambda} \supseteq \mathcal O_\mu$．不妨任取代表元 $X \in \mathcal O_\lambda$, $Y \in \mathcal O_\mu$．对任意 $i \geq 1$，由 $A \mapsto \rk(A^i)$ 的下半连续性，$\rk Y^i \leq \rk X^i$，故
$$
n - \sum_{k=1}^i (\mu^T)_k = \rk Y^i \leq \rk X^i = n - \sum_{k=1}^i (\lambda^T)_k
$$
即 $\mu^T$ 的第 $i$ 个部分和大于等于 $\lambda^T$ 的第 $i$ 个部分和，故 $\mu^T \trianglerighteq \lambda^T$，$\lambda \trianglerighteq \mu$．
:::

细心的读者可能已经发现，[@thm-sl-closure-dominance] $\impliedby$ 一侧的证明对所有经典李代数都适用．自然会猜测经典李代数上的幂零轨道的支配序也和分拆上的支配序等价．事实确实如此：

:::{#thm-classic-closure-dominance}

对任意经典李代数 $\mathfrak g$ 及其上的两个幂零轨道 $\mathcal O_\lambda$, $\mathcal O_\mu$，$\lambda \trianglerighteq \mu$ 当且仅当 $\mathcal O_\lambda \trianglerighteq \mathcal O_\mu$．
:::

本章的剩余部分将致力于证明上述定理的 $\implies$ 侧．总的来说，思路仍然是为每个盖住关系构造一条连续路径，从支配序较大的轨道连接到支配序较小轨道的“边缘”．但不同于 A 型李代数，B、C、D 型李代数要求路径落在斜自伴李代数中；且幂零轨道的 Jordan 型存在额外的限制条件，需要讨论的盖住关系更多更复杂．为处理方便，我们将需要在不同情形 B、C、D 型李代数选取特定的非退化双线性型．

## C 型李代数

本节先来处理 $C$ 型李代数 $\sp_{2n}$．

### 组合图示

记 $\mathbb C^{2n}$ 上的标准基为 $(e_1,f_1,e_2,f_2,\dots,e_n,f_n)$，选取非退化斜对称双线性型
$$
\begin{aligned}
\varphi(e_i, f_i) &= 1 &\text{for } 1 \leq i \leq n \\
\varphi(f_i, e_i) &= -1 &\text{for } 1 \leq i \leq n \\
\varphi(-,-) &= 0 &\text{other unspecified pairs}
\end{aligned} 
\qquad
\Phi := 
\begin{pmatrix}
0 & 1 &   &   &   &  \\
-1 & 0 &   &   &     \\
  &   & 0 & 1 &   &  \\
  &   & -1 & 0 &     \\
  &   &   &   & \ddots & 
\end{pmatrix}
$$
借此定义 $\sp_{2n}$ 为满足斜自伴条件 $X^T \Phi = -\Phi X$ 的全体 $2n$ 阶矩阵．矩阵计算可得 $\sp_{2n}$ 的分块矩阵描述：
$$
\begin{pmatrix}
C_{1,1} & C_{1,2} & \ldots \\
C_{2,1} & C_{2,2} & \ldots \\
\vdots & \vdots & \ddots\\
\end{pmatrix}
\qquad
\begin{aligned}
C_{i,i}
&=
\begin{pmatrix}
r_i & \textcolor{teal}{s_i} \\
\textcolor{blue}{t_i} & -r_i
\end{pmatrix}
& 1 \leq i = j \leq n \\
C_{i,j}
&=
\begin{pmatrix}
a_{i,j} & \textcolor{red}{b_{i,j}} \\
c_{i,j} & \textcolor{violet}{d_{i,j}}
\end{pmatrix}
& 1 \leq i < j \leq n \\
C_{j,i} &=
\begin{pmatrix}
\textcolor{violet}{-d_{i,j}} & \textcolor{red}{b_{i,j}} \\
c_{i,j} & -a_{i,j}
\end{pmatrix}
& 1 \leq i < j \leq n
\end{aligned}
$$
注意变元的数量和 $\dim \sp_{2n} = 2n^2 + n$ 相符．

现在考虑构造具有特定 Jordan 型的幂零斜自伴矩阵 $X$．观察 $\textcolor{teal}{s_i}$, $\textcolor{blue}{t_i}$, $\textcolor{violet}{d_{i-1,i}}$, $\textcolor{red}{b_{i-1,i}}$ 的作用：

$$
\begin{aligned}
X(f_i) &= \textcolor{violet}{d_{i-1,i}} f_{i-1} + \textcolor{teal}{s_i} e_i + \textcolor{red}{b_{i-1,i}} e_{i-1} + \dots \\
X(e_i) &= \textcolor{violet}{-d_{i,i+1}} e_{i+1} + \textcolor{blue}{t_i} f_i + \textcolor{red}{b_{i,i+1}} f_{i+1} + \dots
\end{aligned}
$$
如果将来只使用这四个变元来构造所有所需的斜自伴幂零矩阵，那么 $X$ 的在基底上的作用可完全用如下组合图示来描述：先将基底 $(e_1,f_1,\dots,e_n, f_n)$ 排成两行
$$
\begin{matrix}
f_1 & f_2 & \dots & f_{n-1} & f_n \\
e_1 & e_2 & \dots & e_{n-1} & e_n
\end{matrix}
$$
进而在上述 $2n$ 个节点的图间连接如下四种类型的边：

:::{#fig-cover-c-arrow}

```{tikz}
\begin{tikzcd}
	{f_{k}} & {f_k} & {f_{k-1}} & {f_{k}} & {f_{k-1}} & {f_{k}} \\
	{e_k} & {e_k} & {e_{k-1}} & {e_k} & {e_{k-1}} & {e_k}
	\arrow["{s_k}", color=teal, from=1-2, to=2-2]
	\arrow["{d_{k-1,k}}"', color=violet, from=1-4, to=1-3]
	\arrow["{b_{k-1,k}}"{pos=0}, color=red, from=1-5, to=2-6]
	\arrow["{b_{k-1,k}}"'{pos=0}, color=red, from=1-6, to=2-5]
	\arrow["{t_k}", color=blue, from=2-1, to=1-1]
	\arrow["{-d_{k-1,k}}"', color=violet, from=2-3, to=2-4]
\end{tikzcd}
```
:::

则 $X$ 在每个基向量的作用描述为从该节点出发的所有边的终点向量的线性组合，组合系数由边权给出．组合图示使未来在构造路径时跟踪 Jordan 型的变化情况更容易．在以后的构造中，我们便放心忘记 $X$ 的矩阵形式，直接使用图示来给出所需的幂零斜自伴矩阵．

### 盖住关系与路径构造

与 A 型类似，还是只需要考虑大小相邻的块之间的掉落．但注意 C 型李代数的分拆特别要求奇数部分必须出现偶数次，故需要讨论如下 5 种类型的掉落．对每种掉落，构造路径 $\Gamma := \{\Gamma(t) \in \sp_{2n} : t \in \mathbb C \}$，其中每个 $\Gamma(t)$ 的组合图示如下（以下默认要求非负整数 $p$, $q$ 使得分拆中每块大小非负）：

#### 情形一 $(2p,2q) \to (2p-1,2q+1)$, $p = q+1$

:::{#fig-cover-c-2p2q-special}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=teal, from=1-1, to=2-1]
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["1"', color=violet, from=1-4, to=1-3]
	\arrow["t"{pos=0}, dashed, color=red, from=1-4, to=2-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=2-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=2-1, to=2-2]
	\arrow["{-1}"', color=violet, from=2-2, to=2-3]
	\arrow["{-1}"', color=violet, from=2-3, to=2-4]
	\arrow["{-1}"', color=violet, from=2-5, to=2-6]
	\arrow["{-1}"', color=violet, from=2-6, to=2-7]
	\arrow["1"', color=blue, from=2-7, to=1-7]
\end{tikzcd}
```
:::

对 $p = q+1 = 1$ 的情形，取路径 $f_1 \xrightarrow{1-t} e_1$ 即可．对 $p = q+1 = 2$ 的情形，阅读一般情况证明后补证不难．故设 $p \geq 3$．考察 $f_p$ 和 $e_{p+1} + t f_{p-2}$ 在 $\Gamma(t)$ 多次作用下的变化情况：
$$
\begin{aligned}
f_p &\longrightarrow +\left\{\begin{matrix}
	f_{p-1}   &\xrightarrow{\dots}& f_1 			 &\longrightarrow& e_1 &\xrightarrow{\dots} \\
	t e_{p+1} &\xrightarrow{\dots}& (-1)^{q-1} t e_{p+q} &\longrightarrow& (-1)^{q-1} t f_{p+q} &\xrightarrow{\dots}
\end{matrix}\right. \\
&\left.\begin{matrix}
	\xrightarrow{\dots}& (-1)^{p-2} e_{p-1} &\longrightarrow& (-1)^{p-1} e_p \\
	\xrightarrow{\dots}& (-1)^{q-1} t f_{p+1} &\longrightarrow& (-1)^{q-1} t^2 e_p
\end{matrix}\right\}
= (-1)^{p-1} (1-t^2) e_p
\end{aligned}
$$
$$
\left.\begin{matrix}
t f_{p-2} &\xrightarrow{\dots}& t e_1              &\xrightarrow{\dots}& (-1)^{p-2} t e_{p-1} &\longrightarrow& (-1)^{p-1} t e_p \\
e_{p+1}   &\xrightarrow{\dots}& (-1)^{q-1} e_{p+q} &\xrightarrow{\dots}& (-1)^{q-1}   f_{p+1} &\longrightarrow& (-1)^{q-1} t e_p
\end{matrix}\right\} += 0
$$

- 当 $t \neq 1$ 时，取 $f_p$ 和 $e_{p+1} + t f_{p-2}$．在 $\Gamma(t)$ 作用下生成循环基底，长度分别为 $2p$ 和 $2q$．注意它们在标准基底 $(e_1,f_1,\dots,e_n,f_n)$ 下可排成对角线非零的三角矩阵，确实线性无关．故此时 $\Gamma(t)$ 的 Jordan 型为 $(2p,2q)$．

- 当 $t = 1$ 时，取 $f_p$ 和 $e_{p+1}$ 在 $\Gamma(t)$ 作用下生成循环基底，长度分别为 $2p-1$ 和 $2q+1$．注意它们在标准基底 $(e_1,f_1,\dots,e_n,f_n)$ 下可排成对角线非零的三角矩阵，确实线性无关．故此时 $\Gamma(t)$ 的 Jordan 型为 $(2p-1,2q+1)$．

:::{.remark}

#### $(2p,2q) \to (p+q, p+q)$, $p \geq q+2$

情形一的掉落可以看作是 $(2p,2q) \to (p+q, p+q)$ 的特例．我们有如下不同思路的构造．

:::::{#fig-cover-c-2p-2p2q-avg}

```{tikz}
\begin{tikzcd}
	{f_1} & {f_2} & \dots & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{e_1} & {e_2} & \dots & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["1"', color=violet, from=1-4, to=1-3]
	\arrow["t"', color=violet, dashed, from=1-5, to=1-4]
	\arrow["{1-t}", color=teal, dashed, from=1-5, to=2-5]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=2-1, to=2-2]
	\arrow["{-1}"', color=violet, from=2-2, to=2-3]
	\arrow["{-1}"', color=violet, from=2-3, to=2-4]
	\arrow["{1-t}", color=blue, dashed, from=2-4, to=1-4]
	\arrow["-t"', color=violet, dashed, from=2-4, to=2-5]
	\arrow["{-1}"', color=violet, from=2-5, to=2-6]
	\arrow["{-1}"', color=violet, from=2-6, to=2-7]
\end{tikzcd}
```
:::::

当 $t \neq 1$ 时，考察 $e_1$ 和 $(1-t) f_{p+q} + (-1)^q t e_{p-q+1}$ 在 $\Gamma(t)$ 多次作用下的变化情况：
$$
e_1 \longrightarrow \dots \longrightarrow \pm e_p
\longrightarrow +\left\{\begin{matrix}
(1-t) f_p   &\xrightarrow{\dots}& (1-t) f_{p-q+1} &\xrightarrow{\dots}& (1-t) f_1 \\
\pm t e_{p+1} &\xrightarrow{\dots}& \pm t e_{p+q}
\end{matrix}\right.
$$
$$
\begin{aligned}
\left.\begin{matrix}
(1-t) f_{p+q}      &\xrightarrow{\dots}& (1-t) f_{p+1} &\longrightarrow& t(1-t) f_p + (1-t)^2 e_{p+1} \\
(-1)^q t e_{p-q+1} &\xrightarrow{\dots}& -t e_p        &\longrightarrow& -t(1-t) f_p + t^2 e_{p+1}
\end{matrix}\right\} +
= (t^2 + (1-t)^2) e_{p+1} \\
\longrightarrow \dots \longrightarrow (t^2 + (1-t)^2) e_{p+q}
\end{aligned}
$$
故取此二向量生成的循环基底，长度分别为 $2p$ 和 $2q$．注意它们在标准基底 $(e_1,f_1,\dots,e_n,f_n)$ 下可排成对角线非零的三角矩阵，确实线性无关．故此时 $\Gamma(t)$ 的 Jordan 型为 $(2p,2q)$．

当 $t = 1$ 时，取 $e_1$ 和 $f_{p+q}$ 生成的循环基底，易见长度均为 $p+q$，且它们无非是标准基底 $(e_1,f_1,\dots,e_n,f_n)$ 的一个置换，确实线性无关．故此时 $\Gamma(t)$ 的 Jordan 型为 $(p+q,p+q)$．
:::

#### 情形二 $(2p,2q) \to (2p-2,2q+2)$, $p \geq q+2$

:::{#fig-cover-c-2p2q}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=teal, from=1-1, to=2-1]
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["t"{pos=0}, dashed, color=red, from=1-4, to=2-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=2-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=2-1, to=2-2]
	\arrow["{-1}"', color=violet, from=2-2, to=2-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=2-3, to=2-4]
	\arrow["{-1}"', color=violet, from=2-5, to=2-6]
	\arrow["{-1}"', color=violet, from=2-6, to=2-7]
	\arrow["1"', color=blue, from=2-7, to=1-7]
\end{tikzcd}
```
:::

当 $t \neq 1$ 时，考察 $f_p$ 和 $e_{p+1} \pm t e$ 生成的循环基底，这里 $e$ 指代在左侧在 $\Gamma(t)$ 作用下恰需 $2q$ 步跳至 $e_p$ 的元素，正负号应恰使 $e_{p+1} \pm t e$ 在 $\Gamma(t)$ 作用下最后一步 $e_p$ 处两端系数抵消．分析过程与情形一类似，最终可知 $\Gamma(t)$ 的 Jordan 型为 $(2p,2q)$．

当 $t = 1$ 时，取 $f_{p-1}$ 和 $f_p$ 生成的循环基底，可知 $\Gamma(t)$ 的 Jordan 型为 $(2p-2,2q+2)$．

后续情形的分析与情形二类似，我们仅给出组合图示，细节不再赘述．

#### 情形三 $(2p,q,q) \to (2p-2,q+1,q+1)$, $2p \geq q+3$

:::{#fig-cover-c-2pqq}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=teal, from=1-1, to=2-1]
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["t"{pos=0}, dashed, color=red, from=1-4, to=2-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=2-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=2-1, to=2-2]
	\arrow["{-1}"', color=violet, from=2-2, to=2-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=2-3, to=2-4]
	\arrow["{-1}"', color=violet, from=2-5, to=2-6]
	\arrow["{-1}"', color=violet, from=2-6, to=2-7]
\end{tikzcd}
```
:::

#### 情形四 $(p,p,2q) \to (p-1,p-1,2q+2)$, $p \geq 2q+3$

:::{#fig-cover-c-pp2q}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["t"{pos=0}, dashed, color=red, from=1-4, to=2-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=2-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=2-1, to=2-2]
	\arrow["{-1}"', color=violet, from=2-2, to=2-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=2-3, to=2-4]
	\arrow["{-1}"', color=violet, from=2-5, to=2-6]
	\arrow["{-1}"', color=violet, from=2-6, to=2-7]
	\arrow["1"', color=blue, from=2-7, to=1-7]
\end{tikzcd}
```
:::

#### 情形五 $(p,p,q,q) \to (p-1,p-1,q+1,q+1)$, $p \geq q+2$

:::{#fig-cover-c-ppqq}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["t"{pos=0}, dashed, color=red, from=1-4, to=2-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=2-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=2-1, to=2-2]
	\arrow["{-1}"', color=violet, from=2-2, to=2-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=2-3, to=2-4]
	\arrow["{-1}"', color=violet, from=2-5, to=2-6]
	\arrow["{-1}"', color=violet, from=2-6, to=2-7]
\end{tikzcd}
```
:::

上述讨论完成了 [@thm-classic-closure-dominance]	$\implies$ 侧在 C 型李代数上的证明．

## B 型和 D 型李代数

### 组合图示

B 型李代数和 D 型李代数 $\so_n$ 的构造更加复杂．为处理方便，往往需要为每种盖住关系分别构造不同的对称双线性型．一般地，记 $\mathbb C^n$ 上的标准基为 $(g_1, \dots, g_\alpha, h_1,\dots,h_\beta, e_1,f_1,\dots,e_\gamma, f_\gamma)$，这里 $\alpha + \beta + 2\gamma = n$．选取非退化对称双线性型
$$
\begin{aligned}
\varphi(g_i, g_i) &= 1  & \text{for } 1 \leq i \leq \alpha \\
\varphi(h_j, h_j) &= -1 & \text{for } 1 \leq j \leq \beta \\
\varphi(e_k, f_k) &= 1 & \text{for } 1 \leq k \leq \gamma \\
\varphi(f_k, e_k) &= 1 & \text{for } 1 \leq k \leq \gamma \\
\varphi(-,-) &= 0 & \text{other unspecified pairs}
\end{aligned}
\qquad
\Phi :=
\begin{pmatrix}
I_\alpha &   &   &   &   &  \\
  & -I_\beta &   &   &   &  \\
  &   & 0 & 1 &   &   & \\
  &   & 1 & 0 &   &   & \\
  &   &   &   & 0 & 1 & \\
  &   &   &   & 1 & 0 & \\
  &   &   &   &   &   & \ddots
\end{pmatrix}
$$
借此定义 $\so_n$ 为满足自伴条件 $X^T \Phi = -\Phi X$ 的全体 $n$ 阶矩阵．为精简记号，我们不再画出整个斜对称矩阵 $X$ 的分块表示，而是分类讨论 $g_i$, $h_j$ 和 $(e_k, f_k)$ 间的关系，并给出它们在组合图示中的表现：

- $g_i$ 之间：
  $$
  \begin{pmatrix} g_1^T \\ g_2^T \end{pmatrix} X \begin{pmatrix} g_1 & g_2 \end{pmatrix}
  = \begin{pmatrix} 0 & * \\ -* & 0 \end{pmatrix}
  $$
  我们在组合图示中不使用这些关系．

- $h_j$ 之间：
  $$
  \begin{pmatrix} h_1^T \\ h_2^T \end{pmatrix} X \begin{pmatrix} h_1 & h_2 \end{pmatrix}
  = \begin{pmatrix} 0 & * \\ -* & 0 \end{pmatrix}
  $$
  我们在组合图示中不使用这些关系．

- $g_i$ 和 $h_j$ 之间：
  $$
  \begin{pmatrix} g_i^T \\ h_j^T \end{pmatrix} X \begin{pmatrix} g_i & h_j \end{pmatrix}
  = \begin{pmatrix} 0 & * \\ * & 0 \end{pmatrix}
  $$
  我们在组合图示中不使用这些关系．

- $(e_k, f_k)$ 之间：
  $$
  \begin{pmatrix} e_1^T \\ f_1^T \\ e_2^T \\ f_2^T \end{pmatrix} X \begin{pmatrix} e_1 & f_1 & e_2 & f_2 \end{pmatrix}
  = \begin{pmatrix}
  r_1 & 0  & a & \textcolor{red}{b} \\
  0 & -r_1 & c & \textcolor{violet}{d} \\
  \textcolor{violet}{-d} & \textcolor{red}{-b} & r_2 & 0 \\
  -c & -a & 0 & -r_2
  \end{pmatrix}
  $$
  注意这里和 C 型李代数的区别：原来 $s$ 和 $t$ 所在位置现在强制为零，不再具有自由度．这是 B 型和 D 型李代数的构造变复杂的主要原因之一．我们将在组合图示中使用 $\textcolor{violet}{d}$ 和 $\textcolor{red}{b}$：

- $g_i$ 和 $(e_k, f_k)$ 之间：
  $$
  \begin{pmatrix} g^T \\ e^T \\ f^T \end{pmatrix} X \begin{pmatrix} g & e & f \end{pmatrix}
  = \begin{pmatrix}
  0 & x & \textcolor{teal}{y} \\
  \textcolor{teal}{-y} & 0 & 0 \\
  -x & 0 & 0
  \end{pmatrix}
  $$
  我们将在组合图示中使用 $\textcolor{teal}{y}$．

- $h_j$ 和 $(e_k, f_k)$ 之间：
  $$
  \begin{pmatrix} h^T \\ e^T \\ f^T \end{pmatrix} X \begin{pmatrix} h & e & f \end{pmatrix}
  = \begin{pmatrix}
  0 & \textcolor{blue}{z} & w \\
  w & 0 & 0 \\
  \textcolor{blue}{z} & 0 & 0
  \end{pmatrix}
  $$
  我们将在组合图示中使用 $\textcolor{blue}{z}$．

:::{#fig-cover-bd-arrow}

```{tikz}
\begin{tikzcd}
	{f_1} & {f_2} & {f_1} & {f_2} & f & f & \\
	&&&& g & h \\
	{e_1} & {e_2} & {e_1} & {e_2} & e & e
	\arrow["d"', color=violet, from=1-2, to=1-1]
	\arrow["{{-b}}"{pos=0}, color=red, from=1-3, to=3-4]
	\arrow["b"'{pos=0}, color=red, from=1-4, to=3-3]
	\arrow["{{-d}}"', color=violet, from=3-1, to=3-2]
	\arrow["y"', color=teal, from=1-5, to=2-5]
	\arrow["{-y}"', color=teal, from=2-5, to=3-5]
	\arrow["z"', color=blue, from=2-6, to=1-6]
	\arrow["z"', color=blue, from=3-6, to=2-6]
\end{tikzcd}
```
:::

### 盖住关系与路径构造

构造手段和 C 型李代数类似，故我们也只给出构造，不再验证细节．

#### 情形一 $(2p+1,2q+1) \to (2p,2q+2)$, $p = q+1$

取 $\alpha = 1$, $\beta = 1$, $\gamma = p+q$．

:::{#fig-cover-c-2p12q1-special}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{g_1} &         & 		    &       &           &       & {h_1}       \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=teal, from=1-1, to=2-1]
	\arrow["-1"', color=teal, from=2-1, to=3-1]
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["1"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["{-t}"{pos=0}, dashed, color=red, from=1-4, to=3-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=3-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=3-1, to=3-2]
	\arrow["{-1}"', color=violet, from=3-2, to=3-3]
	\arrow["{-1}"', color=violet, dashed, from=3-3, to=3-4]
	\arrow["{-1}"', color=violet, from=3-5, to=3-6]
	\arrow["{-1}"', color=violet, from=3-6, to=3-7]
	\arrow["1"', color=blue, from=3-7, to=2-7]
	\arrow["1"', color=blue, from=2-7, to=1-7]
\end{tikzcd}
```
:::

#### 情形二 $(2p+1,2q+1) \to (2p-1,2q+3)$, $p \geq q+2$

取 $\alpha = 1$, $\beta = 1$, $\gamma = p+q$．

:::{#fig-cover-bd-2p12q1}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{g_1} &         & 		    &       &           &       & {h_1}      \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=teal, from=1-1, to=2-1]
	\arrow["-1"', color=teal, from=2-1, to=3-1]
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["{-t}"{pos=0}, dashed, color=red, from=1-4, to=3-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=3-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=3-1, to=3-2]
	\arrow["{-1}"', color=violet, from=3-2, to=3-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=3-3, to=3-4]
	\arrow["{-1}"', color=violet, from=3-5, to=3-6]
	\arrow["{-1}"', color=violet, from=3-6, to=3-7]
	\arrow["1"', color=blue, from=3-7, to=2-7]
	\arrow["1"', color=blue, from=2-7, to=1-7]
\end{tikzcd}
```
:::

#### 情形三 $(2p+1,q,q) \to (2p-1,q+1,q+1)$, $2p \geq q+2$

取 $\alpha = 1$, $\beta = 0$, $\gamma = p+q$．

:::{#fig-cover-bd-2p1qq}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	{g_1} &         & 		    &       &           &       &           \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=teal, from=1-1, to=2-1]
	\arrow["-1"', color=teal, from=2-1, to=3-1]
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["{-t}"{pos=0}, dashed, color=red, from=1-4, to=3-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=3-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=3-1, to=3-2]
	\arrow["{-1}"', color=violet, from=3-2, to=3-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=3-3, to=3-4]
	\arrow["{-1}"', color=violet, from=3-5, to=3-6]
	\arrow["{-1}"', color=violet, from=3-6, to=3-7]
\end{tikzcd}
```
:::

#### 情形四 $(p,p,2q+1) \to (p-1,p-1,2q+3)$, $p \geq 2q+4$

取 $\alpha = 0$, $\beta = 1$, $\gamma = p+q$．

:::{#fig-cover-bd-pp2q1}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	      &         & 		    &       &           &       & {h_1}      \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["{-t}"{pos=0}, dashed, color=red, from=1-4, to=3-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=3-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=3-1, to=3-2]
	\arrow["{-1}"', color=violet, from=3-2, to=3-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=3-3, to=3-4]
	\arrow["{-1}"', color=violet, from=3-5, to=3-6]
	\arrow["{-1}"', color=violet, from=3-6, to=3-7]
	\arrow["1"', color=blue, from=3-7, to=2-7]
	\arrow["1"', color=blue, from=2-7, to=1-7]
\end{tikzcd}
```
:::

#### 情形五 $(p,p,q,q) \to (p-1,p-1,q+1,q+1)$, $p \geq q+2$

取 $\alpha = 0$, $\beta = 0$, $\gamma = p+q$．

:::{#fig-cover-bd-ppqq}

```{tikz}
\begin{tikzcd}
	{f_1} & {\dots} & {f_{p-1}} & {f_p} & {f_{p+1}} & \dots & {f_{p+q}} \\
	      &         & 		    &       &           &       &           \\
	{e_1} & {\dots} & {e_{p-1}} & {e_p} & {e_{p+1}} & \dots & {e_{p+q}}
	\arrow["1"', color=violet, from=1-2, to=1-1]
	\arrow["1"', color=violet, from=1-3, to=1-2]
	\arrow["{1-t}"', color=violet, dashed, from=1-4, to=1-3]
	\arrow["{-t}"{pos=0}, dashed, color=red, from=1-4, to=3-5]
	\arrow["t"'{pos=0}, dashed, color=red, from=1-5, to=3-4]
	\arrow["1"', color=violet, from=1-6, to=1-5]
	\arrow["1"', color=violet, from=1-7, to=1-6]
	\arrow["{-1}"', color=violet, from=3-1, to=3-2]
	\arrow["{-1}"', color=violet, from=3-2, to=3-3]
	\arrow["{-(1-t)}"', color=violet, dashed, from=3-3, to=3-4]
	\arrow["{-1}"', color=violet, from=3-5, to=3-6]
	\arrow["{-1}"', color=violet, from=3-6, to=3-7]
\end{tikzcd}
```
:::

上述讨论完成了 [@thm-classic-closure-dominance]	$\implies$ 侧在 B、D 型李代数上的证明．