---
title: Spec，可约与连通性
date: 2026/02/27
author: sun123zxy
lang: zh

bibliography: index.bib

draft: true

categories:
  - math
  - algebra
  - commalg

collection:
  - short

number-sections: true

format:
  html: default
---

\newcommand{\Spec}{\operatorname{Spec}}

本文中环均为交换幺环．

## 定义

环的 Spec 是由它的素理想配备 Zariski 拓扑构成的拓扑空间，Zariski 拓扑的闭集由 $V(I) = \{ \mathfrak p : I \subseteq \mathfrak p \}$ 组成，其中 $I$ 是环的任意理想．

不可约是指 Spec 不能写成两个非空闭集的并．连通是指 Spec 不能写成两个非空不交闭集的并．

有一类特殊的环：

- 它们是有限生成的 $k$-代数（$k$ 是域），总可以写成 $k[x_1, \dots, x_n]/I$．它们的 Spec 叫做代数集．

- 如果（nilradical 意义下）此环既约 / $I$ 是既约的，就叫这个环是代数集的坐标环，或者仿射 $k$-代数．

- 在此基础上，如果 TFAE 地 [@prp-irr-iff-rad-prime]：Spec 不可约 / $I$ 是素理想 / 坐标环是整环，则称这个代数集是一个代数簇．

## 性质

### Spec 不可约 $\implies$ Spec 连通

不可约是比连通更强的性质：不可约的判否不要求两闭集的交集非空，而连通的判否额外要求两个闭集的交集非空．

### Spec 不可约 $\iff$ nilradical 是素理想

::: {#prp-irr-iff-rad-prime}

## [@AM1969, {exercise 1.19}]

环 $R$ 的 Spec 不可约当且仅当 $R$ 的 nilradical $\mathcal N(R)$ 是素理想．
:::

这是因为对任意理想 $I$, $J$：
$$
V(I) \cup V(J) = \Spec R
\iff V(IJ) = \Spec R
\iff IJ \subseteq \mathcal N(R)
$$
不失一般性，可以选取既约的理想 $I$ 和 $J$，这样后者就意味着对 $\mathcal N(R)$ 是素理想的否定．

### 既约环：整环 $\iff$ 不可约

整环的 Spec 是不可约的，反之未必：$k[x]/(x^2)$ 的 Spec 是单点 $(x)$，但 $k[x]/(x^2)$ 不是整环．这完全是 nilradical 的锅——如果环既约 $\mathcal N(R) = (0)$，则 Spec 不可约当且仅当坐标环是整环．这也是仿射 $k$-代数的情况．

### CRing $\times$ $\iff$ Spec $\sqcup$

环侧的 $\times$ / 直积 对应 Spec 侧的无交并 / 直和．环的直积导致典型的不连通．

对非零环 $A$, $B$，$A \times B$ 的 Spec 与 $\Spec A \sqcup \Spec B$ 同胚：

- 它的理想都形如 $I \times J$：总可以通过乘 $(1, 0)$ 和 $(0, 1)$ 来得到 $I$ 和 $J$．
- 它的素理想都形如 $\mathfrak p \times B$ 或 $A \times \mathfrak q$：如果 $I \times J$ 是素理想，那么 $I$ 或 $J$ 必须是素理想，因为两侧的乘法互不干扰；也不能是 $\mathfrak p \times \mathfrak q$，否则可取 $p \notin \mathfrak p$ 和 $q \notin \mathfrak q$ 使得 $(p, *) (*, q) \in \mathfrak p \times \mathfrak q$．
- $V(I \times J) = \{ \mathfrak p \times B : \mathfrak p \in V(I) \} \cup \{ A \times \mathfrak q : \mathfrak q \in V(J) \}$，这就把 $\Spec(A \times B)$ 和 $\Spec A \sqcup \Spec B$ 两个拓扑空间的闭集对应上了．

### 幂等元与 Spec 连通性

环 $R$ 内每个幂等元 $e$ 都对应一个 Spec 上的开闭集 $V(e)$：

- $V(e)$ 也是开集：$V(e) = D(1-e)$．

- 单射性：假如 $V(e_1) = V(e_2)$，那么 $\sqrt{(e_1)} = \sqrt{(e_2)}$，不妨设 $e_1^n = r e_2$，但是 $e_1$ 幂等，即 $e_1 = re_2$．同乘 $e_2$ 得 $e_1 e_2 = r e_2^2 = r e_2 = e_1$．同理也有 $e_2 = e_1 e_2$，所以 $e_1 = e_2$．

- 满射性：对于任意开闭集 $V(I)$，令与它互补的开闭集为 $V(J)$，则
  $$
  \begin{aligned}
  V(I \cap J) = V(IJ) &= V(I) \cup V(J) = \Spec R \\
  V(I + J) &= V(I) \cap V(J) = \emptyset
  \end{aligned}
  $$
  推得 $I \cap J \subseteq IJ$ 落在 nilradical $\mathcal N(R)$ 中，且 $I + J = R$——comaximal．

  如果是 Noether 环的话，$IJ$ 会幂零，中国剩余定理就可以直接收工．一般情况则需要一些技巧．使用 comaximal 取出 $x \in I$ 和 $y \in J$ 使得 $x + y = 1$，因为 $xy \in IJ \subseteq \mathcal N(R)$，不妨设 $(xy)^n = 0$，考察
  $$
  \begin{aligned}
  1 &= (x + y)^{2n} \\
    &= \sum_{i=0}^{2n} \binom{2n}{i} x^i y^{2n-i} \\
    &= \sum_{i=0}^{n-1} \binom{2n}{i} x^i y^{2n-i} + \sum_{i=n+1}^{2n} \binom{2n}{i} x^i y^{2n-i}
  \end{aligned}
  $$
  设后两项分别为 $d$ 和 $e$，则 $d \in J$, $e \in I$, $d + e = 1$, $de = 0$，这样就证明了 $d$ 和 $e$ 是幂等元．

  现在注意以下关系：$V(e) \subseteq V(I)$, $V(d) \subseteq V(J)$ 且 $V(e) \sqcup V(d) = \Spec R = V(I) \sqcup V(J)$，即可迫使 $V(e) = V(I)$ 和 $V(d) = V(J)$．

因此 Spec 连通当且仅当环内没有非平凡的幂等元．

:::{.remark}

这个二项式展开的技巧也可以用来证明：comaximal 的理想 $I$ 和 $J$ 的任意幂次 $I^m$ 和 $J^n$ 也是 comaximal 的．
:::

:::{.remark}

注意 Noether 环中，Spec 的连通分支有限：否则这些闭集对应的理想形成无限升链．有限性导致连通分支既开又闭——此时开闭集与连通分支的各种取并一一对应，进而可以使用幂等元完整刻画连通分支，此时可以把环分解成与连通分支对应的有限直积．

**Takeaway:** 看上去不连通就可以拆，拆完后的环没有非平凡幂等元．

作为推论之一，Artin 环可以被分解成有限个局部 Artin 环的直积 [@AM1969, {theorem 8.7}]，一个证明可以参考[这里](/posts/20250731-artin-noether/)，可以看到证明几乎和上面满射性 Noether 环的 if 线一致．

还想继续拆？请见准素分解．既约理想结果好，作为素理想的交分解唯一．
:::

### f.g. 连通的话，是不是会导致 module rank of fiber 恒定？

### 环侧的 $\otimes$ / push-out 对应 Spec 侧的纤维积 / pull-back

## 使用例

### $V(xy)$

来考察二维仿射平面上的 $V(xy)$．它的坐标环是 $k[x,y]/(xy)$，不是整环，因此可约——但 $V(xy)$ 连通：

- 直观来看，$V(xy)$ 是 $x$ 轴和 $y$ 轴的并集，所以可约；它们在原点相交，所以连通．
- 严格来看，$V(xy) = V(x) \cup V(y)$，所以可约；$V(x)$ 和 $V(y)$ 都是不可约代数集，因此各自连通，它们交集还非空，纯点集拓扑论证（用连通性等价于所有到 $\{0, 1\}$ 连续函数常值的等价刻画）可以保证并集也连通．

以防你想歪，别以为可以用中国剩余定理把坐标环分解成 $k[x] \times k[y]$：$(x)$ 和 $(y)$ 根本不是 comaximal 的——这俩一加等于 $(x,y)$——恰好也对应了 Spec 那一侧交点．

### 局部环的 Spec 连通

因为极大理想只有一个，而 Zariski 拓扑的非空闭集都包含它，没法做不交的划分． 

### 局部环的 Spec 什么时候可约？

TODO