---
title: 诱导表示乱炖
subtitle: Mackey 不可约性定理
author: sun123zxy
date: 2026-08-05
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
  - rep-theory

number-sections: true

format:
  html: default
---

\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\GL}{\operatorname{GL}}
\newcommand{\acts}{\curvearrowright}
\newcommand{\Ind}[3]{\left\uparrow \!_{#1}^{#2} {#3} \right.}
\newcommand{\Res}[3]{\left\downarrow \!^{#1}_{#2} {#3} \right.}
\newcommand{\galg}[1]{{k}[{#1}]}
\newcommand{\mapsfrom}{\leftarrow \! |}

在日常生产生活中，经常需要将一个群表示从一个子群扩展到整个群．在所有可能的选择中，诱导表示是最自然的一种．

如无特殊说明，全文默认假设在特征 $0$ 的代数闭域 $k$ 和有限群 $G$ 中工作．我们尽力在合适的时候指明可以放松的条件．

设子群 $H \leq G$，则

- 对 $G$-表示 $V$，定义限制表示 $\Res G H V$ 为 $V$ 自身限制为 $H$-表示；
- 对 $H$-表示 $W$，定义诱导表示 $\Ind H G W := \galg G \otimes_{\galg H} W$，即 $(\galg G, \galg H)$-双模 $\galg G$ 和 $\galg H$-模 $W$ 的张量积．

特征标我们使用相同记号：$\Res G H {\chi_V} := \chi_{\Res G H V}$; $\Ind H G {\chi_W} := \chi_{\Ind H G W}$．

## 具体记号

张量积的写法相对抽象，这里给出一种更具体的写法．固定一组 $G/H$ 的陪集代表元 $(s)_{[s] \in G/H}$，首先注意作为 $(k, \galg H)$-双模 $\galg G = \bigoplus_{[s] \in G/H} \galg{sH}$，于是作为 $k$-线性空间
$$
\begin{matrix}
\galg G \otimes_{\galg H} W
&=& \left(\bigoplus_{[s] \in G/H} \galg{sH} \right) \otimes_{\galg H} W
&\cong& \bigoplus_{[s] \in G/H} \galg{sH} \otimes_{\galg H} W &=:& \bigoplus_{[s] \in G/H} s \otimes W \\
g \otimes w &=& s_g h_g \otimes w &\mapsto& s_g h_g \otimes w &=:& s_g \otimes (h_g \cdot w)
\end{matrix}
$$
这里映射中我们设 $g$ 有 $G/H$-分解 $g=s_g h_g$．注意最后一项的每个直和项 $s \otimes W$ 是我们方便起见新定义的记号．平凡可见作为线性空间 $s \otimes W \cong W$．作为同构的副产品，我们顺路得到诱导表示的维数
$$
\dim \Ind H G W = [G : H] \dim W
$$

上述同构只是个线性空间同构，我们还需要明确 $G$ 应如何作用在具体记号上——方法是通过上述同构传递定义．对任意 $g \in G$，$[s] \in G/H$，张量积定义侧有 $g \cdot (s \otimes w) = gs \otimes w$，故如设 $gs$ 有 $G/H$-分解 $gs = s_{gs} h_{gs}$，则上式在具体记号侧的表现就是我们定义 $G$-作用的方法：
$$
g \cdot (s \otimes w) := s_{gs} \otimes (h_{gs} \cdot w)
$$

### 正规情形

当 $H$ 是 $G$ 的正规子群时，对任意 $h \in H$，正规性给出 $hs$ 的 $G/H$-分解 $hs = s(s^{-1}hs)$，故
$$
h \cdot (s \otimes w) = s \otimes (s^{-1}hs \cdot w)
$$
此时 $s \otimes W$ 关于 $H$-作用不变，成为一个 $H$-表示，线性同构 $\Ind H G W \cong \bigoplus_{[s] \in G/H} s \otimes W$ 升级为 $H$-表示同构
$$
\Res G H {\Ind H G W} \cong \bigoplus_{[s] \in G/H} s \otimes W
$$

:::{#rem-shs}

这是后续 [@thm-mackey-subgroup] 在正规情形的特例．[@thm-mackey-subgroup] 是对“诱导后限制”得到的表示结构的系统研究．

此外，受此启发，可考虑在任何时候都为 $s \otimes W$ 默认配备 $s H s^{-1}$-作用
$$
shs^{-1} \cdot (s \otimes w) := s \otimes (h \cdot w)
$$
此定义在 $H$ 正规时与我们刚才的推导一致．需要注意的是没有证据表明这种配备方式可以为非正规情况的线性同构 $\Ind H G W \cong \bigoplus_{[s] \in G/H} s \otimes W$ 升级结构．
:::

## 诱导表示的特征标

上节完成的关于 $G$-作用在具体记号上作用方式的分析也使我们能更轻松的从矩阵的视角观察诱导表示的作用方式，进而得到特征标的计算方法．任意固定 $G/H$ 的一组陪集代表元 $(s)_{[s] \in G/H}$，任取 $W$ 的一组线性基底 $(w_j)_{1 \leq j \leq \dim W}$，在基底 $(s \otimes w_j)_{[s] \in G/H; 1 \leq j \leq \dim W}$ 下，$G$ 在 $\Ind H G W$ 上的作用展现为每边块数量为 $[G : H]$、各块边长为 $\dim W$ 的分块矩阵．特征标是取迹，所以我们完全不关心那些 $s_{g s} \neq s$ 的偏离分块对角线的块．注意
$$
s_{gs} = s \implies H \ni h_{g s} = s_{gs}^{-1} (gs) = s^{-1} g s \implies s^{-1} g s \in H \implies gs \in sH \implies s_{gs} = s
$$
故

- $s_{gs} = s$ 与 $s^{-1} g s \in H$ 等价．

- 当 $s_{gs} = s$，$h_{g s} = s^{-1} g s$，此时 $g \cdot (s \otimes w_j) = s \otimes (s^{-1} g s \cdot w_j)$——这个块的矩阵表示由 $s^{-1} g s$ 在 $W$ 上的作用给出，算迹交给 $\chi_W$ 打包处理即可．

综上我们得到诱导表示的特征标公式
$$
\Ind H G {\chi_W} (g) = \sum_{\substack{[s] \in G/H \\ s^{-1} g s \in H}} \chi_W (s^{-1} g s)
$$

### 正规情形

特别地，当 $H$ 正规时，$s^{-1}gs \in H$ 与 $g \in H$ 等价，故上式化为
$$
\Ind H G {\chi_W} (g)
= \begin{cases}
\displaystyle \sum_{[s] \in G/H} \chi_W (s^{-1}gs) & g \in H \\
0 & g \notin H
\end{cases}
$$

## 诱导表示的不可约成分

将限制表示煞有介事的分配专有记号 $\Res G H {}$ 并和诱导表示置于同等地位，一大原因是所谓的 Frobenius 互反律

:::{#thm-frobenius-reciprocity}

## Frobenius 互反律

设 $G$ 是任意群，$k$ 是交换环，$H \leq G$ 是其子群，$V$ 是 $G$-表示，$W$ 是 $H$-表示，则
$$
\Hom_G (\Ind H G W, V) \cong \Hom_H (W, \Res G H V)
$$
在要求 $G$ 有限且 $k$ 使得群 $G$ 的表示论半单（例如特征 $0$ 的域）时有
$$
\Hom_G (V, \Ind H G W) \cong \Hom_H (\Res G H V, W)
$$
:::

:::{.remark}

抽象废话来说，第一式无非是 $2$-范畴 $\mathsf{Bimod}$ 中的一对伴随，本质是张量积的泛性质，证明几乎不需要任何 $k$ 和 $G$ 的特殊性质．第二式涉及到群代数的 Frobenius 自对偶等问题——这是额外条件的用武之地．我们不在此处展开这两个话题，请参见

- [专门文章](/posts/20260729-bimod-adjoint-frobenius)；
- [@curtis_methods_1990, {theorem 10.8, p. 232}] 一个条件宽松版本的参考；
- [@serre_linear_1977, {section 7.2, theorem 13, p. 56}] 只在有限群复数域工作．
:::

在同构两侧取维数立得特征标版本的 Frobenius 互反律
$$
\langle \Ind H G {\chi_W}, \chi_V \rangle_G = \langle \chi_W, \Res G H {\chi_V} \rangle_H
$$

:::{.remark}

第二式的特征标版本恰好是上式的对称版本，这也是 Frobenius 自对偶在特征标内积侧的一个体现．
:::

特征标版本的 Frobenius 互反律对研究诱导表示的性质很有用：例如计算诱导表示 $\Ind H G W$ 中某个不可约 $G$-表示 $V$ 出现了多少份时，可以降到 $H$-表示级别下计算 $\langle \chi_W, \Res G H {\chi_V} \rangle_H$——当然好算很多．

## 诱导表示的不可约性

下一个问题是如何判定诱导表示 $\Ind H G W$ 的不可约性．根据特征标方法，这等价于问
$$
1 = \left\langle \Ind H G {\chi_W}, \Ind H G {\chi_W} \right\rangle_G = \left\langle \chi_W, \Res G H {\Ind H G {\chi_W}} \right\rangle_H
$$
何时成立．为此有必要研究诱导后又限制回原子群后的表示 $\Res G H {\Ind H G W}$ 的性质．

:::{#thm-mackey-subgroup}

## Mackey 子群定理

$k$ 是交换环，$G$ 是有限群，$F$, $H$ 是 $G$ 的子群，$W$ 是 $H$-表示，则
$$
\Res G F {\Ind H G W} \cong \bigoplus_{[s] \in F \backslash G / H} \Ind{sHs^{-1} \cap F}{F} {\left( \Res{sHs^{-1}}{sHs^{-1} \cap F} {(s \otimes W)}\right)}
$$
这里 $F \backslash G / H$ 是全体 $(F, H)$-双边陪集，$s \otimes W$ 上配备的 $s H s^{-1}$-作用如 [@rem-shs] 所述．
:::

:::{.proof}

回忆我们建立诱导表示具体记号的步骤，这里要做的无非是更细的根据双边陪集 $F \backslash G / H$ 拆解．首先注意 $(\galg F, \galg H)$-双模分解
$$
\galg G = \bigoplus_{[s] \in F \backslash G / H} \galg{FsH}
$$
继续照抄，有 $(\galg F, k)$-双模同构
$$
\begin{aligned}
\Res G F {\Ind H G W}
&= \Res G F {\left( \galg G \otimes_{\galg H} W \right)} \\
&= \left( \bigoplus_{[s] \in F \backslash G / H} \galg{FsH} \right) \otimes_{\galg H} W \\
&\cong \bigoplus_{[s] \in F \backslash G / H} \galg{FsH} \otimes_{\galg H} W \\
g \otimes w &\mapsto f_g s_g \otimes (h_g \cdot w)
\end{aligned}
$$
这里是设上式中的 $g \in G$ 有 $F \backslash G / H$-分解 $g=f_g s_g h_g$．剩下的事情是证明 $F$-表示同构
$$
\galg{FsH} \otimes_{\galg H} W \cong \Ind{sHs^{-1} \cap F}{F} {\left( \Res{sHs^{-1}}{sHs^{-1} \cap F} {(s \otimes W)}\right)}
$$
先构造一侧的 $F$-同态
$$
\begin{aligned}
\galg F \otimes_{\galg{sHs^{-1} \cap F}} \Res{sHs^{-1}}{sHs^{-1} \cap F} {(s \otimes W)} &\to \galg{FsH} \otimes_{\galg H} W \\
f \otimes (s \otimes w) &\mapsto fs \otimes w
\end{aligned}
$$
其良定性需要我们验证一下映射和左侧 $\otimes_{\galg{sHs^{-1} \cap F}}$ 平衡关系相容：
$$
\begin{aligned}
(fshs^{-1}) \otimes (s \otimes w)
&\mapsto fsh \otimes w \\
f \otimes \left( shs^{-1} \cdot (s \otimes w) \right)
= f \otimes (s \otimes (h \cdot w))
&\mapsto fs \otimes (h \cdot w)
= fsh \otimes w
\end{aligned}
$$
再构造另一侧 $F$-同态
$$
\begin{aligned}
\galg{FsH} \otimes_{\galg H} W
&\to \galg F \otimes_{\galg{sHs^{-1} \cap F}} \Res{sHs^{-1}}{sHs^{-1} \cap F} {(s \otimes W)} \\
fsh \otimes w &\mapsto f \otimes (s \otimes (h \cdot w))
\end{aligned}
$$
继续验证良定义，首先是无关 $f$, $h$ 选取：设另有 $f'$, $h'$ 使得 $f' s h' = fsh$，则
$$
f^{-1}f' = shh'^{-1}s^{-1} \in F \cap sHs^{-1}
$$
因此
$$
\begin{aligned}
f'sh' \otimes w
&\mapsto f' \otimes (s \otimes (h' \cdot w)) \\
&= f(f^{-1}f') \otimes (s \otimes (h' \cdot w)) \\
&= f \otimes \left(f^{-1}f' \cdot (s \otimes (h' \cdot w))\right) \\
&= f \otimes \left(shh'^{-1}s^{-1} \cdot (s \otimes (h' \cdot w))\right) \\
&= f \otimes \left(s \otimes (hh'^{-1}h' \cdot w)\right) \\
&= f \otimes (s \otimes (h \cdot w)) \\
&\mapsfrom fsh \otimes w
\end{aligned}
$$
其次验证它与左侧张量积的 $\galg H$-平衡关系相容．任取 $h' \in H$，关系两侧分别被映为
$$
\begin{aligned}
(fsh)h' \otimes w
= fshh' \otimes w
&\mapsto f \otimes \left(s \otimes (hh' \cdot w)\right) \\
fsh \otimes (h' \cdot w)
&\mapsto f \otimes \left(s \otimes (h \cdot (h' \cdot w))\right) = f \otimes \left(s \otimes (hh' \cdot w)\right)
\end{aligned}
$$
所以该 $F$-同态良定．

最后，两同态在生成元上的复合分别为
$$
\begin{aligned}
f \otimes (s \otimes w)
&\mapsto fs \otimes w
\mapsto f \otimes (s \otimes w) \\
fsh \otimes w
&\mapsto f \otimes (s \otimes (h \cdot w))
\mapsto fs \otimes (h \cdot w) = fsh \otimes w
\end{aligned}
$$
因此它们互为逆映射，所需的 $F$-表示同构得证．
:::

:::{.remark}

- [@curtis_methods_1990, {chapter 1, theorem 10.13, p. 237}] 较广版本参考
- [@serre_linear_1977, {section 7.3, proposition 22, p. 58}] 如果你喜欢自然语言的浆糊证明
:::

:::{#thm-mackey-irreducibility}

## Mackey 不可约性定理

诱导表示 $\Ind H G W$ 不可约当且仅当

- $W$ 不可约；
- 对任意非平凡双边陪集 $[s] \in H \backslash G / H$，有

$$
\left\langle
\Res H {H \cap sHs^{-1}} {\chi_W},
\Res {sHs^{-1}} {H \cap sHs^{-1}} {\chi_{s \otimes W}}
\right\rangle_{H \cap sHs^{-1}} = 0
$$

换言之，$W$ 和 $s \otimes W$ 限制到 $H \cap sHs^{-1}$ 后没有公共的不可约成分．
:::

:::{.proof}

依次使用 Frobenius 互反律、[@thm-mackey-subgroup] 和各直和项上的 Frobenius 互反律，有
$$
\begin{aligned}
\left\langle \Ind H G {\chi_W}, \Ind H G {\chi_W} \right\rangle_G
&= \left\langle \chi_W, \Res G H {\Ind H G {\chi_W}} \right\rangle_H \\
&= \sum_{[s] \in H \backslash G / H}
\left\langle
\chi_W,
\Ind{H \cap sHs^{-1}}{H}
{\Res{sHs^{-1}}{H \cap sHs^{-1}}{\chi_{s \otimes W}}}
\right\rangle_H \\
&= \sum_{[s] \in H \backslash G / H}
\left\langle
\Res H {H \cap sHs^{-1}} {\chi_W},
\Res {sHs^{-1}} {H \cap sHs^{-1}} {\chi_{s \otimes W}}
\right\rangle_{H \cap sHs^{-1}}
\end{aligned}
$$
双边陪集 $[1] = H$ 对应的求和项为
$$
\left\langle \Res H H {\chi_W}, \Res H H {\chi_W} \right\rangle_H
= \left\langle \chi_W, \chi_W \right\rangle_H
$$
所有求和项都是非负整数，所以左侧等于 $1$ 当且仅当 $[1]$ 对应的求和项等于 $1$，其余项全部等于 $0$．前者等价于 $W$ 不可约，后者正是定理中的第二个条件，而左侧等于 $1$ 等价于 $\Ind H G W$ 不可约．
:::

### 正规情形

:::{#cor-mackey-irreducibility-normal}
若 $H$ 是 $G$ 的正规子群，则诱导表示 $\Ind H G W$ 不可约当且仅当 $W$ 不可约，且对任意 $s \in G \setminus H$，$H$-表示 $s \otimes W$ 与 $W$ 不同构．
:::

:::{.proof}

此时对任意 $s \in G$ 都有 $sHs^{-1} \cap H = H$．若 $W$ 不可约，则 $s \otimes W$ 也不可约，故特征标正交性给出
$$
\left\langle \chi_W, \chi_{s \otimes W} \right\rangle_H = 0
\iff s \otimes W \not\cong W
$$
代入 [@thm-mackey-irreducibility] 即得结论．
:::
