---
title: $\mathfrak{gl}_n$，幂零轨道与支配序
subtitle: 幂零锥和其上的几何：以 $\mathfrak{gl}_n$ 为例
author: sun123zxy
date: 2026-03-21
date-modified: 2026-04-06
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
  - lie

collections:
  - nilpcone

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\gl}{\mathfrak{gl}}
\renewcommand{\sl}{\mathfrak{sl}}
\newcommand{\ad}{\operatorname{ad}}
\newcommand{\Ad}{\operatorname{Ad}}
\newcommand{\rk}{\operatorname{rk}}
\newcommand{\type}{\operatorname{type}}

我们面向了解仿射簇、代数群、李代数但尚不熟练的读者，从相对具体的 $\gl_n$ 或 $\sl_n$ 切入，入门友好地为李代数上幂零锥的几何提供一些感觉．

:::{#def-irr}

不可约的拓扑空间不能以非平凡的方式写成两个闭子集或两个开子集的并．等价地，其任意非空开子集稠密．

仿射空间是配备 Zariski 拓扑的线性空间．仿射集是仿射空间的闭子集，也叫仿射簇．仿射簇的不可约性是指其作为拓扑空间的不可约性．
:::

- 李代数幂零轨道领域结束比赛的参考书 [@mcgovern_nilpotent_1993]
- 后续所用关于不可约性的纯拓扑命题，证明可见 [@specconn]

## $\gl_n$，$\GL_n$ 和共轭轨道

$\gl_n$ 是全体 $n$ 阶复方阵组成的李代数，一个 $n^2$ 维的仿射空间．不妨用 $X = (x_{ij})$ 来标识其不定元．如果你更喜欢半单李代数，$\sl_n$ 是 $\gl_n$ 的一个 $n^2-1$ 维子李代数、理想和不可约闭子簇．

:::{.remark}

## $\gl_n$ vs. $\sl_n$

$\gl_n$ 是[约化李代数（reductive Lie algebra）](https://en.wikipedia.org/wiki/Reductive_Lie_algebra)．这个概念比半单的 $\sl_n$ 稍微广一点：约化李代数是半单李代数和一个 Abel 李代数的直和．例如，$\gl_n = \sl_n \oplus \mathbb{C}$．大量半单李代数的性质都可以推广到约化李代数．
:::

行列式 $\det : \gl_n \to \mathbb{C}$ 是连续映射，定义 $\GL_n$ 是 $V$ 上的全体可逆线性变换组成的群——满足 $\det X \neq 0$ 的 $\gl_n$ 开子集．

:::{#prp-irr-of-open}

不可约空间 $X$ 的任意非空开子集 $U$ 也不可约．
:::

所以 $\GL_n$ 也不可约．

有办法把 $\GL_n$ 实现成一个真正的仿射簇：考虑 $n^2 + 1$ 维仿射空间的闭子簇 $\{(X, t) : \det X \cdot t = 1\} \subseteq \gl_n \times \mathbb{C}$．这也相当于是对 $\gl_n$ 的函数环在 $\det X$ 做局部化（得到的代数簇）．

:::{.remark}

一般地，仿射簇的主开集仍可被实现为仿射簇，其函数环由对单个函数的局部化给出．其它开集不一定能被实现为仿射簇，这类更坏的开集被称为 quasi-affine variety．
:::

那么 $\GL_n$ 现在既是个群，又是个仿射簇，群的乘法和取逆运算还都是代数的（可由多项式定义的），这使得 $\GL_n$ 成为一个仿射代数群．

考虑 $\GL_n$ 在 $\gl_n$ 上的共轭作用 $g \cdot X := g X g^{-1}$．这个作用作为 $\GL_n \times \gl_n \to \gl_n$ 的映射是代数的．考虑某元素 $X \in \gl_n$ 在共轭作用下的轨道 $\mathcal O_X$，则它是上述映射的一部分 $\GL_n \to \gl_n$ 的像．

:::{#prp-irr-image-irr}

不可约空间的在连续映射下的像也不可约．
:::

故由于 $\GL_n$ 不可约，轨道 $\mathcal O_X$ 也不可约．

:::{#prp-irr-closure}

不可约集合 $S$ 的闭包 $\overline{S}$ 也不可约．
:::

因此 $\mathcal O_X$ 的闭包 $\overline{\mathcal O_X}$ 也不可约．

## 幂零锥

考虑 $\gl_n$ 中的所有幂零矩阵的集合，我们称它为幂零锥，记作 $\mathcal N$．如果你更喜欢半单李代数，限制在 $\sl_n$ 中考虑没有区别．此时 $\mathcal N$ 就是 $\sl_n$ 的幂零锥．

:::{.remark}

## 幂零与 $\ad$-幂零

对一般的李代数，因为其上没有定义结合乘法，幂零锥定义为 $\ad$-幂零元素的集合．

- 易见约化李代数的幂零锥就是半单部分的幂零锥直和上 Abel 的部分．例如 $\mathcal N(\gl_n) = \mathcal N(\sl_n) \oplus \mathbb{C}$．

- 对半单的线性李代数来说，因为抽象 Jordan 分解和具体 Jordan 分解的一致性，$\ad$-幂零和幂零可以不做区分【TODO】．

Boilerplate？我知道我知道，抽象 Jordan 分解是个很长的故事——但 $\sl_n$ 的情形不需要这些废话：
:::

:::{.proof}

## $\sl_n$, $\gl_n$ 上的 $\ad$-幂零

回忆任意线性李代数 $\mathfrak g$ 中 $\ad$-幂零和幂零关系的基本处理方法：

- 幂零推 $\ad$-幂零是标准的左乘减右乘高次幂二项式定理论证，全球通用．

- $\ad$-幂零推幂零，设 $x \in \mathfrak g$ $\ad$-幂零，考察具体 Jordan 分解 $x = x_s + x_n$，其中 $x_s$ 半单，$x_n$ 幂零，$[x_s, x_n] = 0$．现在假定 $x_s$ 和 $x_n$ 还落在 $\mathfrak g$ 中，用 $\ad$ 线性性把此式推到 $\gl(\mathfrak g)$ 得 $\ad x = \ad x_s + \ad x_n$．取基本矩阵容易验证 $\ad x_s$ 半单；前面已经证明 $x_n$ 幂零导致 $\ad x_n$ 幂零；$\ad$ 是李代数同态保证 $[\ad x_s, \ad x_n] = \ad [x_s, x_n] = 0$．所以这是 $\ad x \in \gl(\mathfrak g)$ 的具体 Jordan 分解．由具体 Jordan 分解的唯一性和 $\ad x$ 幂零立得 $\ad x_s = 0$，即 $x_s$ 落在 $\mathfrak g$ 的中心．

可以看到唯二依赖 $\mathfrak g$ 的特殊性质的步骤是：

- 证明 $x_s$ 和 $x_n$ 落在 $\mathfrak g$ 中——这是半单李代数抽象 Jordan 分解最困难的部分之一，但在 $\sl_n$ 和 $\gl_n$ 的情形平凡．
- $x_s$ 在中心意味着什么．对半单李代数来说此即 $x_s=0$，此时我们证明了 $\ad$-幂零就是幂零；对 $\gl_n$ 来说 $x_s = \lambda I$，此时我们证明了 $\ad$-幂零的元素形如 $\lambda I + N$．注意这与我们之前讨论的约化李代数的幂零锥的构成一致．
:::

幂零性质可以转写其特征多项式满足 $\det(tI - X) = t^n$．注意特征多项式的各系数都是 $X$ 上的多项式函数，所以 $\mathcal N$ 是 $\gl_n$ 的一个闭子集．

:::{.remark}

## 一般李代数幂零锥上的几何

对一般的 $n$ 维李代数 $\mathfrak g$，固定 $\mathfrak g$ 的一组基 $(e_i)$．取每个元素 $x$ 在这组基下的坐标 $x_i$ 作为多项式的不定元，这将 $\mathfrak g$ 实现成一个 $n$ 维仿射空间．现在每个 $\ad x = \sum_i x_i \ad e_i$．注意 $\ad e_i$ 都完全由 $\mathfrak g$ 的结构决定，因此 $\ad x$ 的特征多项式的系数都是 $x_i$ 的多项式函数．这样就将一般李代数的幂零锥实现为了 $n$ 维仿射空间的一个闭子集．
:::

:::{.remark}

## 锥？

这是得名于 $\sl_2$ 幂零锥的形状．写出矩阵 $\begin{pmatrix} h & e \\ f & -h \end{pmatrix}$ 的特征多项式 $f(t) = t^2 - (h^2 + ef)$，幂零即要求 $h^2 + ef = 0$——相当经典的三维空间中的二次锥面．

我们知道锥面是正规不正则——函数环整闭但有奇点、不光滑的经典案例．所谓的 Springer correspondence 就是对幂零锥进行爆破、奇点消解、上同调等操作得到的一套系统理论．
:::

:::{#prp-irr-nilp}

$\mathcal N$ 不可约，是 $\gl_n$ 的一个闭子簇．
:::

我们作如下断言：任取一个 $\mathcal N$ 中幂零指数为 $n$ 的幂零元素 $X$，其幂零轨道 $\mathcal O_X$ 是 $\mathcal N$ 中的一个稠密开集，从而由轨道的不可约性，$\mathcal N = \overline{\mathcal O_X}$ 不可约．

要求幂零指数恰为 $n$，就是要求幂零的同时，$X^{n-1} \neq 0$．这相当于从幂零锥中挖走了一个闭集，当然剩下一个相对幂零锥的开集．至于其稠密性，在后面给出全体轨道上的几何后就会明朗．

:::{.remark}

一般来说，约化 / 半单李代数的幂零锥都不可约，是李代数的闭子簇．证明路径也是类似的：此类李代数的幂零锥中存在元素 $X$，使得其关于其 $\Ad$-群作用的幂零轨道 $\mathcal O_X$ 是幂零锥中的一个稠密开集．这种元素被称为 regular / principal nilpotent element，并有诸如中心化子维数最小等其它刻画．
:::

## 幂零轨道的支配序

Jordan 标准型理论告诉我们，$\gl_n$ 的幂零轨道完全由幂零元的 Jordan 型决定，后者与 $n$ 的整数分拆（partition）或 Young 图（Young diagram）一一对应．故以后也用 $\mathcal O_\lambda$ 的记号表示 Jordan 型为 $\lambda$ 的元素生成的幂零轨道．

:::{.remark}

## 一般半单李代数上的幂零轨道分类

Bala-Carter 定理：半单李代数 $\mathfrak g$ 上的幂零轨道与 $\mathfrak g$ 的各 Levi 子代数上的全体 distinguished nilpotent orbit 间存在一一对应．
:::

我们关心幂零轨道上的几何，例如幂零轨道的维数和闭包关系．本篇中我们先处理闭包关系．在幂零轨道上定义偏序：如果 $\mathcal O_1 \subseteq \overline{\mathcal O_2}$，就定义 $\mathcal O_1 \trianglelefteq \mathcal O_2$，称为幂零轨道上的支配序关系（dominance order．亦作闭包序，closure order）．事实上只要 $\mathcal O_1$ 的任一元素落在 $\mathcal O_2$ 的闭包里，就有 $\mathcal O_1 \subseteq \overline{\mathcal O_2}$——这是因为共轭作用作为李代数上的同胚与取闭包运算交换．

:::{.remark}

## Specialization Order

一般来讲，任何拓扑空间都可以通过取闭包包含的关系定义出一个预序（不保证反对称性的偏序关系），名曰 [specialization preorder](https://en.wikipedia.org/wiki/Specialization_preorder)．
:::

分拆上也有同名的偏序关系：如果分拆 $\lambda$ 的每个部分和（前缀和）都大于等于 $\mu$ 的对应部分和，则定义 $\lambda \trianglerighteq \mu$．支配序对应的盖住关系（covering relation）可以用 Young 图刻画：考虑 $\lambda$ 对应 Young 图中那些比下一行至少多两个方块的行，让这一行最右侧方块“掉落”到下一行．例如，$(4,2)$ 盖住 $(3,3)$ 的图示如下：
$$
\begin{array}{cccc}
\bullet & \bullet & \bullet & \boxed\bullet \\
\bullet & \bullet
\end{array}
\quad\trianglerighteq\quad
\begin{array}{ccc}
\bullet & \bullet & \bullet \\
\bullet & \bullet & \boxed\bullet
\end{array}
$$

下面的命题说明两种序其实没有区别 [@mcgovern_nilpotent_1993, {theorem 6.2.5}]：

:::{#prp-closure-dominance}

$\lambda \trianglerighteq \mu$ 当且仅当 $\mathcal O_\lambda \trianglerighteq \mathcal O_\mu$．
:::

:::{.proof}

## $\implies$ 侧证明概览

这里提供一种基于“连续路径”的证明．考虑 running example $\lambda = (4,2)$, $\mu = (3,3)$，$\lambda \trianglerighteq \mu$．如何连续地把幂零 Jordan 标准型矩阵 $J_{(4,2)}$ 变成 $J_{(3,3)}$ 呢？这样做：
$$
\begin{pmatrix}
0 & 1 &   &   &   &  \\
  & 0 & 1 &   &   &  \\
  &   & 0 &1-t&   &  \\
  &   &   & 0 &   &  \\
  &   &   &   & 0 & 1 \\
  &   &   & t & 0 & 0
\end{pmatrix}
$$
这里列出标准基底 $e_4$ 在上述矩阵多次作用下的变化情况：
$$
e_4 \longrightarrow +\left\{\begin{aligned}
t e_6 &\longrightarrow& t e_5 &\longrightarrow& 0& \\
(1-t) e_3 &\longrightarrow& (1-t) e_2 &\longrightarrow& (1-t) e_1 &\longrightarrow& 0
\end{aligned}\right.
$$
可以看到：

- 当 $t=0$ 时，就是 $J_{(4,2)}$；
- 当 $t \neq 1$ 时，Jordan 型为 $(4,2)$；
- 当 $t=1$ 时，Jordan 型突变为 $(3,3)$．

这是一条从 $\mathcal O_{(4,2)}$ 内部移动到 $\mathcal O_{(3,3)}$ 边缘的一条“连续路径”．抛开例子，上述论证对任意盖住关系都适用——只需关注 Young 图相邻两行之间的掉落，即可将这一保序映射扩展到任意 $\lambda \trianglerighteq \mu$．
:::

:::{.proof}

## $\implies$ 侧的证明

只需证明 $\lambda$ 盖住 $\mu$ 的情形，即 $\lambda$ 的 Young 图通过掉落一个方块变成 $\mu$ 的 Young 图．设是从 $\lambda$ 的第 $i$ 行掉到第 $i+1$ 行．记 $l(\lambda)$ 是 $\lambda$ 的长度，部分和 $S_i(\lambda) := \sum_{k=1}^i \lambda_k$，$J_\lambda$ 是 $\lambda$ 对应的 Jordan 标准型，$E_{i,j}$ 是基本矩阵，定义矩阵系列 $\Gamma_\lambda := \{\Gamma_\lambda(t) : t \in \mathbb{C}\}$：
$$
\Gamma_\lambda(t) := J_\lambda - t E_{ S_i(\lambda) - 1, S_i(\lambda)} + t E_{ S_{i+1}(\lambda), S_i(\lambda)}\qquad t \in \mathbb{C}
$$
它是 $\mathcal N$ 的满足多项式方程 $x_{S_i(\lambda)-1,S_i(\lambda)} + x_{S_{i+1}(\lambda),S_i(\lambda)} = 1$ 的闭子集．考察标准基 $(e_1, e_2, \dots, e_n)$ 在 $\Gamma_\lambda(t)$ 的作用下的变化情况：
$$
\begin{aligned}
\Gamma_\lambda(t) e_{S_k(\lambda) + 1} &= 0 & k = 0, 1, \dots, l(\lambda) - 1 \\
\Gamma_\lambda(t) e_{S_i(\lambda)} &= (1-t) e_{S_i(\lambda) - 1} - t e_{S_{i+1}(\lambda)} \\
\Gamma_\lambda(t) e_{s} &= e_{s-1} & \text{for all other } s
\end{aligned}
$$
只有 $e_{S_i(\lambda)}$ 的变化情况依赖于 $t$．注意 $\lambda_i \geq \lambda_{i-1}$，故

- 当 $t \neq 1$，$e_{S_i(\lambda)}$ 恰需 $\lambda_i$ 次 $\Gamma_\lambda(t)$ 作用变为 $0$．取基底
  $$
  \{ e_k \}_{1 \leq k \leq S_{i-1}(\lambda)} \sqcup \{\Gamma_\lambda(t)^k e_{S_i(\lambda)} \}_{0 \leq k < \lambda_i} \sqcup \{ e_k \}_{S_i(\lambda) < k \leq n}
  $$
  可知 $\Gamma_\lambda(t) \in \mathcal O_\lambda$．

- 当 $t=1$ 时，$e_{S_i(\lambda)}$ 恰需 $\lambda_{i+1} + 1$ 次 $\Gamma_\lambda(t)$ 作用变为 $0$，取基底
  $$
  \{ e_k \}_{1 \leq k < S_{i}(\lambda)} \sqcup \{\Gamma_\lambda(1)^k e_{S_i(\lambda)} \}_{0 \leq k \leq \lambda_{i+1}} \sqcup \{ e_k \}_{S_{i+1}(\lambda) < k \leq n}
  $$
  可知 $\Gamma_\lambda(1) \in \mathcal O_\mu$．

于是 $\Gamma_\lambda$ 只有一点不在 $\mathcal O_\lambda$ 中，$\Gamma_\lambda \cap \overline{\mathcal O_\lambda} \supseteq \overline{\Gamma_\lambda \cap \mathcal O_\lambda} = \Gamma_\lambda$，即 $\Gamma_\lambda \subseteq \overline{\mathcal O_\lambda}$．故 $\Gamma_\lambda(1) \in \overline{\mathcal O_\lambda}$，$\mathcal O_\mu \subseteq \overline{\mathcal O_\lambda}$．
:::

:::{.proof}

## $\impliedby$ 侧的证明

注意如下若干事实：

- $\lambda \trianglerighteq \mu$ 当且仅当 $\lambda^T \trianglelefteq \mu^T$ [@mcgovern_nilpotent_1993, {lemma 6.3.1}]：可以通过 Young 图的掉落操作直观感受和证明这一点．

- 秩函数具有下半连续性（lower semicontinuity）：秩不大于某数 $k$ 的矩阵是闭集．秩的子式定义可以为此提供一个一句话证明：对这些矩阵的要求等价于大于 $k$ 阶的子式全为零．更一般地，对任意 $i \in \mathbb N$，函数 $A \mapsto \rk(A^i)$ 也是下半连续的．此性质使得当我们对幂零轨道取闭包时，元素及其幂次的秩都不会增加．

- 基于秩的 Jordan 型计算：Jordan 型为 $\lambda$ 的幂零矩阵 $X$ 满足其 $i$ 次幂的秩就是 Young 图 $\lambda$ 去掉前 $i$ 列剩下的方块数：
  $$
  \rk X^i = n - \sum_{k=1}^i (\lambda^T)_k, \quad i = 0, 1, \dots
  $$
  这里 $\lambda^T$ 是分拆 $\lambda$ 的转置，即 Young 图沿主对角线的翻转．反过来这为我们提供了计算 Jordan 型的秩方法：
  $$
  (\lambda^T)_k = \rk X^{k-1} - \rk X^k, \quad k = 1, 2, \dots
  $$
  此外，$X^i$ 的 Jordan 型的转置为 $(n - \rk X^i, \rk X^i - \rk X^{i-1}, \rk X^{i+1} - \rk X^i, \dots)$．

现在设 $\overline{\mathcal O_\lambda} \supseteq \mathcal O_\mu$．不妨任取代表元 $X \in \mathcal O_\lambda$, $Y \in \mathcal O_\mu$．对任意 $i \geq 1$，由 $A \mapsto \rk(A^i)$ 的下半连续性，$\rk Y^i \leq \rk X^i$，故
$$
n - \sum_{k=1}^i (\mu^T)_k = \rk Y^i \leq \rk X^i = n - \sum_{k=1}^i (\lambda^T)_k
$$
即 $\mu^T$ 的第 $i$ 个部分和大于等于 $\lambda^T$ 的第 $i$ 个部分和，故 $\mu^T \trianglerighteq \lambda^T$，$\lambda \trianglerighteq \mu$．
:::

特别地，$\mathcal O_{(n)}$ 支配所有其它幂零轨道，故其在幂零锥中稠密．

:::{.remark}

- 注意 $\impliedby$ 侧的证明对所有经典李代数都适用．
- 关于经典李代数幂零轨道支配序历史，见 [@jantzen_nilpotent_2004, {section 13.16}]
:::