---
title: Lustig--Spaltenstein：分块幂零轨道的提升
subtitle: 幂零锥和其上的几何：以 $\mathfrak{gl}_n$ 为例
author: sun123zxy
date: 2026-04-10
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
  - lie

collections:
  - nilpcone

draft: true

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\gl}{\mathfrak{gl}}
\newcommand{\SL}{\mathrm{SL}}
\newcommand{\PSL}{\mathrm{PSL}}
\renewcommand{\sl}{\mathfrak{sl}}
\newcommand{\ad}{\operatorname{ad}}
\newcommand{\Ad}{\operatorname{Ad}}
\newcommand{\Aut}{\operatorname{Aut}}
\newcommand{\Lie}{\operatorname{Lie}}
\newcommand{\diag}{\operatorname{diag}}

本篇介绍 $\mathfrak{gl}_n$ 中的 Lustig--Spaltenstein 提升：使用分块对角幂零轨道拼出整个 $\mathfrak{gl}_n$ 中的幂零轨道．

记 $\mathfrak g := \mathfrak{gl}_n$．取定基底和（长度为 $l$ 的）分拆 $\lambda \vdash n$ 以做矩阵分块，规定 $\mathfrak{gl}_n$ 的 Levi 子李代数 $\mathfrak l$ 为全体分块对角矩阵，nilradical $\mathfrak n$ 为全体分块严格上三角矩阵．

:::{.remark}

我们称 $\mathfrak n$ 是 nilradical，是因为它是抛物子代数 $\mathfrak p$ 的 radical．$\mathfrak p$ 作为线性空间是 $\mathfrak l$ 和 $\mathfrak n$ 的直和，作为李代数 $\mathfrak p = \mathfrak l \ltimes \mathfrak n$．

回忆对一般的李代数我们都可将其拆解为半单子代数和可解理想的半直积．
:::

现在考虑幂零轨道．记 $G := \GL_n$，$L := \GL_{\lambda_1} \times \cdots \times \GL_{\lambda_l}$，$\Ad G$ 和 $\Ad L$ 是它们分别对应的共轭作用群．任取 $\mathfrak l$ 中的幂零元 $e$ 和它所在的幂零轨道 $\mathcal O_e^{\mathfrak l} := \Ad(L) \cdot e$，它的 Jordan 型由其在每个分块上的 Jordan 型 $\mu_i \vdash \lambda_i$ 决定，不妨统一考虑记 $\mu = (\mu_1, \ldots, \mu_l)$．