---
title: "对称群的复不可约表示"
author: "sun123zxy"
date: 2025/06/08
date-modified: 2026/03/21
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
  - combinatorics
collections:
  - group-rep-tour

number-sections: true

format:
  html:
    other-links:
      - text: "在知乎上阅读"
        icon: "question-circle"
        href: "https://zhuanlan.zhihu.com/p/1915153242335216846"
  pdf: default
---

\newcommand{\sgn}{\operatorname{sgn}}
\newcommand{\im}{\operatorname{im}}
\newcommand{\tr}{\operatorname{tr}}
\newcommand{\id}{\operatorname{id}}
\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\SYT}{\operatorname{SYT}}

我们简明快速地完成对称群的复不可约表示的分类．本文主要微调自 [@fulton_representation_2004, {section 4.2}]，亦少量参考 [@sagan_symmetric_2001, {chapter 2}]．推荐读者阅读前熟悉群的复表示的基本常识 [@fulton_representation_2004, {chapter 1--2}] 和群代数模的观点．

- 本文为重构版本，旧版见 [此处](old.qmd)．

## 速览

一个 Young 图由一个整数分拆 $\lambda \vdash n$ 唯一确定，一个 Young 表将一个 $n$ 元置换填入 Young 图——本质上是一对信息 $T = T_{\lambda, \sigma} := (\lambda \vdash n, \sigma \in \mathcal S_n)$．如果 $T$ 的各行各列均严格单增，则称 $T$ 是标准 Young 表，记为 $T \in \SYT(\lambda)$．

:::::{#fig-y layout-ncol="2"}

:::{#fig-yd}
$$
\begin{matrix}
\bullet & \bullet & \bullet & \bullet \\
\bullet & \bullet & \bullet \\
\bullet & \bullet
\end{matrix}
$$

形状 $\lambda = (4, 3, 2)$ 的 Young 图
:::

:::{#fig-yt}
$$
\begin{matrix}
2 & 3 & 9 & 8 \\
5 & 4 & 6 \\
7 & 1
\end{matrix}
$$

Young 表 $T = (\lambda \vdash n, \sigma \in \mathcal S_n)$，其形状为 $\lambda = (4, 3, 2)$，内容为 $\sigma=239854671$
:::

Young 图、Young 表例
:::::

置换 $g \in \mathcal S_n$ 作用在全体形状为 $\lambda$ 的 Young 表 $T$ 上的方式为将数字 $i$ 替换为 $g(i)$，即 $gT := (\lambda, g \sigma)$．易见对称群在固定形状 Young 表上的作用忠实且传递．作用在给定 Young 表 $T$ 上的效果表现为对同行元素的置换的那些置换构成的群记为 $P_T$，置换同列元素的记为 $Q_T$．易见 $P_T$ 和 $Q_T$ 交平凡，两群之并生成整个 $\mathcal S_n$．

:::{.remark}

## 置换计算速记

见[此处](/posts/20260326-cycle-notation-tech/)．
:::

来刻画不同 Young 表行、列置换之间的关系：

- $P_{gT} = g P_T g^{-1}$
- $Q_{gT} = g Q_T g^{-1}$

设 $\mathbb C[\mathcal S_n]$ 是 $S_n$ 的复群代数，即其复正则表示．定义：

- 行对称化子 $a_T := \sum_{g \in P_T} g \in \mathbb C[\mathcal S_n]$
- 列对称化子 $b_T := \sum_{g \in Q_T} \sgn(g) g \in \mathbb C[\mathcal S_n]$
- Young 对称化子 $c_T := a_T b_T$

容易验证对称化子满足如下性质：

:::{#prp-c-prop}

对任意 $p \in P_T$, $q \in Q_T$, 

- $p a_T = a_T p = a_T$
- $q b_T = b_T q = \sgn(q) b_T$
- $p c_T q = \sgn(q) c_T$

对任意 $g \in \mathcal S_n$，有：

- $a_{gT} = g a_T g^{-1}$
- $b_{gT} = g b_T g^{-1}$
- $c_{gT} = g c_T g^{-1}$
:::

Young 表 $T$ 诱导得到的 Specht 模 $V_T$ 定义为 $\mathbb C[\mathcal S_n] c_T$，于是 $\mathcal S_n$ 复不可约表示分类描述如下：

- 每个 Specht 模都是 $\mathcal S_n$ 的不可约表示
- 两个 Specht 模同构当且仅当诱导它们的 Young 表具有相同的形状
- $\mathcal S_n$ 的每个不可约表示都同构于某一 Specht 模

## Schur 引理与正交关系

我们关心的所有 Specht 模的性质可以紧凑地写为如下命题：

:::{#thm-specht-hom}

设 $T,S$ 是大小均为 $n$ 的 Young 表，则 Specht 模 $V_T, V_S$ 间的全体 $\mathbb C[\mathcal S_n]$-同态 $\Hom_{\mathcal S_n} (V_T, V_S)$ 维数为 $1$ 当且仅当 Young 表 $T$, $S$ 形状相同，否则为 $0$．
:::

即要求我们验证 Specht 模们满足 Schur 引理和特征标的正交关系——根据有限群表示论的基本结果，这将自动导出每个 Specht 特征标的不可约性和它们之间的同构情况．再利用对称群的共轭类数等于整数分拆数等于 Young 表形状数的事实，我们就完成了 $\mathcal S_n$ 的复不可约表示的分类．

注意特征标内积是对称的，所以每对无序 Young 表只需要计算一次维数即可．

## Hom 的新刻画

假定我们已经证明 $c_T$ 是 $\mathbb C[\mathcal S_n]$ 中的幂等元（或其常数倍），则上述 Hom 空间有更好的刻画：

:::{#prp-hom-iso}

作为 $\mathbb C$-线性空间：
$$
\Hom_{\mathcal S_n} (V_T, V_S) \cong c_T \mathbb C[\mathcal S_n] c_S
$$
:::

这一结果由如下一般的命题提供：

:::{#prp-hom-idem}

对任意含幺环 $R$，$R$-模 $M$ 和幂等元 $e \in R$，我们有典范的 $Z_R(e)$-模同构
$$
\begin{aligned}
e M &\cong \Hom_R(Re, M) \\
e m &\mapsto (re \mapsto rem)
\end{aligned}
$$
这里 $Z_R(e)$ 是环 $R$ 中所有与 $e$ 交换的元素构成的子环．
:::

:::{.proof}

这是因为每个 $R e \to M$ 的 $R$-同态 $\varphi$ 都由 $e \mapsto \varphi(e)$ 唯一确定，且 $\varphi(e) = \varphi (e^2) = e \varphi(e) \in e M$．至于模结构，$\Hom_R(Re, M)$ 的模结构取决于 $Re$ 的右模结构，故 $Z_R(e)$ 是自然的选择，验证不难．
:::

于是如果**暂时先承认** $c_T$ 是 $\mathbb C[\mathcal S_n]$ 中的幂等元（或其常数倍），则作为 $\mathbb C$-线性空间，
$$
\Hom_{\mathcal S_n}(V_T, V_S) = \Hom_{\mathcal S_n}(\mathbb C[\mathcal S_n] c_T, \mathbb C[\mathcal S_n] c_S) \cong c_T \mathbb C[\mathcal S_n] c_S
$$

根据上述讨论，接下来的首要任务是研究 $c_T$ 的幂等性和 $c_T \mathbb C[\mathcal S_n] c_S$ 的维数．注意 $c_T = a_T b_T$ 且 $c_T x c_S = a_T (b_T x a_S) b_S$，故两个问题都需要我们更详细地研究 $a_T x b_S$ 的性质——更一般地，满足对任意 $p \in P_T$, $q \in Q_S$ 成立 $p x q = \sgn(q) x$ 的元素 $x \in \mathbb C[\mathcal S_n]$ 的性质．

## 同形状的情形

首先介绍一个必要的组合结果．

:::{#prp-srdc}

## 同形状 Young 表的 S.R.D.C.^[Same row, different column]

设 $T, S = gT$ 是形状为 $\lambda$ 的两个 Young 表，则以下条件等价：

1. 任意一对 $T$ 中同行的数字均落在 $S$ 中的不同列．即不存在对换 $(i,j) \in P_T \cap Q_S = P_T \cap g Q_T g^{-1}$．

2. 存在 $p \in P_T,q' \in Q_S$ 使得 $pT = q'S$

3. 存在 $p \in P_T$, $q \in Q_T$ 使得 $g = pq$
:::

:::{.proof}

**(1) => (2):** 如图所示，将 $T$ 中第一行全体元素取出，其在 $S$ 中的对应元素必然在不同列．因此，可以通过 $S$ 上的列置换将其移至 $S$ 的第一行．随后对 $T$ 的第一行元素做行置换即可使得 $T$ 的第一行与 $S$ 的第一行相同．顺次对第二行，第三行完成上述操作即可．
$$
\begin{matrix}
T &
\begin{matrix}
i & j & k & l \\
* & * & * \\
* & *
\end{matrix}
& \xrightarrow{p_1 \in P_T} &
\begin{matrix}
l & k & i & j \\
* & * & * \\
* & *
\end{matrix}
& \xrightarrow{p_2 \in P_T} & \dots
\\
\\
S &
\begin{matrix}
l & * & * & j \\
* & * & i \\
* & k
\end{matrix}
& \xrightarrow{q'_1 \in Q_S} &
\begin{matrix}
l & k & i & j \\
* & * & * \\
* & *
\end{matrix}
& \xrightarrow{q'_2 \in Q_S} & \dots
\end{matrix}
$$

**(2) => (3):** 设 $q' = g q g^{-1}$，其中 $q \in Q_T$．则 $pT = q'S = (g q g^{-1}) (gT) = gq T$，即 $p = gq$ 或 $g = p q^{-1}$．

**(3) => (1):** 考虑 $T$ 中的某一行的数字．$q$ 对 $T$ 的作用将它们上下平移．$p$ 对 $qT$ 的作用再对它们做一个内部的置换．操作结束后，它们仍在不同列．
:::

:::{.remark}

值得一提，$P_T$, $Q_T$ 并不互相交换，二者的乘积也不构成群．
:::

:::{#prp-c-unique}

## Young 对称化子的唯一性

设 $c \in \mathbb C[\mathcal S_n]$ 满足对任意 $p \in P_T$, $q \in Q_T$，有 $p c q = \sgn(q) c$，则 $c \in \mathbb C c_T$，即 $c$ 在模掉标量乘法意义下唯一．
:::

:::{.proof}

不妨设 $c = \sum_{g \in \mathcal S_n} n_g g$ 是满足对任意 $p \in P_T$, $q \in Q_T$，有 $p c q = \sgn(q) c$ 的某一 $\mathbb C[\mathcal S_n]$ 中元素．对此式对比系数立得 $n_{pgq} = \sgn(q) n_g$．

注意我们已经知道满足这条件的 Young 对称化子
$$
c_T = a_T b_T = \sum_{p \in P_T} \sum_{Q \in Q_T} \sgn(q) pq
$$
所以我们应当指望，也只需证明如下两个事实：

- 对任意 $p \in P_T$, $q \in Q_T$，$n_{pq} = \sgn(q)$ 乘上某个常数．

特取 $g=1$ 得 $n_{pq} = \sgn(q) n_1$，相对 $n_1$ 唯一．

- 对所有 $g \notin P_T Q_T$，有 $n_g = 0$ 成立．

由 [@prp-srdc]，此时存在对换 $p := (i,j) \in P_T \cap Q_S = P_T \cap g Q_T g^{-1}$．于是可取对换 $q := g^{-1} p g \in Q_T$，这样就有
$$
n_g = n_{pg(g^{-1}pg)} = n_{pgq} = \sgn(q) n_g = - n_g
$$
因此 $n_g = 0$．
:::

:::{#cor-cxc}

$a_T x b_T \in \mathbb C c_T$ 对任意 $x \in \mathbb C[\mathcal S_n]$ 成立．特别地，$c_T^2 = \alpha c_T$，这里幂等系数 $\alpha = n! / \dim V_T$．
:::

:::{.proof}

只需计算 $\alpha$．考察右乘线性变换
$$
\begin{aligned}
\mathbb C[\mathcal S_n] &\to V_T \\
x &\mapsto x c_T
\end{aligned}
$$
已经知道它是投影变换的非零常数倍，因此这线性变换的迹 $\tr (x \mapsto c_T x) = \alpha \dim V_T$．考察 $c_T g = a_T b_T g$ 的 $g$ 分量对应系数，注意 $P_T$ 和 $Q_T$ 交平凡，故此系数为 $1$，于是 $\tr (x \mapsto c_T x) = n!$，因此 $\alpha = n! / \dim V_T$．
:::

:::{#cor-cxc-dim}

对同形状 Young 表 $T$, $S$，$\dim c_T \mathbb C[\mathcal S_n] c_S = 1$．
:::

:::{.proof}

设 $S = gT$，则 $c_T \mathbb C[\mathcal S_n] c_S = c_T \mathbb C[\mathcal S_n] c_T g^{-1}$，因此只需考察 $c_T \mathbb C[\mathcal S_n] c_T$ 的维数．这由 [@cor-cxc] 保证．
:::

## 不同形状的情形

受之前 [@prp-srdc] 刻画同形状 Young 表间群作用关系的启发，我们可能也需要从组合上对 Young 表形状不同一事做一点文章．

在分拆上定义一个偏序 $\trianglelefteq$：$\lambda \trianglelefteq \mu$ 当且仅当 $\lambda$ 的每个前缀和都小于等于 $\mu$ 的对应前缀和．注意字典序 $\leq$ 是 $\trianglelefteq$ 的一个细化版本．

下设 $T,S$ 为形状分别为 $\lambda, \mu \vdash n$ 的 Young 表．

:::{#prp-srdc-diff}

## 不同形状 Young 表的 S.R.D.C.

1. 若任意一对 $T$ 中同行的数字均落在 $S$ 中的不同列，则 $\lambda \trianglerighteq \mu$．

2. 若 $\lambda \not \trianglerighteq \mu$，则存在一对互异数字 $(i,j)$ 既落在 $T$ 中同一行，也落在 $S$ 中同一列．即存在对换 $(i,j) \in P_T \cap Q_S$．

3. 若 $\lambda \not \trianglerighteq \mu$，则对任意 $g \in \mathcal S_n$，存在对换 $(i,j) \in P_T \cap Q_{gS} = P_T \cap g Q_S g^{-1}$．
:::

:::{.proof}

上述命题中，(2) 是 (1) 的逆否命题，在 (2) 中取新的 $S$ 为 $gS$ 即可得 (3)，故只需证明 (1)．这是因为可以使用与 [@prp-srdc] 类似的方法，在对 $T$ 做行置换和对 $S$ 做列置换后，确保对每个 $i$，$T$ 的前 $i$ 行元素都落在 $S$ 的前 $i$ 行．数数就得到 $\lambda \trianglerighteq \mu$．详细证明可参考 [@sagan_symmetric_2001, {lemma 2.2.4}]．
:::

:::{#prp-axb}

若 $\lambda \not \trianglerighteq \mu$，则不存在非零元 $c \in \mathbb C[\mathcal S_n]$ 使得 $p c q = \sgn(q) c$ 对任意 $p \in P_T$, $q \in Q_S$ 成立．
:::

:::{.proof}

设 $c = \sum_{g \in \mathcal S_n} n_g g$，对比系数仍有 $n_{pgq} = \sgn(q) n_g$．用 [@prp-srdc-diff]，取 $p = (i,j)$, $q = g^{-1} p g$ 就有
$$
n_g = n_{pg(g^{-1}pg)} = n_{pgq} = \sgn(q) n_g = - n_g
$$
因此 $n_g = 0$ 对任意 $g$ 成立．
:::

:::{#cor-cxc-diff-dim}

若 $\lambda \not \trianglerighteq \mu$（或更特殊地，$\lambda < \mu$），则 $a_T \mathbb C[\mathcal S_n] b_S = 0$．特别地，$\dim c_T \mathbb C[\mathcal S_n] c_S = 0$．
:::

综上，我们完成了 $\mathcal S_n$ 的复不可约表示的分类：它们恰为全体 Specht 模 $V_T$，其中 $T$ 是形状为 $\lambda \vdash n$ 的 Young 表．两个 Specht 模同构当且仅当诱导它们的 Young 表具有相同的形状．

## 双边理想分解

注意任何同形状 Young 表 $T$ $S :=gT$ 的 Specht 模 $V_T$ 和 $V_S$ 间有典范表示同构 $x c_T \mapsto x c_T g^{-1}$，故 $\mathbb C[\mathcal S_n]$ 至少有如下双边理想分解：
$$
\mathbb C[\mathcal S_n] = \bigoplus_{\lambda \vdash n} \mathbb C[\mathcal S_n] c_{\lambda} \mathbb C[\mathcal S_n]
$$
这里 $c_{\lambda}$ 是任意一个形状为 $\lambda$ 的 Young 表的 Young 对称化子．

:::{.remark}

这是 [Peter--Weyl 定理](/posts/20260314-group-rep-peter-weyl/) / Wedderburn--Artin 定理在 $\mathcal S_n$ 上的一个具体实例．

也长得很像 Bruhat 分解
$$
\operatorname{GL}_n = \bigsqcup_{w \in \mathcal S_n} B w B
$$
:::

## 自对偶

$\mathcal S_n$ 表示论的一个重要结果是所有 $\mathcal S_n$ 的表示都是自对偶的，即对任意 $\mathcal S_n$ 的表示 $V$，有
$$
V \cong V^*
$$
这同构有两种理解方式：

- 作为左模的同构：$V$ 上左作用 $g \cdot v$ 自然，$V^*$ 上配备 $(\sigma \cdot f)(v) := f(\sigma^{-1} \cdot v)$．
- 作为右模的同构：$V$ 上右作用 $v \cdot \sigma := \sigma^{-1} \cdot v$，$V^*$ 上右作用 $(f \cdot \sigma)(v) := f(\sigma \cdot v)$ 自然．

两侧是对偶的，只需证明一侧．可以考虑特征标：$\mathcal S_n$ 的共轭类由置换的轮换型给出，而 $\sigma$ 和 $\sigma^{-1}$ 有相同轮换型，故在同一共轭类，故 $V$ 和 $V^*$ 的特征标相同，进而同构．

:::{.remark}

## 自对偶、特征标与双线性型

一般来说：

- 有限群复表示自对偶当且仅当特征标是实函数
- 自对偶相当于保证 $V$ 上有一个非退化的 $\mathcal S_n$-不变双线性型
- 群代数上总有标准的非退化 $G$-不变双线性型，从而自对偶

一般来说，怎样显式构造这个双线性型呢？

可以考虑随意取一 $V$ 上双线性型做平均化得到不变双线性型．如果 $V$ 不可约，Schur 引理保证平均化后的双线性型要么是零，要么非退化．于是可以取 $V^*$ 一组基底 $(f_i)$ 并遍历 $f_i \otimes f_j$ 实验平均化后是否非退化．对可约的情况，可以分解成不可约成分后做．
:::

## Garnir 关系与 Specht 模的基底

我们为每个 Specht 模构造一个显式基底．因为同形状 Young 表诱导的 Specht 模之间有典范同构，可以只研究最标准的那个从左到右，从上到下标号的 Young 表 $T_{\lambda, \id}$ 诱导的 Specht 模．以后在无歧义的情况下，直接用 $\lambda$ 来代指此这个最标准的 Young 表．

:::{#thm-basis}

$V_\lambda$ 的一组基底为 $\{ g c_\lambda : T_{\lambda, g} \in \SYT(\lambda) \}$，即 $g$ 取遍所有标准 Young 表对应的置换．
:::

对任意 $g \in \mathcal S_n$，我们尝试将 $g c_\lambda$ 写成上述基底的线性组合．首先可以对 $g$ 右乘 $P_\lambda$ 元素而保持 $g c_\lambda$ 不变，故问题约化为 $g$ 对应 Young 表已经按行升序排列的情形．

如果 $g$ 已经对应标准 Young 表，则没有需要做的事情．否则，必然两个同列、相邻行的位置对满足靠上的数字大于靠下的数字．不妨设它们分别是第 $i$ 行第 $j$ 列的 $r$ 和第 $i+1$ 行第 $j$ 列的 $s$：
$$
\begin{matrix}
  &   &   &   & r & < & * & < & * \\
  &   &   &   & \lor &   &   &   & \\
* & < & * & < & s &   &   &   & 
\end{matrix}
$$

TODO: this part is under construction

## 附录 {.appendix .unnumbered}

:::{#exr-1}

- 证明通过相邻数字对换操作足以沟通所有标准 Young 表．
- 证明 Specht 模的维数为其对应 Young 图对应标准 Young 表数量，一组显式基底为 $\{g c_T\}$，其中 $g$ 取遍所有标准 Young 表对应的置换．
- 确定具体对哪些 $g \in \mathcal S_n$，作为 $\mathbb C[\mathcal S_n]$ 的子模有 $V_T = V_{gT}$．
:::

:::{.remark}

## 关于使用到的复数域 $\mathbb C$ 的特殊性质

- 我们使用了 $\mathbb C$ 特征不整除 $n!$ 导致的群代数 $\mathbb C[\mathcal S_n]$ 的半单性．
- 我们使用了群的复不可约表示数量等于群的共轭类的数量的结果．
- 其它论证没有用到 $\mathbb C$ 的特殊性质．
:::

:::{.remark}

## 关于对称化子的组合看法

$P_T$ 中的元素在左作用到 $g \in \mathcal S_n$ 时，是对 $T$ 中同行的数字做字面上的数字置换；在右作用时是将 $\sigma$（从左到右，从上到下）排入 $T$ 后做其上的行置换．$Q_T$ 同理．

$\mathbb C[\mathcal S_n]$ 可以看作 $\mathcal S_n \to \mathbb C$ 的函数空间，配备双边群作用 $(g_1 \cdot \chi \cdot g_2)(h) = \chi(g_1^{-1} g g_2^{-1})$．

- $a_T \mathbb C[\mathcal S_n]$ 中的函数，交换两个出现在 $T$ 中同行的数字，函数值不变；
- $\mathbb C[\mathcal S_n] b_T$ 中的函数，交换 $T$ 中同列的两个位置，改变符号．
- $a_T \mathbb C[\mathcal S_n] b_T$ 中的函数同时满足以上两条性质．

其它经典的组合看法还有关于 $a_T \mathbb C[\mathcal S_n]$ 是“tabloid”的看法 [@sagan_symmetric_2001, {Definition 2.1.4}]，是诱导表示 $1\uparrow_{P_T}^{\mathcal S_n}$ 的看法等．
:::

::: {.remark .hidden}

## 关于 $P_T Q_T \cap Q_T P_T$ 的一个错误猜想，已隐藏

$\alpha$ 也应等于 $c_T^2$ 在单位元处的系数
$$
[\id_{\mathcal S_n}] c_T^2 = \sum_{\substack{p_1,p_2 \in P_T \\ q_1, q_2 \in Q_T \\ p_1 q_1 p_2 q_2 = \id_{\mathcal S_n}}} \sgn(q_1) \sgn(q_2) 
$$

猜想求和中的每一项都满足 $\sgn(q_1) = \sgn(q_2)$，这样就有
$$
\alpha = |P_T Q_T \cap Q_T P_T|
$$
然而这并不正确．使用如下 Sage 代码可以验证：

```python
# Define the symmetric group
S = SymmetricGroup(8)

"""
1 2 3
4 5 6
7 8
"""

P_gens = [S((1,2)), S((2,3)),
          S((4,5)), S((5,6)),
          S((7,8))]
Q_gens = [S((1,4)),S((4,7)),
          S((2,5)),S((5,8)),
          S((3,6))]

# Create the subgroups P and Q
P = S.subgroup(P_gens)
Q = S.subgroup(Q_gens)

print("P", len(P))
print("Q", len(Q))

PQ = Set([p * q for p in P for q in Q])
QP = Set([q * p for q in Q for p in P])

print("PQ:", len(PQ))
print("QP:", len(QP))

# Compute the intersection of P and Q
cap = PQ.intersection(QP)

# Display the intersection
print("PQ cap QP:", len(cap))
```
:::