---
title: 经典李代数中的幂零轨道：分类
date: 2026-05-09
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
  - lie

collections:
  - nilpcone

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\gl}{\mathfrak{gl}}
\newcommand{\SL}{\mathrm{SL}}
\newcommand{\PSL}{\mathrm{PSL}}
\renewcommand{\sl}{\mathfrak{sl}}
\newcommand{\SO}{\operatorname{SO}}
\newcommand{\so}{\mathfrak{so}}
\newcommand{\Sp}{\operatorname{Sp}}
\renewcommand{\sp}{\mathfrak{sp}}
\newcommand{\ad}{\operatorname{ad}}
\newcommand{\Ad}{\operatorname{Ad}}
\newcommand{\Aut}{\operatorname{Aut}}
\newcommand{\Lie}{\operatorname{Lie}}
\newcommand{\diag}{\operatorname{diag}}
\newcommand{\antidiag}{\operatorname{antidiag}}
\newcommand{\Sym}{\operatorname{Sym}}
\newcommand{\Alt}{\operatorname{Alt}}
\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\End}{\operatorname{End}}
\newcommand{\Tr}{\operatorname{Tr}}

设 $V$ 是 $n$ 维线性空间．所谓经典李代数，即是单李代数中寄居在线性李代数 $\gl(V)$ 中的：

- A 型李代数：即特殊线性李代数 $\sl(V) := \{X \in \gl(V) : \Tr X = 0\}$，$A_n$ 型对应 $\dim V = n+1$．
- C 型李代数：即辛李代数 $\sp(V)$，$C_n$ 型对应 $\dim V = 2n$．
- B 型和 D 型李代数：即正交李代数 $\so(V)$，$B_n$ 型对应 $\dim V = 2n+1$，$D_n$ 型对应 $\dim V = 2n$．

所谓幂零轨道，是取适当作用群 $G$ 在李代数 $\mathfrak g$ 上的共轭作用下的幂零元素的轨道．在经典李代数的情形，所有经典李代数的作用群都可以取 $\GL(V)$；$\sl(V)$ 的作用群可以取 $\SL(V)$；$\so(V)$ 的作用群可以取特殊正交群 $\SO(V)$ 或正交群 $O(V)$；$\sp(V)$ 的作用群可以取 $\Sp(V)$．不同作用群的选择可能导致粒度不同的分类结果．注意 A 型 $\sl(V)$ 的幂零轨道已经由 Jordan 型（即分拆）分类，故本章主要关心 B、C、D 型，即 $\so(V)$ 和 $\sp(V)$ 中的幂零轨道分类情况．

我们主要跟随 [@jantzen_nilpotent_2004, {section 1}] 的呈现．主要的不同是，我们在 [@sec-jacobson-morozov-classical] 介绍了幂零轨道分类的结果和 Jacobson--Morozov 定理的联系，并借此在 [@sec-rep-theory-orbit-classification] 提供了幂零轨道分类的另一表示论风格的简明证明．

除明确说明外，本章默认在复数域 $\mathbb C$ 上工作；为表示区分，本章中，在给定一组基的前提下，线性变换对应的矩阵通常使用其对应正体大写字母表示，例如 $X \in \gl(V)$ 在某组基下的矩阵记为 $\mathrm X$．

## 正交群及其斜自伴李代数

先在 $\mathbb C$ 上有限维线性空间 $V$ 上确定一个非退化双线性型 $\varphi(-,-)$ 明确正交群及其斜自伴李代数的定义．

### 非退化双线性型

设 $\varphi(-,-)$ 为 $V$ 上的非退化双线性型——非退化是指左根（或 / 且右根）为零，等价于 $\varphi$ 作为 $V \to V^*$ 的线性映射可逆．对任意线性变换 $X \in \gl(V)$，规定 $X^*$ 为满足 $\varphi(Xv, w) = \varphi(v, X^*w)$ 的唯一映射，抽象地来说是对偶空间 $V^*$ 上的对偶映射通过非退化双线性型拉回到 $V$ 上的结果．定义正交群 $G$ 和斜自伴李代数 $\mathfrak{g}$ 如下：
$$
G := O(V, \varphi) := \{X \in \GL(V) : \varphi(Xv, Xw) = \varphi(v, w)\} = \{X \in \GL(V) : X^* = X^{-1}\}
$$
$$
\mathfrak g := \mathfrak o(V, \varphi) := \{X \in \gl(V) : \varphi(Xv, w) = -\varphi(v, Xw)\} = \{X \in \gl(V) : X^* = -X\}
$$
因此 $G$ 和 $\mathfrak{g}$ 是它们各自在其代数结构的对极映射下不变的元素全体．

:::{.remark}

## 矩阵记号

在选定基底后，使用矩阵记号会为计算带来便利．设 $\Phi$ 是双线性型 $\varphi$ 在该基下的 Gram 矩阵，则 $\varphi(v, w) = v^T \Phi w$，非退化意味着 $\Phi$ 可逆．伴随算子 $\mathrm X^*$、正交群 $G$ 和斜自伴李代数 $\mathfrak{g}$ 的定义可以用矩阵记号重写为：
$$
\begin{aligned}
\mathrm X^* &:= \Phi^{-1} \mathrm X^T \Phi \\
G &= \{\mathrm X \in \GL_n : \mathrm X^T \Phi \mathrm X = \Phi\} = \{ \mathrm X \in \GL_n : \mathrm X^* = \mathrm X^{-1} \} \\
\mathfrak g &= \{\mathrm X \in \gl_n : \mathrm X^T \Phi = - \Phi \mathrm X \} = \{\mathrm X \in \gl_n : \mathrm X^* = -\mathrm X\}
\end{aligned}
$$
:::

:::{.remark}

## 表示论观点

若将 $\varphi$ 视为 $V \to V^*$ 的线性映射，则

- $\varphi$ 是群表示意义下的 $G$-模同态，且 $G$ 是使得 $\varphi$ 成为 $G$-模同态的最大的 $\GL(V)$ 的子群．
- $\varphi$ 是李代数表示意义下的 $\mathfrak{g}$-模同态，且 $\mathfrak{g}$ 是使得 $\varphi$ 成为 $\mathfrak g$-模同态的最大的 $\gl(V)$ 的子李代数．我们写作 $\varphi \in \Hom_{\mathfrak g}(V, V^*)$，或等价地 $\varphi \in (V^* \otimes V^*)^{\mathfrak g}$，这里 $(V^* \otimes V^*)^{\mathfrak g}$ 是 $V^* \otimes V^*$ 中全体被 $\mathfrak g$-作用消灭的元素全体．
:::

将来只关心两类特殊的非退化双线性型：对称的 $\varphi(v, w) = \varphi(w, v)$ 和斜对称的 $\varphi(v, w) = -\varphi(w, v)$．前者对应正交群 $O(V, \varphi)$ 及其斜自伴李代数 $\so(V, \varphi)$，后者对应辛群 $\Sp(V, \varphi)$ 及其斜自伴李代数 $\sp(V, \varphi)$．不过在此之前，可以对一般的非退化双线性型做一点讨论：

:::{#prp-bilinear-prop}

对任何域上有限维线性空间 $V$ 及其子空间 $U$：

- 定义消灭子 $U^0 := \{f \in V^* : f(U) = 0\}$．它是 $U \to V$ 嵌入的对偶映射 $V^* \to U^*$ 的核．$\dim U^0 = \dim V - \dim U$．

对任意 $V$ 上双线性型 $\varphi(-,-)$： 

- 它可通过 $\varphi: v \mapsto \varphi(v, -)$ 看成 $V \to V^*$ 的线性映射．

- 定义正交补 $U^\perp := \varphi^{-1}(U^0)$．等价地 $U^\perp = \{v \in V : \varphi(v, u) = 0,\, \forall u \in U\}$．

当 $\varphi$ 非退化时：

- $\dim U^\perp = \dim U^0$，$\dim U + \dim U^\perp = \dim V$．
:::

读者依序自证不难．更精炼地有如下正合列交换图：

:::{#fig-bilinear-prop}

```{tikz}
\begin{tikzcd}
	0 & U & V & {V/U} & 0 \\
	0 & {U^*} & {V^*} & {U^0} & 0
	\arrow[from=1-1, to=1-2]
	\arrow["\iota", from=1-2, to=1-3]
	\arrow["\varphi"', from=1-2, to=2-2]
	\arrow[from=1-3, to=1-4]
	\arrow["\varphi", from=1-3, to=2-3]
	\arrow[from=1-4, to=1-5]
	\arrow[from=2-2, to=2-1]
	\arrow["{\iota^*}", from=2-3, to=2-2]
	\arrow[from=2-4, to=2-3]
	\arrow[from=2-5, to=2-4]
\end{tikzcd}
```
:::

### 对称与斜对称双线性型的结构

:::{#prp-sym-diag}

## 对称情形

在特征非二的域上：

- 若对称双线性型 $\varphi(-,-)$ 非零，则一定有 $v \in V$ 使得 $\varphi(v, v) \neq 0$．

- 对称双线性型 $\varphi(-,-)$ 都可以通过适当选取基底化为对角型．

在 $\mathbb C$ 上：

- 进而由 $\mathbb C$ 上每个元素都有平方根，对称双线性型完全由 $\varphi$ 的秩来分类．特别地，对非退化对称双线性型 $\varphi$，可选取基底使其在该基下的矩阵为单位矩阵．
:::

:::{.proof}

- 否则
  $$
  \varphi(v+w, v+w) = \varphi(v, v) + \varphi(w, w) + \varphi(v, w) + \varphi(w, v) = 0
  $$
  结合对称性和特征非二的假设，将得到 $\varphi(v, w) = 0$ 对任意 $v, w$ 成立，与 $\varphi$ 非零矛盾．

- 归纳，取出上述 $v \in V$ 作为首个基底．考虑其正交补空间，其维数为 $\dim V - 1$．对此空间重复上述过程，最终得到一个基底使得 $\varphi$ 的矩阵为对角型．

- 平凡．
:::

:::{#prp-alt-standard}

## 斜对称情形

在特征非二的域上：

- 若斜对称双线性型 $\varphi(-,-)$ 非零，则总存在一对线性无关向量 $v, w \in V$ 使得 $\varphi(v, w) \neq 0$．

- $V$ 可正交分解为一系列一维和二维子空间的直和：$\varphi$ 在每个一维子空间上为零，在每个二维子空间上存在基底使得 $\varphi$ 的矩阵为 $\begin{pmatrix} 0 & a \\ -a & 0 \end{pmatrix}$．

在 $\mathbb C$ 上：

- 上述 $a$ 都可以化为 $1$．斜对称双线性型完全由一维和二维子空间的数量来分类．特别地，对非退化斜对称双线性型 $\varphi$，可选取基底使其在该基下的矩阵为 $\begin{pmatrix} 0 & I_n \\ -I_n & 0 \end{pmatrix}$．
:::

:::{.proof}

- 注意斜对称使得所有向量 $v$ 都有 $\varphi(v, v) = 0$，因此 $\varphi$ 非零保证了存在 $v, w$ 使得 $\varphi(v, w) \neq 0$．

- 考虑 $v$ 的正交补空间 $v^\perp$，其维数为 $\dim V - 1$，$v \in v^\perp$ 且 $w \notin v^\perp$．类似性质也对 $w^\perp$ 成立．因此 $v^\perp \cap w^\perp$ 与 $v$, $w$ 正交且维数为 $\dim V - 2$．对 $v^\perp \cap w^\perp$ 重复上述过程即可．

- 平凡．
:::

:::{.remark}

## 其它域上的对称和斜对称双线性型分类

在其它域上对对称和斜对称双线性型做具体分类会更加复杂．当然，通用的第一步约化是，对角线或二维子空间的变量只需在商掉平方数的 $F^{\times} / (F^{\times})^2$ 中考虑．

- 惯性定理告诉我们 $\mathbb R$ 上的对称双线性型完全由秩和正负惯性指数分类．

- $\mathbb Q$ 上对称双线性型（二次型）的分类是经典代数数论主题．Hasse--Minkowski 定理将其分类问题化归到局部域 $\mathbb R$ 或 $\mathbb Q_p$ 上分类，后者的分类由秩、判别式和 Hilbert 符号决定．参见 [@serre_course_1973] 及其[导读](/posts/20250416-q-quadratic-form-classification/)．

- 针对一般对称双线性型的分类，[Witt 定理系列](https://en.wikipedia.org/wiki/Witt%27s_theorem)为我们提供了一些分解的工具．
:::

## 约化到 Jordan 型 {#sec-reduction-to-jordan}

以下定理保证正交群 $G$ 作用下斜自伴李代数 $\mathfrak g$ 共轭轨道和在 $\GL(V)$ 作用下的共轭轨道分类情况一致：

:::{#thm-orbit-by-gl}

设 $V$ 是 $n$ 维线性空间，$\varphi$ 是 $V$ 上的非退化双线性型，$G = O(V, \varphi)$ 是正交群，$\mathfrak g = \mathfrak o(V, \varphi)$ 是斜自伴李代数．若 $X, Y \in \mathfrak{g}$，则 $X$ 与 $Y$ 在 $G$ 下共轭当且仅当在 $\GL(V)$ 下共轭．
:::

:::{.proof}

设存在 $g \in \GL(V)$ 使得 $gXg^{-1} = Y$．目标是调整 $g$ 使得它满足 $g^* g = 1$ 落入 $G$ 的同时仍然保持 $gXg^{-1} = Y$．

对 $gXg^{-1} = Y$ 两边取 $\varphi$-伴随得 $(g^{-1})^* X^* g^* = Y^*$，即 $(g^*)^{-1} X^* g^* = Y^*$．又因为 $X, Y \in \mathfrak{g}$ 即 $X^* = -X$、$Y^* = -Y$，所以 $(g^*)^{-1} X g^* = Y$．联立两式推出 $g^*g$ 与 $X$ 可交换，同时注意 $g^* g \in G$．

现在做断言：存在多项式 $p(t) \in \mathbb{C}[t]$ 使得 $h := p(g^*g)$ 满足 $h^2 = g^*g$．于是 $h$ 满足以下三个条件：

- $h \in \GL(V)$：因为 $h^2 = g^*g$ 可逆．
- $h = h^*$：因为他是自伴的 $g^*g$ 的多项式．
- $h$ 与 $X$ 可交换：因为 $h$ 是 $g^*g$ 的多项式，故和 $g^* g$ 交换，进而和 $X$ 可交换．

现在考虑 $gh^{-1}$，断言它就是我们所求：

- $gh^{-1} \in G$: $(gh^{-1})^* (gh^{-1}) = (h^*)^{-1} (g^* g) h^{-1} = h^{-1} (g^* g) h^{-1} = 1$
- $(gh^{-1}) X (gh^{-1})^{-1} = g h^{-1} X h g^{-1} = g X g^{-1}$，最后一步使用了 $h$ 与 $X$ 交换．

关于断言的证明见下面的引理．
:::

:::{#lem-square-root}

对任意 $g \in \GL(V)$，存在多项式 $p(t) \in \mathbb{C}[t]$ 使得 $h := p(g)$ 满足 $h^2 = g$．
:::

:::{.proof}

因为限定了在 $g$ 多项式生成的代数 $\mathbb{C}[g]$ 中寻找 $h$，而 $\mathbb{C}[g] \cong \mathbb{C}[t]/(f(t))$，其中 $f(t)$ 是 $g$ 的最小多项式．因此问题等价于在 $\mathbb{C}[t]/(f(t))$ 中寻找 $t$ 的平方根．注意因为 $g$ 可逆，这里 $f(t)$ 的常数项非零．

由环同构版本的中国剩余定理，找平方根等价于在每个 $\mathbb{C}[t]/(t-b)^r$ 上找 $t$ 的平方根，这里 $b \neq 0$．做一下平移和缩放，等价于在 $\mathbb{C}[t]/(t^r)$ 上找 $1 + at$ 的平方根，这里 $a \neq 0$．

则设 $p(t) = 1 + a_1 t + \cdots + a_{r-1} t^{r-1}$ 满足 $p(t)^2 \equiv 1 + at \pmod{t^r}$．比较系数：

- 常数项：$1 = 1$
- $t$ 的系数：$2 a_1 = a \implies a_1 = \frac{a}{2}$
- $t^k$ 的系数：$2 a_k + \sum_{i=1}^{k-1} a_i a_{k-i} = 0 \implies a_k = -\frac{1}{2} \sum_{i=1}^{k-1} a_i a_{k-i}$

这样就递归地确定了 $a_1, \ldots, a_{r-1}$，平方根存在．
:::

:::{.remark}

此命题的证明大约在 1950s-1960s 之间出现，具体历史评注可见 [@jantzen_nilpotent_2004, {section 1.5}]．
:::

:::{.remark}

注意 $G$ 现在只是正交群 $O(V,\varphi)$，它可能还不足够细．当 $\varphi$ 斜对称时，$G$ 作为辛群是连通的，因此基本上够了．但 $\varphi$ 对称时，$G$ 作为正交群是不连通的，$\SO(V, \varphi)$ 才是它的连通子群．因此 $\SO(V, \varphi)$ 的轨道可能比 $O(V, \varphi)$ 的轨道更细——轨道分类的故事还没有结束．不过这至少帮助我们获得了 Jordan 型的较粗分类．
:::

以后讨论 B、C、D 型的幂零轨道时，默认指代正交群 $O(V, \varphi)$ 作用下的轨道．

## 构造合法分拆 {#sec-construction-of-partition}

另一件尚未完成的工作是：哪些 Jordan 型能够在 $\so(V)$ 或 $\sp(V)$ 的幂零线性变换上产生？剧透一下最终的答案：

- 对于 $\so(V)$，偶数大小的 Jordan 块必须出现偶数次；
- 对于 $\sp(V)$，奇数大小的 Jordan 块必须出现偶数次．

我们将把满足上述条件的分拆称为（对称或斜对称情形下的）合法分拆．讨论此事需关注两个问题：

- 在斜自伴李代数中凑出具有上述 Jordan 型的幂零线性变换
- 证明斜自伴李代数中的幂零线性变换的 Jordan 型必须满足上述条件

我们跟随 [@jantzen_nilpotent_2004, {section 1.6--1.11}]，先提供一个纯线性代数的显式证明．思路很简单：先为一个或两个相同大小的 Jordan 块构造非退化双线性型，然后正交地拼接它们，最后将任何幂零斜自伴线性变换的 Jordan 型约化到上述情况．

本节先来做凑的工作．设在 $d$ 维线性空间 $V$ 中取定基底 $(e_1, \dots, e_d)$，定义幂零线性变换 $X \in \gl(V)$ 在此基下的矩阵为 $d$ 阶 Jordan 块
$$
X e_k = \begin{cases}
e_{k-1} & 2 \leq k \leq d \\
0 & k = 1
\end{cases}
\qquad
\mathrm J_d := \begin{pmatrix}
0 & 1 &   &  \\
  & 0 & \ddots &  \\
  &   & \ddots & 1 \\
  &   &        & 0
\end{pmatrix}
$$
同时定义 $V$ 上的双线性型 $\varphi$ 在此基下的矩阵为
$$
\varphi(e_i, e_j) = \begin{cases}
(-1)^i & \text{if } i + j = d + 1 \\
0 & \text{otherwise}
\end{cases}
\qquad
\Phi_d := \begin{pmatrix}
   &   &    & 1 \\
   &   & -1 &  \\
   & \dots &    &  \\
(-1)^{d-1} &   &    &
\end{pmatrix}
$${#eq-gram-std-single}
容易验证：

- $d$ 偶数时斜对称，$d$ 为奇数时对称．
- $X$ 关于 $\varphi$ 斜自伴．
- $\varphi$ 非退化．
- $d$ 为偶数时 $\varphi$ 斜对称，为 $\sp$ 提供了单个偶数阶 Jordan 块的构造．
- $d$ 为奇数时 $\varphi$ 对称，为 $\so$ 提供了单个奇数阶 Jordan 块的构造．

下面再为成对的块提供构造．设在 $2d$ 维线性空间 $V$ 中取定基底 $(e_1, \dots, e_d, f_1, \dots, f_d)$ 使得前 $d$ 个基向量张成的子空间上 $X$ 的矩阵为 $\mathrm J_d$，后 $d$ 个基向量张成的子空间上也为 $\mathrm J_d$，即 $X$ 在此基下的矩阵为
$$
\begin{pmatrix}
\mathrm J_d &   \\
   & \mathrm J_d
\end{pmatrix}
$$
定义双线性型 $\varphi$ 在此基下的矩阵为
$$
\Phi := \begin{pmatrix}
0 & \Phi_d \\
\varepsilon \Phi_d^T & 0
\end{pmatrix}
$${#eq-gram-std-pair}
这里 $\varepsilon \in \{1,-1\}$．同样容易验证：

- $X$ 关于 $\varphi$ 斜自伴．
- $\varphi$ 非退化．
- $\varepsilon = -1$ 时 $\varphi$ 斜对称，为 $\sp$ 提供了成对 Jordan 块的构造．
- $\varepsilon = 1$ 时 $\varphi$ 对称，为 $\so$ 提供了成对 Jordan 块的构造．

注意非退化双线性型的正交直和保持其非退化性、对称或斜对称性．因此我们完成了 $\so$ 和 $\sp$ 中合法分拆的构造．

## 约化到合法分拆 {#sec-reduction-to-partition}

:::{#prp-reduction-to-partition}

设 $V$ 是配备对称或斜对称双线性型 $\varphi$ 的线性空间，$X \in \mathfrak{g} := \mathfrak{o}(V, \varphi)$ 是幂零斜自伴线性变换．则存在 $V$ 的正交分解 $V = V_1 \oplus \dots \oplus V_r$ 使得每个 $V_i$ 是 $X$ 的不变子空间，且记 $d_i := \dim V_i$ 时有：

- 若 $\varphi$ 对称，则 $X$ 在 $V_i$ 上的 Jordan 型要么是奇数阶单个 Jordan 块 $[d_i]$，要么是成对的两个 Jordan 块 $[d_i / 2, d_i / 2]$．
- 若 $\varphi$ 斜对称，则 $X$ 在 $V_i$ 上的 Jordan 型要么是偶数阶单个 Jordan 块 $[d_i]$，要么是成对的两个 Jordan 块 $[d_i / 2, d_i / 2]$．
:::

:::{.proof}

考虑 $X$ 的幂零指数 $d$ 使得 $X^d = 0$ 且 $X^{d-1} \neq 0$．任取 $u_0 \in V$ 使得 $X^{d-1} u_0 \neq 0$ 并定义 $u_k := X^k u_0$，记 $U := \mathbb C u_0 \oplus \dots \oplus \mathbb C u_{d-1}$，这是 $X$ 的一个 $d$ 维不变子空间，且 $X$ 在基底 $(u_{d-1}, \dots, u_0)$ 上的矩阵实现为 Jordan 块 $\mathrm J_d$．进一步考察 $\varphi$ 限制在 $U$ 上相对基底 $(u_{d-1}, \dots, u_0)$ 的矩阵，多次使用 $X$ 关于 $\varphi$ 的斜自伴性
$$
\varphi(u_i, u_j) = \varphi(X^i u_0, X^j u_0) = (-1)^i \varphi(u_0, X^{i+j} u_0)
$$
这意味着矩阵在每条反对角线上正负交替；且当 $i+j \geq d$ 时 $\varphi(u_i, u_j) = 0$，即矩阵在严格左上三角区域为零．

现在考虑 $U$ 关于 $\varphi$ 的正交补 $U^\perp$，有两种情况需要讨论．

如果 $U^\perp \cap U = \{0\}$．由于 $X$ 关于 $\varphi$ 的斜自伴性，$U^\perp$ 也是 $X$ 的不变子空间．此时在 $U^\perp$ 上重复上述过程归纳即可．注意此时 $\varphi$ 在 $U$ 上非退化，结合之前分析 $\varphi$ 在 $U$ 上的矩阵结构知反对角线上正负交替的元素必非零：
$$
\varphi(u_0，u_{d-1}) = \dots = (-1)^{d-1} \varphi(u_{d-1}, u_0) \neq 0
$$
于是当 $\varphi$ 对称时 $d$ 必须为奇数，当 $\varphi$ 斜对称时 $d$ 必须为偶数．

如果 $U^\perp \cap U \neq \{0\}$．取一 $u \in U^\perp \cap U$，不妨设 $u = \sum_{k=0}^{d-1} c_k u_k$ 并设 $s$ 是使得 $c_s \neq 0$ 的第一个正整数．则 $X^{d-s-1} u = c_s u_{d-1} \neq 0$，因此 $u_{d-1} \in U \cap U^\perp$．

因为 $\varphi$ 非退化，存在 $w_0 \in V$ 使得 $\varphi(u_{d-1}, w_0) = 1$．定义 $w_k := X^k w_0$，记 $W := \mathbb C w_0 \oplus \dots \oplus \mathbb C w_{d-1}$，这是 $X$ 的一个 $d$ 维不变子空间．下面断言

- $w_1, \dots, w_{d-1}$ 线性无关．因为它们是由幂零线性变换 $X$ 多次作用得到，其实只需证这些向量非零：多次使用 $X$ 关于 $\varphi$ 的斜自伴性
  $$
  1 = \varphi(u_{d-1}, w_0) = -\varphi(u_{d-2}, w_1) = \dots = (-1)^{d-1} \varphi(u_0, w_{d-1})
  $$
  即可．

- $U \cap W = 0$．设 $v = \sum_{k=0}^{d-1} a_k u_k = \sum_{k=0}^{d-1} b_k w_k$．假若 $v \neq 0$，设 $s$ 是使得 $a_s \neq 0$ 或 $b_s \neq 0$ 的第一个正整数．则同时作用 $X^{d-s-1}$ 得到 $a_s u_{d-1} = b_s w_{d-1}$．注意 $u_{d-1} \in U^\perp$ 和 $w_{d-1} \notin U^\perp$ 线性无关，于是 $a_s = b_s = 0$，矛盾．这意味着 $v = 0$．

- $(U \oplus W) \cap (U \oplus W)^\perp = \{0\}$．为此取其中一 $v = \sum_{k=0}^{d-1} a_k u_k + \sum_{k=0}^{d-1} b_k w_k$，反设 $s$ 是使得 $a_s \neq 0$ 或 $b_s \neq 0$ 的第一个正整数．则 $X^{d-s-1} v = a_s u_{d-1} + b_s w_{d-1}$，于是（回忆 $u_{d-1} \in U^\perp$，$\varphi(u_{d-1}, w_0) = 1$）
  $$
  \begin{aligned}
  0 &= \varphi(u_{d-s-1}, v) = \varphi(u_0, X^{d-s-1} v) = b_s \varphi(u_0, w_{d-1}) = b_s \varphi(u_{d-1}, w_0) \\
  0 &= \varphi(w_{d-s-1}, v) = \varphi(w_0, X^{d-s-1} v) = a_s \varphi(w_0, u_{d-1}) + b_s \varphi(w_0, w_{d-1})
  \end{aligned}
  $$
  回忆 $\pm \varphi(w_0, u_{d-1}) = \pm \varphi(u_{d-1}, w_0) = \pm 1$，因此 $a_s = b_s = 0$，矛盾，因此 $v = 0$．

因此 $U \oplus W$ 是 $X$ 的一个 $2d$ 维不变子空间，且 $X$ 在 $U \oplus W$ 上实现为两个 $d$ 阶 Jordan 块的直和．由 $X \in \mathfrak{g}$ 的斜自伴性知 $(U \oplus W)^\perp$ 也是 $X$-不变子空间，在其上重复上述过程归纳即可．
:::

## 约化到标准型

:::{#thm-reduction-to-normal-form}

继承 [@prp-reduction-to-partition] 的记号．可以在每个 $V_i$ 上选取基底，使得 $X$ 和 $\varphi$ 在此基下的矩阵服从 [@sec-construction-of-partition] 给出的两类基本构造之一．
:::

:::{.proof}

不妨在 $V = V_i$ 里工作并在此空间内作基本构造．设基本构造使用的基底是 $(e_k) \subseteq V$，非退化双线性型为 $\varphi_0$，幂零元为 $X_0 \in \mathfrak{o}(V, \varphi_0)$．由 [@prp-sym-diag] 或 [@prp-alt-standard]，存在 $h \in \GL(V)$ 使得 $\varphi(hv, hw) = \varphi_0(v, w)$．构造 $X_1 := h X_0 h^{-1} \in \mathfrak{o}(V, \varphi)$，它斜自伴是因为：
$$
\begin{aligned}
\varphi(X_1 v, w) + \varphi(v, X_1 w)
&= \varphi(h X_0 h^{-1} v, w) + \varphi(v, h X_0 h^{-1} w) \\
&= \varphi_0(X_0 \cdot h^{-1} v, h^{-1} w) + \varphi_0(h^{-1} v, X_0 \cdot h^{-1} w) \\
&= 0
\end{aligned}
$$
同时 $X_1$ 在基底 $(h e_k)$ 上的矩阵是 Jordan 标准型，$\varphi$ 在基底 $(h e_k)$ 上的矩阵是反对角的．注意 $X_1$ 与 $X$ 有相同的 Jordan 型且同属 $\mathfrak{o}(V,\varphi)$，故由 [@thm-orbit-by-gl]，存在 $g \in O(V,\varphi)$ 使得 $g X_1 g^{-1} = X$．现在使用基底 $(g h e_k)$，则 $X$ 的矩阵是 Jordan 标准型，而利用 $g$ 的正交性，$\varphi$ 的矩阵仍然是反对角的：
$$
\varphi(g h e_i, g h e_j) = \varphi(h e_i, h e_j) = \varphi_0(e_i, e_j)
$$
故 $(g h e_k)$ 就是我们所求的基底．
:::

:::{.remark}

这一步的证明在 [@jantzen_nilpotent_2004, {section 1.11}] 的第一句话处一笔带过．
:::

## 经典李代数的 Jacobson--Morozov 定理 {#sec-jacobson-morozov-classical}

上一节完成的正交群幂零轨道分类工作颇有表示论的风味．从矩阵的语言来看，我们显式构造了一个 $V$ 上的可逆线性变换，同时合同地调整非退化双线性型 $\varphi \in V^* \otimes V^*$ 并相似地调整斜自伴幂零算子 $X \in V \otimes V^*$，使得 $X$ 化为 Jordan 标准型，且块与块间正交．本节首先利用分类结果证明经典李代数上的 Jacobson--Morozov 定理，借此为幂零轨道分类提供一个表示论风格的阐述，最后反过来利用 Jacobson--Morozov 定理重新提供一个更干净整洁的非构造性证明．

Jacobson--Morozov 定理允许我们为任何幂零元 $X \in \mathfrak g$ 补出其对应的 $\sl_2$-三元组 $(X,Y,H)$：

:::{#thm-jacobson-morozov}

## Jacobson--Morozov

设 $\mathfrak g$ 为复半单李代数，对任意幂零元 $X \in \mathfrak g$，存在 $Y, H \in \mathfrak g$ 使得
$$
[H, X] = 2X, \quad [H, Y] = -2Y, \quad [X, Y] = H,
$$
即 $(X, Y, H)$ 构成一个 $\sl_2$-三元组．
:::

一般情况的证明需用到 Killing 型、抽象 Jordan 分解和 Cartan 根空间分解，我们留作附录．但这里可以为经典李代数提供 $\sl_2$ 三元组的显式构造．

先看 A 型．设 $X \in \sl(V)$ 幂零，选取基底使 $X$ 化为若干 Jordan 块 $\mathrm J_d$ 的直和．不妨设单个 $d$ 维块上基底 $(e_1, \dots, e_d)$ 使得 $X e_k = e_{k-1}$（$e_0 := 0$）．则定义 $H$ 和 $Y$ 在此基下的矩阵：
$$
H e_k = (d+1-2k) e_k \qquad \mathrm H_d := \diag(d-1, d-3, \dots, -(d-1))
$$
$$
Y e_k = \begin{cases}
k(d-k) e_{k+1} & \quad 1 \leq k \leq d-1 \\
0 & \quad k = d
\end{cases}
\qquad
\mathrm Y_d :=
\begin{pmatrix}
0 & & & & \\
1 \cdot (d-1) & 0 & & & \\
  & 2 \cdot (d-2) & 0 & & \\
  &  & \ddots & \ddots & \\
  &  &  & (d-1) \cdot 1 & 0
\end{pmatrix}
$$
这就是 $\sl_2$ 的 $d$ 维不可约表示的标准构造．各块拼接即完成 A 型的构造．

现在看 B, C, D 型．设 $X \in \mathfrak g := \mathfrak o(V, \varphi)$ 幂零，非退化双线性型 $\varphi$ 对称或斜对称．由 [@thm-reduction-to-normal-form]，可选取基底使 $X$ 为 Jordan 标准型且 $\varphi$ 的矩阵为 [@sec-construction-of-partition] 中的反对角构造．现在在每个子块补出 $Y, H$：

- 对单块情形 [@eq-gram-std-single]，直接沿用 A 型构造的 $\mathrm Y_d, \mathrm H_d$．
- 对成对块情形 [@eq-gram-std-pair]，直接相对其基底 $(e_1, \dots, e_d, f_1, \dots, f_d)$ 使用矩阵 $\mathrm Y := \begin{pmatrix} \mathrm Y_d & 0 \\ 0 & \mathrm Y_d \end{pmatrix}$ 和 $\mathrm H := \begin{pmatrix} \mathrm H_d & 0 \\ 0 & \mathrm H_d \end{pmatrix}$ 即可．

小心仔细的计算表明无论是单个块还是成对的块，$Y, H$ 仍满足斜自伴条件：

:::{.proof}

## 验证 $Y, H$ 的斜自伴性

我们在矩阵记号下工作．回忆 $\mathfrak g = \{ \mathrm M : \mathrm M^T \Phi = -\Phi \mathrm M \}$．

对单块情形，设块大小为 $d$，
$$
\begin{aligned}
\mathrm H_d &= \diag(d-1, d-3, \dots, -(d-1)) & \Phi_d &= \antidiag((-1)^{d-1},\dots,-1,1), \\
\mathrm Y_d &=
\begin{pmatrix}
0 \\
1(d-1) & 0 \\
& 2(d-2) & 0 \\
& & \ddots & \ddots \\
& & & (d-1)\cdot 1 & 0
\end{pmatrix}
&
\mathrm Y_d^T &=
\begin{pmatrix}
0 & 1(d-1) \\
& 0 & 2(d-2) \\
& & \ddots & \ddots \\
& & & 0 & (d-1)\cdot 1 \\
& & & & 0
\end{pmatrix}
\end{aligned}
$$
手动计算验证 $\mathrm H_d^T \Phi_d = -\Phi_d \mathrm H_d$ 和 $\mathrm Y_d^T \Phi_d = -\Phi_d \mathrm Y_d$ 即可．

对成对块情形，设每块大小为 $d$，此时
$$
\Phi = \begin{pmatrix} 0 & \Phi_d \\ \varepsilon \Phi_d^T & 0 \end{pmatrix}
\quad
\mathrm H = \begin{pmatrix} \mathrm H_d & 0 \\ 0 & \mathrm H_d \end{pmatrix}
\quad
\mathrm Y = \begin{pmatrix} \mathrm Y_d & 0 \\ 0 & \mathrm Y_d \end{pmatrix}
\quad \varepsilon = \pm 1
$$
对 $\mathrm H$：
$$
\mathrm H\Phi = \begin{pmatrix} 0 & \mathrm H_d \Phi_d \\ \varepsilon \mathrm H_d \Phi_d^T & 0 \end{pmatrix}
\qquad
-\Phi \mathrm H = \begin{pmatrix} 0 & -\Phi_d \mathrm H_d \\ -\varepsilon \Phi_d^T \mathrm H_d & 0 \end{pmatrix}
$$
右上块 $\mathrm H_d \Phi_d = -\Phi_d \mathrm H_d$ 即单块结论．对左下块，将单块结论取转置得 $\Phi_d^T \mathrm H_d = -\mathrm H_d \Phi_d^T$，即 $\mathrm H_d \Phi_d^T = -\Phi_d^T \mathrm H_d$，两边乘 $\varepsilon$ 即得所需．
对 $\mathrm Y$：
$$
\mathrm Y^T \Phi = \begin{pmatrix} 0 & \mathrm Y_d^T \Phi_d \\ \varepsilon \mathrm Y_d^T \Phi_d^T & 0 \end{pmatrix}
\qquad
-\Phi \mathrm Y = \begin{pmatrix} 0 & -\Phi_d \mathrm Y_d \\ -\varepsilon \Phi_d^T \mathrm Y_d & 0 \end{pmatrix}
$$
右上块 $\mathrm Y_d^T \Phi_d = -\Phi_d \mathrm Y_d$ 即单块结论．左下块由单块结论取转置 $\Phi_d^T \mathrm Y_d = -\mathrm Y_d^T \Phi_d^T$ 即得 $\mathrm Y_d^T \Phi_d^T = -\Phi_d^T \mathrm Y_d$，两边乘 $\varepsilon$ 即得所需．
:::

因此我们完成了 B, C, D 型的构造．

:::{.remark}

如果不执着于将 $X$ 实现为 Jordan 标准型，适当放缩，$m+1$ 阶单块矩阵的三元组和 Gram 矩阵可以获得更对称的矩阵写法：
$$
\mathrm X := \begin{pmatrix}
0 & m & & & \\
  & 0 & m-1 & & \\
  &   & \ddots & \ddots & \\
  &   &   & 0 & 1 \\
  &   &   &   & 0
\end{pmatrix} \quad
\mathrm Y := \begin{pmatrix}
0 &   &   &   & \\
1 & 0 &   &   & \\
  & 2 & 0 &   & \\
  &   & \ddots & \ddots & \\
  &   &   & m & 0
\end{pmatrix}
$$
$$
\mathrm H := \diag(m, m-2, \dots, -m+2, -m)
$$
$$
\Phi := \begin{pmatrix}
   &   &    & \binom{m}{0} \\
   &   & -\binom{m}{1} &  \\
   & \dots &    &  \\
(-1)^{m} \binom{m}{m} &   &    &
\end{pmatrix}
$$
这里的 $\binom{m}{k}$ 是二项式系数．
:::

## 表示论风格的分类重证 {#sec-rep-theory-orbit-classification}

由于 Jacobson--Morozov 定理有完全不依赖经典李代数的抽象证明，可以考虑反过来利用它来重新为幂零轨道分类提供一个更干净整洁的非构造性证明．

为幂零元 $X \in \mathfrak g := \mathfrak{o}(V, \varphi)$ 补出 $\sl_2$-三元组 $(X, Y, H)$ 后，$V$ 成为一个 $\sl_2$-模．由 $\sl_2$-模的表示理论，其完全分解为
$$
V \cong \bigoplus_k V_k^{\oplus r_k} \cong \bigoplus_k (V_k \otimes \mathbb C^{\oplus r_k})
$$
其中 $V_k$ 是 $\sl_2$ 的 $k$ 维不可约表示，$X$ 在每个 $V_k$ 上的作用恰为一个 $k$ 阶幂零 Jordan 块．故 Jordan 型由重数 $r_k$ 完全确定．

$X$ 的斜自伴性意味着 $\varphi$ 是 $V \to V^*$ 的 $\sl_2$-模同态，即 $\varphi \in (V^* \otimes V^*)^{\sl_2}$．在 $V^* \otimes V^*$ 上使用上面的分解：
$$
V^* \otimes V^* \cong \bigoplus_{i,j} (V_i^* \otimes V_j^*) \otimes (\mathbb C^{\oplus r_i} \otimes \mathbb C^{\oplus r_j})
$$
$\sl_2$ 只作用于 $V_i^* \otimes V_j^*$．注意 $\sl_2$-表示是自伴的 $V_k \cong V_k^*$，故由 Schur 引理，$i \neq j$ 时 $(V_i^* \otimes V_j^*)^{\sl_2} \cong \Hom_{\sl_2}(V_i, V_j) = 0$，故可不考虑交叉项，上式简化为：
$$
(V^* \otimes V^*)^{\sl_2} \cong \bigoplus_k (V_k^* \otimes V_k^*)^{\sl_2} \otimes (\mathbb C^{\oplus r_k} \otimes \mathbb C^{\oplus r_k})
$$
仍由 Schur 引理，$(V_k^* \otimes V_k^*)^{\sl_2} \cong \Hom_{\sl_2}(V_k, V_k^*)$ 是一维线性空间．我们其实在上一小节手动完成经典李代数的 Jacobson--Morozov 定理时已经构造出其中的一个非零元素（即单块情形的反对角构造），故 $V_k$ 是对称还是斜对称由维数 $k$ 的奇偶性决定：$k$ 偶数时斜对称，$k$ 奇数时对称．

注意直和项作为双线性型的非退化性、对称性或斜对称性与原双线性型相同．来考虑每个直和项张量积的右侧：$\mathbb C^{\oplus r_k}$ 上的一个非退化双线性型．回忆 [@prp-sym-diag] 和 [@prp-alt-standard]，这后一个双线性型为对称时对 $r_k$ 无限制，为斜对称时 $r_k$ 必须为偶数．于是：

- 若 $\varphi$ 对称：$k$ 为偶数时 $V_k$ 侧是斜对称，故 $\mathbb C^{\oplus r_k}$ 上的双线性型必须是斜对称，从而 $r_k$ 为偶数；$k$ 奇数时 $V_k$ 侧的型是对称，故 $\mathbb C^{\oplus r_k}$ 上的型也可以取对称，对 $r_k$ 无限制．
- 若 $\varphi$ 斜对称（$\sp$ 情形）：$k$ 为奇数时 $V_k$ 侧的型是对称，故 $\mathbb C^{\oplus r_k}$ 上的双线性型必须是斜对称，从而 $r_k$ 为偶数；$k$ 偶数时 $V_k$ 侧的型是斜对称，故 $\mathbb C^{\oplus r_k}$ 上的型可以取对称，对 $r_k$ 无限制．

这正好是合法分拆的条件——$\so(V)$ 中偶数大小块出现偶数次，$\sp(V)$ 中奇数大小块出现偶数次．我们重新完成了幂零轨道的分类．

:::{.remark .content-visible when-format="html"}

- Some of the ideas from [Mathoverflow](https://mathoverflow.net/questions/9361/how-can-we-describe-the-splitting-of-nilpotent-orbit-for-very-even-partitions)
:::

## 特殊正交群 $\SO_{2n}$ 与轨道分支现象

回到之前提到的作用群选择问题．我们提到特殊正交群 $\SO$ 的产生的轨道可能更细．记 $G := O(V, \varphi)$，$G^\circ := \SO(V, \varphi)$，$\mathfrak{g} := \so(V, \varphi)$．

:::{#lem-special-same}

设 $X \in \mathfrak{g}$，则 $X$ 在 $G$ 下的轨道在 $G^\circ$ 下分裂为两个轨道当且仅当不存在 $h \in G$ 使得 $h \cdot X = X$ 且 $\det h = -1$．
:::

:::{.proof}

设 $g \in G$ 且 $\det g = -1$，则 $G = G^\circ \sqcup G^\circ g$．于是
$$
G^\circ \cdot X = G^\circ g \cdot X
\iff g \cdot  X \in G^\circ \cdot X \\
\iff \exists h \in G^\circ,\, hg \cdot X = X
$$
注意 $\det (hg) = -1$，这完成了证明．
:::

这种元素其实相当常见，例如 $-1$ 就给出了空间是奇数维时的例子．考虑到我们的幂零轨道分类结果，只要分拆中存在至少奇数大小的块，在此块上取 $-1$、其它块上取 $1$ 就给出了一个满足条件的元素．因此只有当分拆中全是偶数大小的块时，才可能出现轨道分裂现象．这是所谓的非常偶（very even）的情形，只可能在 $D_n$ 型李代数 $\so_{2n}$ 中出现．关于此时幂零轨道确实分裂的证明可参考 [@jantzen_nilpotent_2004, {section 3.13}]．

## 一般李代数的 Jacobson--Morozov 定理 {.appendix .unnumbered}

本节在一般的有限维复半单李代数中证明 [@thm-jacobson-morozov]．记号便利起见，再次将定理重述如下：

:::{#thm-jacobson-morozov-appendix}

## Jacobson--Morozov

设 $\mathfrak g$ 为一有限维复半单李代数，对任意幂零元 $e \in \mathfrak g$，存在 $h, f \in \mathfrak g$ 使得 $e$, $h$, $f$ 满足 $\sl_2$ 的 Lie 括号关系 $[h,e] = 2e$, $[h,f] = -2f$, $[e,f] = h$．
:::

先做一个观察：首先注意满足上述条件的 $h$ 一定是半单的：这是通过 $e$, $f$, $h$ 将 $\mathfrak g$ 实现为 $\sl_2$ 的表示后，使用 $\sl_2$ 表示论的完全可约性得到的结果．所以将来的证明中，构造半单的 $h$ 也是必经之路．

下面给出的证明跟随 [@mcgovern_nilpotent_1993, {theorem 3.3.1}]．证明需要抽象 Jordan 分解、Killing 型和 Cartan 根空间分解理论 [@hu_bggo_2020, {section 1.5, 1.8}] 以及如下引理：

:::{#lem-centralizer-reductive}

[@mcgovern_nilpotent_1993, {lemma 2.1.2}] 约化李代数任意半单元的中心化子是也是约化李代数．
:::

:::{#lem-centralizer-othogonal}

设 $e$ 是有限维复半单李代数 $\mathfrak g$ 中任意元素，则其中心化子 $\mathfrak z(e)$ 和 $[e,\mathfrak g]$ 互为 Killing 型意义下的正交补．
:::

:::{.proof}

注意到
$$
\kappa(\mathfrak z(e), [e,\mathfrak g]) = \kappa([\mathfrak z(e), e], \mathfrak g) = 0
$$
故 $\mathfrak z(e)$ 与 $[e,\mathfrak g]$ 正交．又由正合列
$$
0 \longrightarrow \mathfrak z(e) \longrightarrow \mathfrak g \xrightarrow{\ad e} [e,\mathfrak g] \longrightarrow 0
$$
考察维数并使用 Killing 型在半单李代数中的非退化性就有正交补关系．
:::

:::{.proof}

## Jacobson--Morozov 定理的证明

对维数 $\mathfrak g$ 做归纳，则可以先假设 $e$ 不落在 $\mathfrak g$ 任何真半单子李代数中——否则直接在那个更小的半单李代数中构造 $h$ 和 $f$ 即可．这会帮我们在后面排除一大类讨论情况．

下面开始构造．先构造 $h \in \mathfrak g$ 使得 $[h,e] = 2e$，为此只需证明 $e \in [e, \mathfrak g]$．由 [@lem-centralizer-othogonal]，这等价于证明 $e$ 与 $\mathfrak z(e)$ 正交．对任意与 $e$ 交换的 $x \in \mathfrak z(e)$，$\ad x$ 也与 $\ad e$ 交换，故 $e$ 幂零即是 $\ad e$ 幂零进而导致 $\ad e \circ \ad x$ 幂零．因此 $\kappa(e,x) = \Tr(\ad e \circ \ad x) = 0$，$e$ 确实与 $\mathfrak z(e)$ 正交，进而所需的 $h$ 存在．

再修改 $h$ 使其半单．考虑 $h$ 的抽象 Jordan 分解 $h = h_s + h_n$，其中 $h_s$ 半单，$h_n$ 幂零．注意 $\ad h_s$, $\ad h_n$ 都是可写成关于 $\ad h$ 的多项式，故也与 $\ad h$ 共享特征向量 $e$．$h_n$ 幂零，故特征值 $[h_n, e] = 0$，因此 $[h_s, e] = [h,e]-[h_n,e] = 2e$．取新的 $h := h_s$ 即可．

半单的 $h$ 使得可以关于它将 $\mathfrak g$ 做权空间分解 $\mathfrak g = \bigoplus_{i \in \mathbb Z} \mathfrak g_i$，于是 $h \in \mathfrak g_0$，$e \in \mathfrak g_2$，且容易验证 $[e, \mathfrak g_i] \subseteq \mathfrak g_{i+2}$．现在来构造 $f$．它需要满足 $[h,f]=-2f$，故应当在 $\mathfrak g_{-2}$ 中寻找．它还需满足 $[e,f]=h$，故只需证 $h \in [e, \mathfrak g_{-2}]$．如果我们**暂时断言 $h \in [e,\mathfrak g]$**，则 $h \in \bigoplus_i [e, \mathfrak g_i]$．但 $h \in \mathfrak g_0$，逼迫 $h \in [e, \mathfrak g_{-2}]$，证毕．

现在来证明断言 $h \in [e,\mathfrak g]$，已有的条件是 $[h,e] = 2e$ 及 $h$ 半单．仍然用关系 $[e,\mathfrak g] = \mathfrak z(e)^\perp$，只需证 $h$ 与 $\mathfrak z(e)$ 正交．考察 $\mathfrak z(e)$ 相对 $h$ 的权空间分解 $\mathfrak z(e) = \bigoplus_i \mathfrak z(e)_i$，这里 $\mathfrak z(e)_i = \mathfrak z(e) \cap \mathfrak g_i$．于是对任意 $z_i \in \mathfrak z(e)_i$，
$$
0 = \kappa([h,h],z_i) = \kappa(h, [h, z_i]) = i \cdot \kappa(h, z_i)
$$
故 $h$ 与 $\mathfrak z(e)_i$ 正交对任意 $i \neq 0$ 成立．

现在只需证 $h$ 与 $\mathfrak z(e)_0$ 正交．对任意 $z_0 \in \mathfrak z(e)_0$，注意 $z_0$ 与 $e$ 和 $h$ 交换．不失一般性，可设 $z_0$ 半单：

- 因为其半单部分 $(z_0)_s$ 与 $h$ 正交当且仅当 $z_0$ 与 $h$ 正交：为此只需证幂零部分 $(z_0)_n$ 与 $h$ 正交，这是因为 $(z_0)_n$ 与 $z_0$ 交换进而与 $h$ 交换，故 $\ad h \circ \ad (z_0)_n$ 是幂零，因此 $\kappa(h, (z_0)_n) = \Tr(\ad h \circ \ad (z_0)_n) = 0$．

下面证明在上述限制下只能有 $z_0 = 0$，从而 $h$ 与 $\mathfrak z(e)_0$ 的正交性平凡．为此反设 $z_0 \neq 0$，由 [@lem-centralizer-reductive]，$\mathfrak z(z_0)$ 是约化李代数．$\mathfrak g$ 半单中心平凡保证 $\mathfrak z(z_0)$ 比 $\mathfrak g$ 严格更小．注意 $e, h \in \mathfrak z(z_0)$，于是 $2e = [h,e] \in [\mathfrak z(z_0), \mathfrak z(z_0)]$，后者是一个半单李代数．终于，我们把 $e$ 放到了一个比 $\mathfrak g$ 严格更小的半单李代数 $[\mathfrak z(z_0), \mathfrak z(z_0)]$ 中，但是这与整个证明一开始的假设冲突．因此 $z_0 = 0$，$h$ 与 $\mathfrak z(e)$ 正交，断言得证．
:::