---
title: A Table of Lie Groups and Lie Algebras
author: sun123zxy
date: 2025/10/16
lang: zh
# bibliography: index.bib

draft: true
categories:
  - math 
  - algebra

format:
  html: default
---

\newcommand{\GL}{\mathrm{GL}}
\newcommand{\SL}{\mathrm{SL}}
\newcommand{\SO}{\mathrm{SO}}
\newcommand{\Sp}{\mathrm{Sp}}
\newcommand{\gl}{\mathfrak{gl}}
\newcommand{\sl}{\mathfrak{sl}}
\newcommand{\so}{\mathfrak{so}}
\newcommand{\sp}{\mathfrak{sp}}
\newcommand{\b}{\mathfrak{b}}
\newcommand{\n}{\mathfrak{n}}
\newcommand{\h}{\mathfrak{h}}

\newcommand{\diag}{\operatorname{diag}}

:::{.list-table .column-page}

* - Type
  
  - Radical  
    (maximal solvable ideal)
  - Levi subalgebra  
    (semisimple subalgebra complementing the radical)
  - Cartan subalgebra  
    (self-normalizing nilpotent subalgebra)  
    Maximal toral subalgebra  
    (maximal abelian subalgebra of semisimple elements)
  - Borel subalgebra  
    (maximial solvable subalgebra)

* - $\gl(n)$, all matrices
  - scalar matrices
  - $\sl(n)$
  - []{colspan=2} (not semisimple)

* - $\sl(n)$, matrices with trace $0$
  - []{colspan=2} (simple)
  - diagonal matrices with trace 0
  - upper triangular matrices with trace $0$

* - $\so(n)$, skew-symmetric matrices
  - []{colspan=2} (semisimple)
  - block-diagonal ...
  - 

* - $\sp(2n)$
  - []{colspan=2} (simple)
  - $\diag(h_1,\dots,h_n,−h_1,\dots,−h_n)$
  -
:::