---
title: Schur--Weyl 对偶
author: sun123zxy
date: 2026-04-19
lang: zh
bibliography: index.bib

categories:
  - math
  - algebra
collections:
  - group-rep-tour

number-sections: true

format:
  html: default
  pdf: default
---

\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\GL}{\operatorname{GL}}
\newcommand{\im}{\operatorname{im}}
\newcommand{\id}{\operatorname{id}}
\newcommand{\Tr}{\operatorname{Tr}}
\newcommand{\End}{\operatorname{End}}
\newcommand{\Sym}{\operatorname{Sym}}
\newcommand{\Alt}{\operatorname{Alt}}
\def\bbinom#1#2{{\left(\kern-.3em\left(\genfrac{}{}{0pt}{}{#1}{#2}\right)\kern-.3em\right)}}
\newcommand{\sgn}{\operatorname{sgn}}
\newcommand{\gl}{\mathfrak{gl}}
\renewcommand{\sl}{\mathfrak{sl}}

- 路线主要参考 [@etingof_introduction_2011, {section 5.18--5.19}]．

## 从 Sym 和 Alt 谈起

众所周知，设 $G$ 是群，则对任意 $G$ 的 $n$ 维表示 $V$，$V \otimes_{\mathbb C} V$ 都可以分解为子表示 $\Sym^2 V$ 和 $\Alt^2 V$ 的直和，其中

- $\Sym^2 V$ 由 $v \otimes w + w \otimes v$ 生成，在交换 $V \otimes V$ 的作用下稳定，是左作用 $G$ 的不变子空间，维数为 $\bbinom{n}{2} = \frac{n(n+1)}{2}$．

- $\Alt^2 V$ 由 $v \otimes w - w \otimes v$ 生成，在交换 $V \otimes V$ 的作用下变号，是左作用 $G$ 的不变子空间，维数为 $\binom{n}{2} = \frac{n(n-1)}{2}$．

对一般的 $G$-表示 $T^d V := V^{\otimes d}$，也会想要获得类似的分解．当然还是先类似定义 $G$-子表示 $\Sym^d V$ 和 $\Alt^d V$．此时考虑 $d$ 阶置换群 $\mathcal S_d$ 在 $V^{\otimes d}$ 上的作用变得有益：定义
$$
\sigma \cdot (v_1 \otimes \cdots \otimes v_d) := v_{\sigma^{-1}(1)} \otimes \cdots \otimes v_{\sigma^{-1}(d)}
$$
为什么是取逆？因为这是对多重张量位置的置换是右作用，必须采用对极映射强行逆回左作用．线性扩展后这将 $V^{\otimes d}$ 做成 $\mathbb C[\mathcal S_d]$-左模．

于是 $V^{\otimes d}$ 被做成 $G \times \mathcal S_d$ 表示——显然 $G$ 和 $\mathcal S_d$ 的作用互相交换．而两个不变子空间的性质列表如下：

:::{.list-table}

- - 
  - $\Sym^d V$
  - $\Alt^d V$

- - 作为像
  - $\left( \sum_{\sigma \in \mathcal S_d} \sigma \right) \cdot V^{\otimes d}$
  - $\left( \sum_{\sigma \in \mathcal S_d} \sgn(\sigma) \sigma \right) \cdot V^{\otimes d}$

- - 作为核
  - $\mathcal S_d$ 作用下稳定
  - $\mathcal S_d$ 作用下按置换 $\sgn$ 变号

- - 关于左作用 $G$
  - 不变子空间
  - 不变子空间

- - 维数
  - $\bbinom{n}{d} = \frac{n(n+1)\cdots(n+d-1)}{d!}$
  - $\binom{n}{d} = \frac{n(n-1)\cdots(n-d+1)}{d!}$
:::

这两个空间还是无交，但它们不再张成整个 $V^{\otimes d}$ 了——对 $d \geq 3$ 的情况 $n^d > \bbinom{n}{d} + \binom{n}{d}$．$V^{\otimes d}$ 中还藏有其它 $\mathcal S_d$ 和 $G$ 的不变子空间．

## Schur--Weyl 分解

Schur--Weyl 分解对此给出了一个非常漂亮的答案：作为 $G \times \mathcal S_d$-表示，
$$
V^{\otimes d} \cong \bigoplus_{\lambda \vdash d} V_\lambda \otimes_{\mathbb C} \mathbb S_\lambda V
$$
这里

- $\lambda \vdash d$ 取遍所有 $d$ 的分拆，但分拆长度超过 $n$ 时是退化情况
- $V_\lambda := \mathbb C[\mathcal S_d] c_\lambda$ 是通常的 $\mathcal S_d$ 的不可约表示，再补充上 $G$ 的平凡作用后升级为 $G \times \mathcal S_d$ 的表示
- $\mathbb S_\lambda V := c_\lambda \cdot V^{\otimes d}$ 是 $G$ 的表示（$G$-不变性是因为 $G$ 与 $\mathcal S_d$ 作用交换），再补充上 $\mathcal S_d$ 的平凡作用后升级为 $G\times \mathcal S_d$ 的表示
- $\otimes_{\mathbb C}$ 是 $G \times \mathcal S_d$-表示的张量积

:::{.remark}

## Abuse of Notation

$V_\lambda$ 的记号里虽然有 $V$，其实和 $V$ 没有联系．要怪就怪 [@fulton_representation_2004, {Chapter 6}] 是这么写的吧．
:::

:::{.remark}

## Sym and Alt

注意在此记号下，$\Sym^d V$ 和 $\Alt^d V$ 恰好分别是 $\lambda = (d)$ 和 $\lambda = (1, \dots, 1)$ 的 $\mathbb S_\lambda V$．
:::

:::{.remark}

## 下标取值范围

不会因为认为 $\lambda \vdash n$ 受到任何处分——我们去掉 $\lambda$ 的长度超过 $n$ 的部分只是因为此时 $\mathbb S_\lambda V = V^{\otimes d} \cdot b_\lambda a_\lambda$ 退化为 $0$．

退化在 $\Alt^d V$ 上其实已经初见端倪：当 $d > n$ 时，$\Alt^d V$ 退化为 $0$，这是因为 $V$ 中基底数量不足以让楔积的各位置线性无关．同样的事情发生在 $\mathbb S_\lambda V$ 上：当 $\lambda$ 的长度超过 $n$ 时，$\mathbb S_\lambda V$ 退化为 $0$．这是因为 $b_\lambda$ 交错化使得 $\lambda$ 第一列对应的张量位置一旦线性相关就退化为 $0$，而 $\lambda$ 的第一列长度大于 $n = \dim V$ 使得这一情况必然发生．
:::

:::{.remark}

## Schur Functor

$\mathbb S_\lambda$ 其实是个函子：定义 $\mathbb S_\lambda$ 在线性映射 $f: V \to W$ 上的作用 $\mathbb S_\lambda f$ 为 $f^{\otimes d} : V^{\otimes d} \to W^{\otimes d}$ 限制到 $\mathbb S_\lambda V \to \mathbb S_\lambda W$ 上．容易验证 $\mathbb S_\lambda W$ 一侧是良定的．
:::

:::{.remark}

## 我更喜欢 $\mathcal S_d$ 右作用

You are absolutely right to question that! 本来 $V^{\otimes d}$ 上的自然的 $\mathcal S_d$ 作用就应该右边．那能不能考虑把 $V^{\otimes d}$ 做成 $(G, \mathcal S_d)$-双边表示分解？答案是能，分解会变成
$$
V^{\otimes d} \cong \bigoplus_{\lambda \vdash d} \Hom_{\mathbb C}(V_\lambda, V^{\otimes d} \cdot c_\lambda)
$$
这里 $\Hom_{\mathbb C}$ 上的左作用是 $V^{\otimes d} \cdot c_\lambda$ 上的 $G$-左作用，右作用是 $V_\lambda$ 的 $\mathcal S_d$-左作用．

需要注意的是在 $\mathcal S_d$-右作用风格表述，之前定义的 $\mathbb S_\lambda V$ 写作
$$
\mathbb S_\lambda V = a_\lambda b_\lambda \cdot V^{\otimes d} = \left( \sum_{\sigma} \sum_{\tau} \sgn(\tau) \sigma \tau \right) \cdot V^{\otimes d} = V^{\otimes d} \cdot \left( \sum_{\sigma} \sum_{\tau} \sgn(\tau) \tau^{-1} \sigma^{-1} \right) = V^{\otimes d} \cdot b_\lambda a_\lambda
$$
可以看到和双边版本这里的 $V^{\otimes d} \cdot c_\lambda$ 微妙地掉了个转．好消息是因为 Young 对称化子的幂等性
$$
V^{\otimes d} \cdot a_\lambda b_\lambda \xrightarrow{- \cdot a_\lambda} V^{\otimes d} \cdot b_\lambda a_\lambda \xrightarrow{- \cdot b_\lambda} V^{\otimes d} \cdot a_\lambda b_\lambda
$$
故这两个 $G$-模是同构的，不小心混用了也问题不大．
:::

现在来给出证明．利用 $\mathbb C[\mathcal S_d]$ 左模版本的 Peter--Weyl 定理
$$
\mathbb C[\mathcal S_d] \cong \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C V_\lambda^*
$$
可以借助已经清楚的 $\mathcal S_d$-表示论将 $V^{\otimes d}$ 分解成 $\mathcal S_d$-不可约成分
$$
\begin{aligned}
V^{\otimes d}
&\cong \mathbb C[\mathcal S_d] \otimes_{\mathbb C[\mathcal S_d]} V^{\otimes d} \\
&\cong \left( \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C V_\lambda^* \right) \otimes_{\mathbb C[\mathcal S_d]} V^{\otimes d} \\
&\cong \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C \left( V_\lambda^* \otimes_{\mathbb C[\mathcal S_d]} V^{\otimes d} \right) \\
&\cong \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C \Hom_{\mathbb C[\mathcal S_d]}(V_\lambda, V^{\otimes d}) \\
&=     \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C \Hom_{\mathbb C[\mathcal S_d]}(\mathbb C[\mathcal S_d] c_\lambda, V^{\otimes d}) \\
&\cong \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C \left( c_\lambda \cdot V^{\otimes d} \right) \\
&=     \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C \mathbb S_\lambda V
\end{aligned}
$$
这就是 Schur--Weyl 分解．注意 $G$-表示同构 $\Hom_{\mathbb C[\mathcal S_d]}(V_\lambda, V^{\otimes d}) \cong c_\lambda \cdot V^{\otimes d}$ 是使用以下一般事实的结果：

:::{#prp-hom-idem}

对任意含幺环 $R$，$R$-模 $M$ 和幂等元 $e \in R$，我们有典范的 $Z_R(e)$-模同构
$$
\begin{aligned}
e M &\cong \Hom_R(Re, M) \\
e m &\mapsto (re \mapsto rem)
\end{aligned}
$$
这里 $Z_R(e)$ 是环 $R$ 中所有与 $e$ 交换的元素构成的子环．
:::

:::{.remark}

## 双边版本的 Schur--Weyl 对偶证明

用双边版本的 Peter--Weyl 定理张量积在 $V^{\otimes d}$ 右侧：
$$
\begin{aligned}
V^{\otimes d}
&\cong V^{\otimes d} \otimes_{\mathbb C[\mathcal S_d]} \mathbb C[\mathcal S_d] \\
&\cong V^{\otimes d} \otimes_{\mathbb C[\mathcal S_d]} \left( \bigoplus_{\lambda \vdash d} V_\lambda \otimes_\mathbb C V_\lambda^* \right) \\
&\cong \bigoplus_{\lambda \vdash d} V^{\otimes d} \otimes_{\mathbb C[\mathcal S_d]} V_\lambda \otimes_\mathbb C V_\lambda^* \\
&\cong \bigoplus_{\lambda \vdash d} V^{\otimes d} \otimes_{\mathbb C[\mathcal S_d]} \mathbb C[\mathcal S_d] c_\lambda \otimes_\mathbb C V_\lambda \\
&\cong \bigoplus_{\lambda \vdash d} \left( V^{\otimes d} \cdot c_\lambda \right) \otimes_\mathbb C V_\lambda^* \\
&\cong \bigoplus_{\lambda \vdash d} \Hom_\mathbb C(V_\lambda, V^{\otimes d} \cdot c_\lambda)
\end{aligned}
$$
:::

## Schur--Weyl 对偶

### 对偶何在？

至此 Schur--Weyl 分解的工作已经完成——其实根本没有用到 $G$ 的任何性质．对偶何在？现在这个分解可一点都不对偶：$V_\lambda$ 是全体 $\mathcal S_d$ 的不可约表示，但对 $G$-表示 $\mathbb S_\lambda V$ 我们一无所知．

事实上，对偶仅在取特殊的群或代数时体现．

先再将这里的讨论推进一步，没有使用 $G$ 的性质意味着，对任何左作用在 $V^{\otimes d}$ 上的结合代数 $A$，只要它与 $\mathcal S_d$ 在 $V^{\otimes d}$ 上的作用交换，上述分解同样提供了 $A \otimes_{\mathbb C} \mathbb C[\mathcal S_d]$-左模意义下的分解．特别地，$A$ 可以是：

- 群 $G$ 左作用在 $V$ 上，这里代数取群代数 $\mathbb C[G]$．$G$ 在 $V^{\otimes d}$ 上的作用由如下对角映射给出：
  $$
  \begin{aligned}
  \Delta_{\GL}^d : G &\to \End_{\mathbb C}(V^{\otimes d}) \\
  g &\mapsto \rho_{V}(g) \otimes \dots \otimes \rho_{V}(g)
  \end{aligned}
  $$
  Schur--Weyl 分解在 $G \times \mathcal S_d$-表示意义下成立．

- 李代数 $\mathfrak{g}$ 左作用在 $V$ 上，这里代数取李代数的泛包络代数 $U(\mathfrak{g})$．$\mathfrak{g}$ 在 $V^{\otimes d}$ 上的作用由如下对角映射给出：
  $$
  \begin{aligned}
  \Delta_{\gl}^d : \mathfrak{g} &\to \End_{\mathbb C}(V^{\otimes d}) \\
  x &\mapsto \rho_V(x) \otimes \id_V \otimes \dots \otimes \id_V + \dots + \id_V \otimes \id_V \otimes \dots \otimes \rho_V(x)
  \end{aligned}
  $$
  Schur--Weyl 分解在 $U(\mathfrak{g}) \otimes \mathbb C[\mathcal S_d]$-模意义下成立．

我们尤其关注一般线性群 $\GL(V)$ 和一般线性李代数 $\gl(V)$ 作用在 $V$ 上的情形．这两个情形将反映出 $\GL(V)$ 和 $\mathcal S_d$ 不可约（代数）表示间的对偶关系——真正使得 Schur--Weyl 对偶的“对偶”二字名副其实．

### 双交换化结构

如上所述，我们关心任何作用在 $V^{\otimes d}$ 上与 $\mathbb C[\mathcal S_d]$ 作用交换的结合代数 $A$——即要求 $A$ 在 $\End_{\mathbb C}(V^{\otimes d})$ 的像落在 $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$ 中．

不妨先看看 $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$ 是什么——我们还真能处理它：刚刚已经对 $V^{\otimes d}$ 做好了 $\mathcal S_d$-不可约成分的分解，立刻大力 Schur 引理拆掉这个 $\End$：
$$
\begin{aligned}
\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})
&\cong \End_{\mathbb C[\mathcal S_d]} \left( \bigoplus_{\lambda \vdash d} V_\lambda \otimes_{\mathbb C} \mathbb S_\lambda V \right) \\
&\cong \bigoplus_{\lambda \vdash d} \End_{\mathbb C[\mathcal S_d]}(V_\lambda \otimes_{\mathbb C} \mathbb S_\lambda V) & \text{by Schur's lemma} \\
&\cong \bigoplus_{\lambda \vdash d} (\mathbb S_\lambda V)^* \otimes_{\mathbb C} V_\lambda^* \otimes_{\mathbb C[\mathcal S_d]} V_\lambda \otimes \mathbb S_\lambda V \\
&\cong \bigoplus_{\lambda \vdash d} (\mathbb S_\lambda V)^* \otimes_{\mathbb C} \End_{\mathbb C[\mathcal S_d]}(V_\lambda) \otimes \mathbb S_\lambda V \\
&\cong (\mathbb S_\lambda V)^* \otimes_{\mathbb C} \mathbb S_\lambda V & \text{by Schur's lemma} \\
&\cong \bigoplus_{\lambda \vdash d} \End_{\mathbb C}(\mathbb S_\lambda V)
\end{aligned}
$$
上述分解每一步都在 $\mathbb C$-代数意义下成立（中间几步中环内部的乘法是在对偶空间配对意义下定义）．竟然直接把 $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$ 分解干净了：

:::{.remark}

## 一点有限维半单结合代数表示论

记 $A = \bigoplus_{\lambda \vdash d} A_\lambda$，这里 $A := \End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$，$A_\lambda := \End_{\mathbb C}(\mathbb S_\lambda V)$．

- 矩阵代数 $A_\lambda$ 单：即无非平凡双边理想，使用基本矩阵转移行列论证即可．

- 任何 $A$-表示 $V$ 半单：对 $V$ 左侧 $A \otimes_A -$ 后分配律变成一系列 $A_\lambda \otimes_A V$ 的直和，这是矩阵代数 $A_\lambda$ 的表示，由矩阵代数的表示论知道 $A_\lambda \otimes_A V$ 是 $A_\lambda$ 的唯一的不可约表示 $\mathbb S_\lambda V$ 的若干份直和．

- $A$ 的不可约表示全体恰为 $\mathbb S_\lambda V$：这是上一条的副产物．
:::

因此要是取 $A = \End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$ 作用在 $V^{\otimes d}$ 上，Schur--Weyl 分解
$$
V^{\otimes d} \cong \bigoplus_{\lambda \vdash d} V_\lambda \otimes_{\mathbb C} \mathbb S_\lambda V
$$
就真的体现出对偶：作为 $A \otimes \mathbb C[\mathcal S_d]$-模分解将 $V^{\otimes d}$ 分解成 $A$ 的不可约表示 $\mathbb S_\lambda V$ 和 $\mathcal S_d$ 的不可约表示 $V_\lambda$ 的张量积．

:::{.remark}

## 双交换化结构

$A := \End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$ 与 $B := \text{image of } \mathbb C[\mathcal S_d] \text{ in } \End_{\mathbb C}(V^{\otimes d})$ 的对偶关系有如下一般的表述：

设 $V$ 是有限维线性空间，$B$ 是 $\End_{\mathbb C}{V}$ 的半单结合子代数，半单分解 $B = \bigoplus_i \End(W_i)$，其中 $W_i$ 是 $B$ 的全体不可约表示．记 $A := \End_B V$，则

- $A$ 也是半单结合代数，具有分解 $A = \bigoplus_i \End(V_i)$，其中 $U_i := \Hom(W_i, V)$ 是 $A$ 的全体不可约表示；
- $V$ 作为 $A \otimes_{\mathbb C} B$-模分解为 $\bigoplus_i U_i \otimes_{\mathbb C} W_i$，其中 $V_i$ 是 $A$ 的不可约表示，$W_i$ 是 $B$ 的不可约表示；
- $B = \End_A V$，即 $A$ 与 $B$ 作为 $\End_{\mathbb C} V$ 的子代数互为交换子．

其中第一条和第二条使用与前面类似方法已经完成证明；第三条是 Schur--Weyl 对偶“对偶”二字的另一核心表述，对 $\End_A V$ 重新用 $V$ 的分解和 Schur 引理拆掉 $\End$ 就可还原出 $\bigoplus_i \End_{\mathbb C}(W_i) = B$，请读者练习．
:::

### $\gl$ 与 $\GL$ 的作用

刚刚做的太急，甚至没来得及考虑 $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$ 里面具体装了些什么．第一个重要观察是

- $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d}) = \Sym^d \End_{\mathbb C}(V)$

  这是因为 $\End_{\mathbb C}(V^{\otimes d}) = (\End_{\mathbb C}V)^{\otimes d}$，且交换性实质要求变换作用效果无关于张量位置——即在每个位置作用效果相同．

这是有趣的事情——研究张量积 $V^{\otimes d}$ 的分解最终引导我们去研究一个更大的张量积 $(\End_{\mathbb C} V)^{\otimes d}$ 的对称部分．现在考察 $\gl(V)$ 和 $\GL(V)$ 作为 $V^{\otimes d}$ 上的作用在其中扮演的角色．

#### 群 $\GL$

回忆群 $\GL(V)$ 在 $V^{\otimes d}$ 上的作用方式记作 $\Delta_{\GL}^d : \GL(V) \to \End_{\mathbb C}(V^{\otimes d})$．

:::{#prp-group-span}

- 全体 $\{\Delta_{\GL}^d(g) : g \in \GL(V) \}$ 线性生成了 $\Sym^d \End_{\mathbb C}(V)$．
- 群代数 $\mathbb C[\GL(V)]$ 在 $V^{\otimes d}$ 上的像恰好是 $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$．
- $\mathbb S_\lambda V$ 作为 $\GL(V)$-表示不可约；Schur--Weyl 系列定理描述了 $\GL(V)$ 和 $\mathcal S_d$ 在 $V^{\otimes d}$ 上的对偶关系．
:::

:::{.proof}

只需证第一条．考虑多重线性版本的极化恒等式
$$
x_1 \dots x_d = \frac{1}{d!} \sum_{S \subseteq \{ 1, \dots, d \}} (-1)^{d - |S|} \left( \sum_{i \in S} x_i \right)^d
$$
这意味着全体线性多项式的 $d$ 次幂足以线性生成全体 $d$ 次多项式．熟记对称代数的全体线性泛函就是多项式环，故这等价于说 $\End_{\mathbb C}(V)$ 在 $\Delta_{\GL}^d$ 下的像为 $\Sym^d \End_{\mathbb C}(V)$．

假如 $\GL(V)$ 在 $\Delta_{\GL}^d$ 的像没有线性生成 $\Sym^d \End_{\mathbb C}(V)$，则应存在 $\Sym^d \End_{\mathbb C}(V)$ 上的非零线性泛函（即 $d$ 次齐次多项式）$h$ 使得这像在 $h$ 下被消灭，即 $h \circ \Delta_{\GL}^d$ 消灭 $\GL(V)$．注意 $h : \Sym^d \End_{\mathbb C}(V) \to \mathbb C$ 和 $\Delta_{\GL}^d : \End_{\mathbb C}(V) \to \Sym^d \End_{\mathbb C}V$ 都是纯代数映射，Zariski 拓扑意义下连续，又 $\GL(V)$ 在 $\End_{\mathbb C}(V)$ 中 Zariski 稠密，故 $h \circ \Delta_{\GL}^d$ 的消灭性从 $\GL(V)$ 扩展到 $\End_{\mathbb C}(V)$．于是 $\End_{\mathbb C}(V)$ 在 $\Delta_{\GL}^d$ 下的像 $\Sym^d \End_{\mathbb C}(V)$ 被 $h$ 消灭——但 $h$ 非零，这不可能发生．
:::

:::{.remark}

另一条路线是直接证明任何有限维线性空间 $V$ 上的齐次对称部分 $\Sym^d \End_{\mathbb C}(V)$ 作为 $\GL(V)$ 模都不可约．
:::

#### 李代数 $\gl$

回忆李代数 $\gl(V)$ 在 $V^{\otimes d}$ 上的作用方式记作 $\Delta_{\gl}^d : \gl(V) \to \End_{\mathbb C}(V^{\otimes d})$．

:::{#prp-gl-span}

- 全体 $\{\Delta_{\gl}^d(x) : x \in \gl(V) \}$ 结合代数地生成出 $\{\Delta_{\GL}^d(g) : g \in \GL(V) \}$，进而由 [@prp-group-span] 结合代数地生成整个 $\Sym^d \End_{\mathbb C}(V)$．
- 泛包络代数 $U(\gl(V))$ 在 $V^{\otimes d}$ 上的像恰好是 $\End_{\mathbb C[\mathcal S_d]}(V^{\otimes d})$．
- $\mathbb S_\lambda V$ 作为 $\gl(V)$-表示不可约；Schur--Weyl 系列定理描述了 $\gl(V)$ 和 $\mathcal S_d$ 在 $V^{\otimes d}$ 上的对偶关系．
:::

:::{.proof}

只需证第一条．对任意 $x \in \gl(V)$，考虑记
$$
x_i := \id_V \otimes \dots \otimes \rho_{V}(x) \otimes \dots \otimes \id_V \in (\End_{\mathbb C} V)^{\otimes d}
$$
其中 $x$ 在第 $i$ 个位置，则 $x_1, \dots, x_d$ 交换且
$$
\begin{aligned}
\Delta_{\gl}^d(x) &= x_1 + \dots + x_d \\
\Delta_{\gl}^d(x^k) &= x_1^k + \dots + x_d^k \\
\Delta_{\GL}^d(x) &= x_1 \cdots x_d
\end{aligned}
$$
因此 $\Delta_{\GL}^d(x)$ 作为 $d$ 元基本对称多项式之一，可以写成关于幂和对称多项式 $\Delta_{\gl}^d(x), \dots, \Delta_{\gl}^d(x^d)$ 的多项式表达．这就是结合代数的生成．
:::

## $\GL(V)$ 的代数表示

关于 $\mathbb S_\lambda V$ 的故事还没有讲完．我们刚刚建立的对偶确实完整刻画了 $\GL(V)$ 和 $\mathcal S_d$ 在 $V^{\otimes d}$ 上作用的关系，并分类了 $\GL(V)$ 作用在 $V^{\otimes d}$ 上的不可约子表示——但这都是作为 $\End_{\mathbb C} (V^{\otimes d})$ 的子代数在研究，而 $\GL(V)$（或 $\gl(V)$）完全可能作用更多的空间上，进而产生更多的不可约表示．

在每个 $V^{\otimes d}$ 上的讨论已经证明全体 $\mathbb S_\lambda V$ 确为 $\GL(V)$ 的不可约表示，但这就是全部了吗？还会有其它 $\GL(V)$ 的不可约表示吗？

:::{.remark}

## 约化代数群和半单李代数的表示论

答案是：如果考虑 $\GL(V)$ 的代数表示的话，$\mathbb S_\lambda V$ 就几乎是全部了．这是 A 型约化代数群的表示论．

$\GL(V)$ 的代数表示即是研究代数群同态 $\GL(V) \to \GL(W)$．$d$ 一下立刻会获得李代数同态 $\gl(V) \to \gl(W)$，因此代数群的表示论和其对应李代数的表示论联系密切．这就又涉及 $A$ 型李代数 $\gl_n$ 或 $\sl_n$ 的表示论．

这个天坑就不在这里继续挖了．
:::
