---
title: 梦话集
subtitle: Rambling Words
author: sun123zxy
date: 2026-04-19
lang: zh
abstract: 内容或包含医疗建议．

categories:
  - math

collections:
  - casual

number-sections: true

format:
  html: default
---

## 域，Galois，代数数论

\newcommand{\GL}{\operatorname{GL}}
\newcommand{\Hom}{\operatorname{Hom}}

- 有限扩张代数，单代数扩张有限，有限可分扩张单．

- Hilbert Nullstellensatz：有限生成 $k$-代数 $A$ 是域，则扩张 $A/k$ 有限．

- 代数闭正规，特征零可分．

- 正规的域扩张够大，包含所有代数元的共轭根．

- 可分的域扩张够细，扩域足够大就能将不同的根分离．

  - 因此在足够大的扩域上数嵌入数可以判定可分性．

- Galois 扩张有限可分正规，具有上述好根性质，故可用根的置换 / 自同构群刻画域的结构．

## 表示论

- 半单李代数的有限维复表示是半单的，正如诺特环的有限生成模也是诺特的．

  - 注意诺特环可以分解为连通分量的直积．

- 半单李代数都是 $\mathfrak{sl}_2$ 粘成的．

### 内积

内积是 $V \to V^*$ 的同构．

- 群表示论中：

  平均化搓出 $G$-不变内积，$V \to V^*$ 是 $G$-共轭线性同构．用于半单性证明．

  $(V,W) \mapsto \dim \Hom_G(V,W)$ 是 $G$-表示 Grothendieck 群（作为 $\mathbb Z$-模）上的内积，Schur 定理给出了正交基，特征标是 Grothendieck 群的显式实现．

- 李代数表示论中是 Killing 型，$V \to V^*$ 是 $\mathfrak g$-同构．

- 代数数论中是 $(x,y) \mapsto \operatorname{Tr}_{K/\mathbb Q}(xy)$．用于定义 different ideal，判别式，构造对偶基，证明 $\mathcal O_K$ 有限生成自由 $\mathfrak Z$-模．

- Hilbert 空间自反，$H^*$ 与 $H$ 共轭线性同构，Reisz 表示定理保证同构性．

### $q$-deformation

- $$
  \begin{matrix}
  [n] & n \\
  P^{n-1} \mathbb F_q & [n]_q
  \end{matrix}
  $$

- $$
  \begin{matrix}
  S_n & [n] \to [n] & n! \\
  \operatorname{PGL}_n(\mathbb F_q) & P^{n-1} \mathbb F_q \to P^{n-1} \mathbb F_q & [n]_q!
  \end{matrix}
  $$

- $$
  \begin{matrix}
  A_n & \ker(\operatorname{sgn}) \\
  \operatorname{PSL}_n(\mathbb F_q) & \ker(\det)
  \end{matrix}
  $$

- $$
  \begin{matrix}
  G/B & \text{完全旗簇} & [n]_q! \\
  [n] & \text{完全旗簇} & n!
  \end{matrix}
  $$
