---
title: "On Determining Prime Spectra of Some Coordinate Rings"
subtitle: "with Applications to the Two Squares Theorem"
date: 2025/05/16
date-modified: 2025/05/16
author: "sun123zxy"
bibliography: index.bib
lang: en
abstract: "Thanks to the powerful tools borrowed from commutative algebra, we show a general approach to determine the prime spectra of some coordinate rings by examples. As we determine the spectrum of the Gaussian integers, a proof of the famous two squares theorem emerges without tricky techniques."

categories:
  - math
  - algebra
collection:
  - dedicated

number-sections: true

format:
  html: default
---

\newcommand{\Spec}{\operatorname{Spec}}
\renewcommand{\mapsto}{\rightarrowtail}
\newcommand{\mapsfrom}{\leftarrowtail}
\newcommand{\coresp}{\longleftrightarrow}
\newcommand{\V}{\operatorname{V}}
\newcommand{\D}{\operatorname{D}}
\renewcommand{\i}{\mathrm i}
\newcommand{\N}{\operatorname{N}}

\newcommand{\injto}{\hookrightarrow}
\newcommand{\surjto}{\twoheadrightarrow}
\newcommand{\bijto}{\hookrightarrow\mathrel{\mspace{-15mu}}\rightarrow}

In this article, all rings are commutative with $1$ unless otherwise specified. [@atiyah_commalg] is referred for terms not defined here.

Recall that ED^[Euclidean domain] implies PID^[principal ideal domain] implies UFD^[unique factorization domain].

## Correspondences of prime spectra under quotients and localizations

Before start, we review some basic facts about prime ideals. These facts turn out to be useful in the study of prime spectra of specific rings.

Recall that the spectrum $\Spec R$ of a ring $R$ consists of all prime ideals of $R$. The Zariski topology is defined on $\Spec R$ by declaring the closed sets to be of the form $\V(\mathfrak a) := \{ \mathfrak p \in \Spec R : \mathfrak p \supseteq \mathfrak a \}$ for any ideal $\mathfrak a$ of $R$. Equivalently, one can define the Zariski topology by the topological base consisting of the open sets $\D(f) := \{ \mathfrak p \in \Spec R : f \notin \mathfrak p \}$ for any $f \in R$.

:::{#prp-preimage-preserve-prime}

## Preimage preserves prime ideals

Let $\varphi: R \to S$ be any ring homomorphism. Let $\mathfrak p$ be a prime ideal of $S$, then $\varphi^{-1}(\mathfrak p)$ is a prime ideal of $R$.
:::

:::{#cor-subring-preserve-prime}

## Subring preserves prime ideals

Let $R$ be a ring and $S$ be a subring of $R$. Let $\mathfrak p$ be a prime ideal of $R$, then $\mathfrak p \cap S$ is a prime ideal^[Not true for maximal ideals. e.g. $(x)$ is an ideal of $R := \mathbb C[x]$, but it is contained in a larger ideal $(2,x)$ in the subring $S := \mathbb Z[x] \subset R$.] of $S$.
:::

:::{#thm-quotient-ideal-correspondence}

## Ideal correspondence theorem for quotient rings

Let $R$ be a ring and $\mathfrak a$ be an ideal of $R$. Then there is a one-to-one correspondence:
$$
\{ \text{ideals of } R / \mathfrak a \} \coresp \{ \text{ideals of } R \text{ containing } \mathfrak a \} 
$$
Moreover, prime ideals^[In fact, also maximal ideals] are also one-to-one corresponded: In fact, the natural quotient homomorphism $\pi: R \to R / \mathfrak a$ induces a Zariski-topological closed embedding:
$$
\begin{aligned}
\Spec \pi : \Spec R / \mathfrak a &\bijto \V(\mathfrak a) \subseteq \Spec R \\
\mathfrak q &\mapsto \pi^{-1} (\mathfrak q) \\
\mathfrak p / \mathfrak a &\mapsfrom \mathfrak p
\end{aligned}
$$
where $\V (\mathfrak a) := \{ \mathfrak p \in \Spec R : \mathfrak p \supseteq \mathfrak a \}$ is the set of prime ideals containing $\mathfrak a$.
:::

The proof is straightforward and thus omitted.

:::{#thm-localization-ideal-correspondence}

## Spectrum correspondence theorem for localizations of rings

Let $R$ be a ring with and $S$ be a multiplicatively closed subset of $R$. Then the localization homomorphism $\iota : R \to S^{-1} R$ induces a Zariski-topological open embedding:
$$
\begin{aligned}
\Spec \iota : \Spec S^{-1} R &\bijto \D(S) \subseteq \Spec R \\
                 \mathfrak q &\mapsto \iota^{-1} (\mathfrak q) \\
          S^{-1} \mathfrak p &\mapsfrom \mathfrak p
\end{aligned}
$$
where $\D(S) := \{ \mathfrak p \in \Spec R : \mathfrak p \cap S = \varnothing \}$ is the set of prime ideals disjoint from $S$.
:::

:::{.remark}

Do note that here we commit a terrible abuse of notation: $\D(S)$ is not the complement of $\V(S) := \bigcap_{f \in S} \V(f)$!
:::

:::{.remark}

Correspondence of arbitrary ideals is not mentioned in the statement because of its subtlety: $\mathfrak a \mapsto S^{-1} \mathfrak a$ is indeed surjective, but is not injective because in $S^{-1} R$ one can use elements in $S$ to "cancel out" the numerators. See the proof for details.
:::

:::{.proof}

For simplicity, we introduce some terminology first:

- For any ideal $\mathfrak a$ of $R$ disjoint from $S$, let $\mathfrak a^\mathrm e := S^{-1} \mathfrak a$ denote the extension of $\mathfrak a$. $\mathfrak a^\mathrm e$ consists of all fractions whose numerators are in $\mathfrak a$.

- For any ideal $\mathfrak b$ of $S^{-1} R$, let $\mathfrak b^\mathrm c := \iota^{-1} (\mathfrak b)$ denote the contraction of $\mathfrak a$. $\mathfrak b^\mathrm c$ consist of all numerators of fractions in $\mathfrak b$.

Extension and contraction are, to some extent, inverse operations (but not genuinely before we restrict to the prime ideals):

- $$\mathfrak b^\mathrm{ce} = \mathfrak b$${#eq-bce}

  Every ideal of $S^{-1} R$ is an extended ideal: extended from the ideal consisting of its numerators.
  
- $$\mathfrak a^\mathrm{ec} = \{ c \in R: \exists u \in S,\, c u \in \mathfrak a \}$${#eq-aec}

  $\mathfrak a^\mathrm{ec}$ consists of those elements in $R$ that may reach $\mathfrak a$ after some multiplication by $S$. To show this,
  $$
  \begin{aligned}
  c \in \mathfrak a^\mathrm{ec}
  &\iff \exists a \in \mathfrak a,\, \exists s \in S,\, \frac c 1 = \frac a s \\
  &\iff \exists a \in \mathfrak a,\, \exists s \in S,\, \exists t \in S,\, (cs-a) t = 0 \\
  &\iff \exists s \in S,\, \exists t \in S,\, cst \in \mathfrak a \\
  &\iff \exists u \in S,\, c u \in \mathfrak a
  \end{aligned}
  $$

The following is where the "disjoint from $S$" requirement shows up:

- $$\mathfrak a^\mathrm{ec} = R \iff S \cap \mathfrak a \neq \varnothing$${#eq-disjoint-from-S}

  The part of $\impliedby$ is easy. To establish the $\implies$ part, pick $c = 1$, then $\exists u \in S,\, u = 1 u \in \mathfrak a$ and hence $S \cap \mathfrak a \neq \varnothing$.
  
  The statement is equivalent of saying that for any proper ideal $\mathfrak b$ of $S^{-1} R$, its contraction must be disjoint from $S$ --- otherwise its numerators are entire $R$, resulting $\mathfrak b = S^{-1} R$ being not proper. In fancy symbols,
  $$
  \mathfrak b^\mathrm c = R \iff \mathfrak b^\mathrm{cec} = R \iff S \cap \mathfrak b^\mathrm c \neq \varnothing
  $$

  - As a consequence, contractions of prime ideals in $S^{-1} R$ are disjoint from $S$, i.e. fall into $\D(S)$.

We now focus on prime ideals.

- Extension preserves prime ideals: Extension is $S^{-1}$, preserves prime ideals by trivial verification.

- Contraction preserves prime ideals: Contraction is $\iota^{-1}$, preserves prime ideals by [@prp-preimage-preserve-prime].

- For any $\mathfrak p \in \Spec(R)$, we have $\mathfrak p^\mathrm{ec} = \mathfrak p$.

  By [@eq-aec], $\mathfrak p^\mathrm{ec} = \{ c \in R: \exists u \in S,\, c u \in \mathfrak p \}$. But $\mathfrak p$ is prime and disjoint from $S$, thus equivalently $c \in p$ and in turn $\mathfrak p^\mathrm{ec} = \mathfrak p$.

Thus extension and contraction are genuinely inverse operations between $\Spec S^{-1} R$ and $\D(S)$, and the one-to-one correspondence is established. Below we turn to the topological part of the correspondence.

- Extension is Zariski-continuous: For any $a \in R$,
  $$
  \begin{aligned}
  \left( \D_R(a) \right)^\mathrm e
  &= \{ \mathfrak p \in \Spec R : a \notin \mathfrak p \}^\mathrm e \\
  &= \{ \mathfrak q \in \Spec S^{-1} R : a \notin \mathfrak q \} \\
  &= D_{S^{-1} R}(a) \\
  \end{aligned}
  $$

- Contraction is Zariski-continuous: For any $a/s \in S^{-1}R$,
  $$
  \begin{aligned}
  \left( \D_{S^{-1}R}(\frac a s) \right)^\mathrm c
  &= \{ \mathfrak q \in \Spec S^{-1} R : \frac a s \notin \mathfrak q \}^\mathrm c \\
  &= \{ \mathfrak q \in \Spec S^{-1} R : a \notin \mathfrak q^\mathrm c \}^\mathrm c \\
  &= \{ \mathfrak p \in R : a \notin \mathfrak p \} \\
  &= \D_R(a) \\
  \end{aligned}
  $$

Thus the correspondence is actually a Zariski-homeomorphism between $\Spec S^{-1} R$ and $\D(S)$. Note that $\D(S)$ is open in $\Spec R$. Thus we are done.
:::

:::{#exr-localization-preserves}

By the (partial) correspondence of ideals shown in the proof of the theorem above, show that a localization preserves the property of being an integral domain, a PID and a Noetherian ring.
:::

:::{#prp-product-ideal-correspondence}

## Ideals of a finite product of rings

Let $R_1, \dots, R_n$ be $n$ rings. Then all the ideals of $\prod_{k=1}^n R_k$ are exactly the ideals of the form $\prod_{k=1}^n \mathfrak a_k$ where $\mathfrak a_1, \dots, \mathfrak a_n$ are ideals of $R_1, \dots, R_n$ respectively.

Among them, prime ideals are exactly those products where prime ideals occur once while all the other factors are entire rings. In Zariski-topological words, $\Spec \prod_{k=1}^n R_k \cong \bigsqcup_{k=1}^n \Spec R_k$.
:::

:::{.proof}

Let $e_i$ be the identity of $R_i$. For the ideal correspondence, consider multiplication by $e_i$ and then taking the sum. For the prime ideals, consider $e_i e_j = 0 \in \mathfrak p$ for all $i \neq j$.
:::

:::{.remark}

Note that above is not true for infinite products. For example, in $\prod_{i=1}^\infty \mathbb Z$, the ideal formed by elements whose components are all-but-one zero, is not a product of ideals. In fact, if we view ideals as $R$-modules, this reflects the fact that in the category of $R$-modules, direct products are not exactly the same as direct sums.
:::

## The prime spectrum of the polynomial ring over a PID

Our inspiring example is $\mathbb Z[x]$, the polynomial ring over the integers. The theorem below captures the essence of the way to determine the prime spectrum of $\mathbb Z[x]$.

:::{#prp-prime-spectrum-poly-over-pid}

## The prime spectrum of the polynomial ring over a PID

Let $R$ be a PID and $K$ be its field of fractions. Then $\Spec R[x]$ consists of

- $K[x]$-identified prime ideals:
  - The zero ideal $(0)$
  - $(f)$ where $f(x) \in R[x]$ is an irreducible polynomial of degree $\geq 1$
- $R/pR[x]$-identified prime ideals (where $p$ is a prime element of $R$):
  - $(p)$
  - $(p, f)$ where $f(x) \in R[x]$ is irreducible when viewed in $R/pR[x]$
:::

:::{.remark}

We require $R$ to be a PID to make sure that $(p) = pR$ is a maximal ideal and $R/pR$ is a field.
:::

:::{.remark}

Note that $R/pR[x]$-identified prime ideals are exactly the maximal ideals of $R[x]$. This actually reveals that $R[x]$ is of Krull dimension $2$.
:::

:::{.proof}

Note that $R \injto R[x]$ by mapping to constant polynomials. For any $\mathfrak p \in \Spec R[x]$, by [@cor-subring-preserve-prime], we have $\mathfrak p \cap R \in \Spec R$. As the spectrum of a PID, $\Spec R$ consists of all principal ideals generated by prime elements and the zero ideal $(0)$. Let's do them case by case:

- If $\mathfrak p \cap R = (0)$: Then $\mathfrak p \in \Spec R[x]$ is disjoint from $R$. By [@thm-localization-ideal-correspondence], the spectrum of $R[x]$ is in one-to-one correspondence with the spectrum of the localization $(R \setminus \{0\})^{-1} \left( R[x] \right) \cong K[x]$. Since $\Spec K[x]$ consists of:

  - The zero ideal $(0)$
  - $(f)$ where $f(x) \in K[x]$ is irreducible (and of degree $\geq 1$)

  They pull back (by contraction) to $\Spec R[x]$ to be:

  - The zero ideal $(0)$
  - $(f)$ where $f(x) \in R[x]$ is irreducible and of degree $\geq 1$

- If $\mathfrak p \cap R = p R$ for some prime $p$: Then $\mathfrak p \in \Spec R[x]$ contains $p R[x]$. By [@thm-quotient-ideal-correspondence], the spectrum of $R[x]$ is in one-to-one correspondence with the spectrum of the quotient ring $R[x] / p R[x] \cong R/pR[x]$. Since $\Spec R/pR[x]$ consists of:

  - The zero ideal $(0)$
  - $(f)$ where $f(x) \in R/pR[x]$ is an irreducible polynomial

  They pull back to $\Spec R[x]$ to be:

  - $(p)$
  - $(p, f)$ where $f(x) \in R[x]$ is irreducible when viewed in $R/pR[x]$
:::

As $\mathbb Z$ is a PID, the spectrum of $\mathbb Z[x]$ is determined:

:::{#cor-prime-spectrum-Zx}

## The prime spectrum of ${\mathbb Z[x]}$

$\Spec \mathbb Z[x]$ consists of

- The zero ideal $(0)$
- $(f)$ where $f(x) \in \mathbb Z[x]$ is an irreducible polynomial
- $(p, f)$ where $f(x) \in \mathbb Z[x]$ is irreducible when viewed in $\mathbb F_p[x]$
:::

The power of [@prp-prime-spectrum-poly-over-pid] does not stop here. Apply it to $K[x]$ for any field $K$, we have the following:

:::{#cor-prime-spectrum-kxy}

## The prime spectrum of ${K[x,y]}$

Let $K$ be a field. Then $\Spec K[x,y]$ consists of

- The zero ideal $(0)$
- $(f)$ where $f \in K[x,y]$ is an irreducible polynomial
- $(p, f)$ where $f \in K[x,y]$ is irreducible when viewed in $K[x,y] / (p(x))$
:::

This still looks complicated, but if we restrict to the case where $K$ is algebraically closed (e.g. $K = \mathbb C$), above results simplifies to that all prime ideals of $K[x,y]$ are the zero ideal, maximal ideals (points in $\mathbb C^2$) and principal ideals generated by irreducible polynomials.

## The prime spectrum of $\mathbb Z[i]$

Recall that $\mathbb Z[\i] := \mathbb Z[x] / (x^2 + 1) = \{a+ b\i : a,b \in \mathbb Z \}$. The (multiplicative) norm of $z := a + b \i$ is defined as $\N(z) := z \bar z = a^2 + b^2$. The units of $\mathbb Z[\i]$ are $\{ 1, -1, \i, -\i \}$, all of them are of norm $1$. By the regular argument of the Euclidean division, $\mathbb Z[\i]$ is an ED and hence a PID and a UFD.

:::{#prp-prime-spectrum-Zi}

## The prime spectrum of ${\mathbb Z[i]}$

The spectrum of Gaussian integers $\mathbb Z[\i] := \mathbb Z[x]/(x^2+1)$ consists of

- The zero ideal $(0)$
- $(p)$ where $p$ is a prime number s.t. $p \equiv 3 \pmod 4$
- $(z)$ where $z \in \mathbb Z[\i]$ and $\N(z) = p$ for some prime $p$ (which always satisfies $p=2$ or $p \equiv 1 \pmod 4$ by a trivial modular argument)

These principal ideals also determine all prime elements of $\mathbb Z[\i]$.
:::

:::{.proof}

By [@thm-quotient-ideal-correspondence], the spectrum of $\mathbb Z[\i]$ consists of the quotient image of the prime ideals of $\mathbb Z[x]$ containing $x^2+1$. We apply the previous result to $\mathbb Z[x]$ and get the following cases:

- For $\mathbb Q[x]$-identified prime ideals in $\mathbb Z[x]$:

  - The zero ideal $(0) \in \Spec \mathbb Z[x]$: does not contain $x^2+1$.

  - $(f) \in \Spec \mathbb Z[x]$ where $f(x) \in \mathbb Z[x]$ is an irreducible polynomial of degree $\geq 1$: Note that $x^2+1 \in \mathbb Z[x]$ is irreducible, thus $(f)$ does not contain $x^2+1$ unless $f(x) = x^2+1$. In this case, it identifies to $(0) \in \Spec \mathbb Z[\i]$.

- For $\mathbb F_p[x]$-identified prime ideals in $\mathbb Z[x]$:

  - $(p) \in \Spec \mathbb Z[x]$ where $p$ is a prime number: does not contain $x^2+1$.

  - $(p, f) \in \Spec \mathbb Z[x]$ where $f(x) \in \mathbb Z[x]$ is irreducible when viewed in $\mathbb F_p[x]$: $x^2+1 \in (p,f)_{\mathbb Z_[x]}$ iff $x^2+1 \in (f)_{\mathbb F_p[x]}$, thus below let's focus on this case and work in $\mathbb F_p[x]$.

We first check whether $x^2+1$ is irreducible in $\mathbb F_p[x]$:

- For $p \geq 3$, it is reducible iff $x^2 = -1$ has a solution in $\mathbb F_p$, i.e. $-1$ is a quadratic residue in $\mathbb F_p$, i.e. the multiplicative group $\mathbb F_p^\times$ has an element of order $4$. By the common sense that $\mathbb F_p^\times$ is cyclic of order $p-1$, we know it happens iff $p \equiv 1 \pmod 4$.

- For $p = 2$, Since $-1 = 1$, we have $x^2 + 1 = (x+1)^2$.

When $x^2 + 1$ is irreducible, i.e. when $p \equiv 3 \pmod 4$, $(x^2+1) \in \Spec \mathbb F_p[x]$ is the only prime ideal that contains $x^2+1$, which pulls back to $(p) \in \Spec \mathbb Z[\i]$.

When $x^2 + 1$ is reducible, i.e. when $p \equiv 1 \pmod 4$ or $p=2$, it can be written as $(x-a)(x+a)$ for some $a \in \mathbb F_p$ s.t. $a^2 = -1$. Thus $(x-a),\,(x+a) \in \Spec \mathbb F_p[x]$ are the prime ideals containing $x^2 + 1$. They pull back to $(p,\i - \tilde a) = (p,\tilde a - \i) \in \Spec \mathbb Z[\i]$ and $(p,\i + \tilde a) = (p, \tilde a + \i) \in \Spec \mathbb Z[\i]$, where $\tilde a \in \mathbb Z$ satisfies $\tilde a \bmod p = a$.

Since $\mathbb Z[\i]$ is a PID, we are supposed to rewrite above two prime ideals into principal ones, i.e. find $\gcd(p,\tilde a + \i)$ and $\gcd(p,\tilde a - \i)$ in $\mathbb Z[\i]$. Note that $p \nmid \tilde a + \i$ (by $p \nmid 1$ in the imaginary part) and $p \nmid \tilde a - \i$. But $p \mid 1 + \tilde a^2 = (\tilde a + \i)(\tilde a - \i)$, so (by that $\mathbb Z[\i]$ is a UFD) $p$ is not a prime element of $\mathbb Z[\i]$. It must decompose into two conjugate prime elements $p = z \bar z$ s.t. $N(z) = p$ and $z \mid \tilde a + \i$ and $\bar z \mid \tilde a - \i$. Thus $(p,\tilde a + \i) = (z)$ and $(p,\tilde a + \i) = (\bar z)$.

  - Note that when $p=2$ these two prime ideals are actually the same. It is
  $$
  (1+\i) = (1-\i) = (-1+\i) = (-1-\i) \in \Spec \mathbb Z[\i]
  $$
:::

### The two squares theorem

:::{#cor-prime-two-squares}

A prime number $p$ can be expressed as a sum of two squares iff $p = 2$ or $p \equiv 1 \pmod 4$.
:::

:::{#thm-two-squares}

## The two squares theorem

A positive integer $n$ can be expressed as a sum of two squares iff for every prime $p \equiv 3 \pmod 4$, $p$ has an even exponent in the prime factorization of $n$.
:::

:::{.proof}

For the forward direction, if $n = a^2 + b^2$, for any prime factor $p \equiv 3 \pmod 4$ of $n$, it suffices to show that $p$ divides both $a$ and $b$. Otherwise, $a^2,\,b^2 \not \equiv 0 \pmod p$. But we have $a^2 + b^2 \equiv 0 \pmod p$ thus $(a/b)^2 \equiv -1 \pmod p$, i.e. $-1$ is a quadratic residue in $\mathbb F_p$, which is impossible for $p \equiv 3 \pmod 4$.

For the backward direction, it suffices to assume $n$ is square-free. Say its decomposition is $n = \prod_{i=1}^k p_k$ where $p_i = 2$ or $p_i \equiv 1 \pmod 4$. By [@cor-prime-two-squares], $p_i = \N(z_i)$ for some $z_i \in \mathbb Z[\i]$. Thus $n = \prod_{i=1}^k p_k = \N \left( \prod_{i=1}^k z_i \right)$, thus a sum of two squares.
:::
