on:
  push:
    branches:
      - master

name: Render and Publish to Github Pages

# you need these permissions to publish to GitHub pages
permissions: 
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
          # To install LaTeX to build PDF book 
          # tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      # To update PATH
      - name: Set up TinyTeX via Quarto manually
        run: |
          quarto install tinytex --update-path

      # To ensure dvisvgm installed
      - name: Install dvisvgm via TinyTeX
        run: |
          tlmgr update --self
          tlmgr install dvisvgm
          tlmgr path add
          dvisvgm --help
      
      - name: Install mutool
        run: sudo apt-get install mupdf-tools
      
      # To import libraries in advance for tikz image generation
      - name: Prepare for TikZ rendering
        run: |
          echo "" >> temp.qmd
          quarto render temp.qmd --to=pdf --template=_assets/suntemp-tikz.tex
          rm temp.qmd

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Setup Python dependencies
        run: python3 -m pip install jupyter numpy matplotlib tabulate

      # - name: Render Quarto Project
      #   uses: quarto-dev/quarto-actions/render@v2
      
      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
