## 内积

本节旨在为 Maschke 定理的两种观点——分裂同态观点和不变内积观点提供证明和等价性阐述．

### 内积的第二重理解

线性空间 $V$ 上的内积 $\langle \cdot, \cdot \rangle_\gamma$ 是一个正定对称双线性型，作为映射可以写作 $\gamma \in \Hom(V, \Hom(V, \mathbb C))$．但注意到
$$
\Hom(V, V^*) = \Hom(V, \Hom(V, \mathbb C))
$$
故也可写作 $\gamma \in \Hom(V, V^*)$．因此，内积 $\langle \cdot, \cdot \rangle_\gamma$ 事实上给出一个线性空间到其对偶的同构 $\gamma : V \to V^*$ 满足 $\langle v, w \rangle_\gamma := \gamma(v)(w)$．

:::{.remark}

反过来，如果给定一个线性空间到其对偶的同构 $\gamma : V \to V^*$，我们可以定义 $\langle v, w \rangle_\gamma := \gamma(v)(w)$，但它现在只是一个非退化的双线性型，我们暂时无法顾及对称性和正定性的要求．
:::

使用 $V \to V^*$ 的记号讨论内积有很多好处．特别地，这方便我们使用交换图描述对保内积同态的要求．设 $U$, $V$ 是配备内积 $\gamma_U : U \to U^*$, $\gamma_V : V \to V^*$ 的线性空间，称线性映射 $\varphi : U \to V$ 是保内积的，如果它使得如下交换图成立：

:::{#fig-cd-inner-prod-hom}

```{tikz}
\begin{tikzcd}
	U & V \\
	{U^*} & {V^*}
	\arrow["\varphi", from=1-1, to=1-2]
	\arrow["{\gamma_U}"', from=1-1, to=2-1]
	\arrow["{\gamma_V}", from=1-2, to=2-2]
	\arrow["{\varphi^*}", from=2-2, to=2-1]
\end{tikzcd}
```
:::

这里 $\varphi^* : V^* \to U^*$ 是定义为 $f \mapsto (u \mapsto f(\varphi(u)))$ 的对偶映射．容易验证我们的定义和常见的要求 $\langle x, y \rangle_U = \langle \varphi(x), \varphi(y) \rangle_V$ 的定义等价：

:::{.proof}

$$
\begin{aligned}
\langle x, y \rangle_U
&= \gamma_U(x)(y) \\
&= \left(\varphi^* \circ \gamma_V \circ \varphi (x) \right) (y) \\
&= \gamma_V(\varphi(x))(\varphi(y)) \\
&= \langle \varphi(x), \varphi(y) \rangle_V
\end{aligned}
$$
:::

### 补空间

现在在此种观点下描述补空间．考虑线性空间正合列
$$
0 \longrightarrow U \xrightarrow{\iota} V \xrightarrow{\pi} W \longrightarrow 0
$$
此时 $\iota(U) \subseteq V$ 存在补空间等价于存在左分裂同态 $\psi \in V \to U$ 使得 $\psi \circ \iota = \id_U$：$\iota(U)$ 的补空间由 $\ker \psi$ 给出，于是我们有线性空间意义下的直和 $V = \iota(U) \oplus \ker \psi$．

通常认为有限维空间的补空间的存在性通过扩充基底保证，但取定基底即是引入内积，所以我们给出一个基底无关的构造．设 $U$, $V$, $W$ 配备内积 $\gamma_U$, $\gamma_V$, $\gamma_W$，$\iota : U \to V$ 和 $\pi : V \to W$ 是保内积的线性映射——即如下图表交换

:::{#fig-cd-inner-prod-split}

```{tikz}
\begin{tikzcd}
	0 & U & V & W & 0 \\
	0 & {U^*} & {V^*} & {W^*} & 0
	\arrow[from=1-1, to=1-2]
	\arrow["\iota", from=1-2, to=1-3]
	\arrow["{{\gamma_U}}", from=1-2, to=2-2]
	\arrow["\pi", from=1-3, to=1-4]
	\arrow["{{\gamma_V}}", from=1-3, to=2-3]
	\arrow[from=1-4, to=1-5]
	\arrow["{{\gamma_W}}", from=1-4, to=2-4]
	\arrow[from=2-2, to=2-1]
	\arrow["{{\iota^*}}", from=2-3, to=2-2]
	\arrow["{{\pi^*}}", from=2-4, to=2-3]
	\arrow[from=2-5, to=2-4]
\end{tikzcd}
```
:::

则在 $V \to V^*$ 的内积观点下，$\iota(U)$ 的补空间由
$$
\iota(U)^\perp := \{ v \in V : \forall u \in U,\, \langle v, \iota(u) \rangle_V = 0 \} = \ker (\iota^* \circ \gamma_V) = \ker (\gamma_U^{-1} \circ \iota^* \circ \gamma_V)
$$
给出，左分裂同态可构造为 $\psi := \gamma_U^{-1} \circ \iota^* \circ \gamma_V$——且该同态甚至保内积：

:::{.proof}

验证它确实是左分裂同态：
$$
\begin{aligned}
\psi \circ \iota
&= (\gamma_U^{-1} \circ \iota^* \circ \gamma_V) \circ \iota \\
&= \gamma_U^{-1} \circ (\iota^* \circ \gamma_V \circ \iota) \\
&= \gamma_U^{-1} \circ \gamma_U \\
&= \id_U
\end{aligned}
$$
也就是从 $U$ 出发顺时针转一圈是 $\id_U$．

验证它保内积（$\psi^* \circ \gamma_U \circ \psi = \gamma_V$）：
$$
\begin{aligned}
\psi^* \circ \gamma_U \circ \psi
&= \psi^* \circ \gamma_U \circ (\gamma_U^{-1} \circ \iota^* \circ \gamma_V) \\
&= \psi^* \circ \iota^* \circ \gamma_V \\
&= (\psi \circ \iota)^* \circ \gamma_V \\
&= \id_U^* \circ \gamma_V \\
&= \gamma_V
\end{aligned}
$$
即从 $V$ 出发逆时针转一圈是 $\id_V$．
:::

所以这真的给出了一个内积空间意义下的直和 $V = \iota(U) \oplus \iota(U)^\perp$．

### $G$-不变内积

下面为 $G$-模配备内积——自然要求 $\gamma_V : V \to V^*$ 是 $G$-模同态．这一要求可以等价地翻译为通常的内积写法 $\langle g \cdot v, g \cdot w \rangle_{\gamma} = \langle v, w \rangle_{\gamma}$，从而我们也称之为 $G$-不变内积：

:::{.proof}

$$
\begin{aligned}
\langle g \cdot v, g \cdot w \rangle_{\gamma}
&=  \gamma (g \cdot v) (g \cdot w) & \text{by natural isomorphism} \\
&= (g \cdot  \gamma)(v)(g \cdot w) & \text{by } \gamma \text{ is } G\text{-homomorphism} \\
&= (g^{-1} \cdot g \cdot  \gamma)(v)(w) & \text{by } G\text{-module structure of } V^* \\ 
&=  \gamma(v)(w) & \text{by module axiom} \\
&= \langle v, w \rangle_{ \gamma} & \text{by natural isomorphism}
\end{aligned}
$$
:::

### 内积的平均化提升

怎么为 $G$-模配备 $G$-不变内积？有了前面的铺垫，自然可以先任取一个线性空间意义下的内积 $\gamma \in \Hom(V, V^*)$，然后对其应用 $\Hom(V, V^*) \to \Hom_G(V, V^*)$ 的平均化投影得到得到 $G$-模同态
$$
\tilde \gamma : V \to V^*,\, v \mapsto \frac 1 {|G|} \sum_{g \in G} g \cdot \gamma(g^{-1} \cdot v)
$$
这一平均化也可翻译为内积写法 $\langle v, w \rangle_{\tilde \gamma} = \frac 1 {|G|} \sum_{g \in G} \langle g \cdot v, g \cdot w \rangle_{\tilde \gamma}$：

:::{.proof}

$$
\begin{aligned}
\langle v, w \rangle_{\tilde \gamma}
&= \tilde \gamma(v)(w) & \text{by natural isomorphism} \\
&= \frac 1 {|G|} \sum_{g \in G} (g \cdot \gamma)(v)(w) & \text{by definition of } \tilde\gamma \\
&= \frac 1 {|G|} \sum_{g \in G} \left( g \cdot \gamma(g^{-1} \cdot v) \right) (w) & \text{by } G\text{-module structure of } \Hom(V, V^*) \\
&= \frac 1 {|G|} \sum_{g \in G} \gamma(g^{-1} \cdot v)(g^{-1} \cdot w) & \text{by } G\text{-module structure of } V^* \\
&= \frac 1 {|G|} \sum_{g \in G} \gamma(g \cdot v)(g \cdot w) \\
&= \frac 1 {|G|} \sum_{g \in G} \langle g \cdot v, g \cdot w \rangle_{\tilde \gamma} & \text{by natural isomorphism}
\end{aligned}
$$
:::

即 $G$-不变内积可以通过任取线性空间意义下的内积做平均化提升得到．

### 补空间的平均化提升

设 $U$, $V$, $W$ 是 $G$-模，且线性空间正合列
$$
0 \longrightarrow U \longrightarrow V \longrightarrow W \longrightarrow 0
$$
有左分裂同态 $\psi : V \to U$．根据前述讨论，不妨认为 $U$, $V$, $W$ 配备内积 $\gamma_U$, $\gamma_V$, $\gamma_W$ 使得上述线性空间正合列在保内积意义下成立且分裂．

且存在线性空间意义下的分裂同态 $\psi : V \to U$ 使得 $\psi \circ \iota = \id_U$，则对 $\psi$ 做平均化提升得到的 $\tilde \psi : V \to U$ 也是一个左分裂同态：
$$
0 \longrightarrow U \longrightarrow V \longrightarrow W \longrightarrow 0
$$
